### ISSUE TITLE
'List index out of range' error during ranking step

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1008]
when I run this query in `master`:
```
    query = {"previous_message_processing_plan": {"processing_actions": [
        "add_qnode(curie=CHEMBL.COMPOUND:CHEMBL635, id=n0)",
        "add_qnode(type=protein, is_set=true, id=n1)",
        "add_qnode(type=chemical_substance, id=n2)",
        "add_qedge(source_id=n0, target_id=n1, id=e0)",
        "add_qedge(source_id=n1, target_id=n2, id=e1)",
        "expand(kp=ARAX/KG2)",
        "overlay(action=overlay_exposures_data, virtual_relation_label=E1, source_qnode_id=n0, target_qnode_id=n2)",
        "resultify()",
        "return(message=true, store=false)",
    ]}}
```
I get this error:

`ERROR: An uncaught error occurred: list index out of range: ['Traceback (most recent call last):\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 546, in executeProcessingPlan\n    ranker.aggregate_scores(message, response=response)\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 46, in aggregate_scores\n    result = query_graph_info.assess(message)\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/query_graph_info.py", line 155, in assess\n    start_node = singletons[0]\n', 'IndexError: list index out of range\n']`

here's the latter part of the log:
```
  - 2020-08-18 12:38:41.705242 DEBUG: Number of nodes in KG is 3902
  - 2020-08-18 12:38:41.708665 DEBUG: Number of nodes in KG by type is Counter({'chemical_substance': 3803, 'protein': 99})
  - 2020-08-18 12:38:41.708681 DEBUG: Number of edges in KG is 20323
  - 2020-08-18 12:38:41.728880 DEBUG: Number of edges in KG by type is Counter({'molecularly_interacts_with': 9419, 'interacts_with': 3644, 'related_to': 1993, 'inhibits': 1565, 'positively_regulates': 1396, 'affects': 789, 'agonist': 272, 'directly_interacts_with': 217, 'produces': 197, 'has_role': 169, 'part_of': 162, 'subclass_of': 156, 'antagonist': 82, 'derives_into': 62, 'is_substance_that_treats': 55, 'regulates': 39, 'equivalent_to': 37, 'has_icees_p-value_with': 22, 'located_in': 19, 'has_input': 8, 'contraindicated_with': 5, 'antisense': 5, 'binding_agent': 2, 'negatively_regulates': 2, 'increases_metabolic_processing_of': 1, 'predisposes': 1, 'causes_or_contributes_to': 1, 'close_match': 1, 'is_about': 1, 'activates': 1})
  - 2020-08-18 12:38:41.742556 DEBUG: Number of edges in KG with attributes is 20323
  - 2020-08-18 12:38:41.792047 DEBUG: Number of edges in KG by attribute Counter({'relation_curie': 20301, 'simplified_relation_curie': 20301, 'simplified_relation': 20301, 'edge_label': 20301, 'icees_p-value': 22})
  - 2020-08-18 12:38:41.792284 INFO: Processing action 'resultify' with parameters {'': 'true'}
  - 2020-08-18 12:38:41.792314 DEBUG: Applying Resultifier to Message with parameters {'': 'true'}
  - 2020-08-18 12:38:42.778626 INFO: Resultify created 22 results
  - 2020-08-18 12:38:42.778673 DEBUG: Cleaning up the KG to remove nodes not used in the results
  - 2020-08-18 12:38:42.802483 INFO: After cleaning, the KG contains 81 nodes and 416 edges
  - 2020-08-18 12:38:42.922076 INFO: Running experimental reranker on results
  - 2020-08-18 12:38:42.949021 ERROR: An uncaught error occurred: list index out of range: ['Traceback (most recent call last):\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 546, in executeProcessingPlan\n    ranker.aggregate_scores(message, response=response)\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/ARAX_ranker.py", line 46, in aggregate_scores\n    result = query_graph_info.assess(message)\n', '  File "/Users/aglen/translator/RTX_new/RTX/code/ARAX/test/../ARAXQuery/query_graph_info.py", line 155, in assess\n    start_node = singletons[0]\n', 'IndexError: list index out of range\n']
```
not sure if this is purely an issue with the ranker itself, or if it's being caused by an upstream issue?

**Comment by amykglen** [comment]
looks like this must've been fixed somewhere along the line, as the query runs fine on production now! https://arax.ncats.io/?r=2856
