### ISSUE TITLE
add command-line option "--savePickle" to multi_ont_to_json_kg.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1011]

**Comment by ericawood** [comment]
Hi @saramsey, this error showed up on the full build on kg2steve:
(stacktrace)
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1016, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 147, in make_kg2
    curie_to_uri_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 450, in make_nodes_dict_from_ontologies_list
    biolink_categories_ontology_depths)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 278, in get_biolink_category_for_node
    ret_category = max(candidate_category_depths, key=candidate_category_depths.get)
TypeError: '>' not supported between instances of 'int' and 'NoneType'

```

(screenshot)
![image](https://user-images.githubusercontent.com/36611732/90266813-7196c680-de09-11ea-97a0-30031236bc52.png)

**Comment by saramsey** [comment]
Thank you for reporting this issue. I am investigating.
