### ISSUE TITLE
TypeError in multi_ont_to_json_kg.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1014]
Kindly reported by @ericawood; copied from #1011

Hi @saramsey, this error showed up on the full build on kg2steve:
(stacktrace)

```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1016, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 147, in make_kg2
    curie_to_uri_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 450, in make_nodes_dict_from_ontologies_list
    biolink_categories_ontology_depths)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 278, in get_biolink_category_for_node
    ret_category = max(candidate_category_depths, key=candidate_category_depths.get)
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

**Comment by saramsey** [comment]
See commit 96c455b

**Comment by saramsey** [comment]
testing this on `kg2steve` now....

**Comment by saramsey** [comment]
Hi @ericawood I think this issue is resolved. I just successfully ran `build-multi-ont-kg.sh` on `kg2steve` (not in test mode). It ran to completion without giving a `TypeError`.
```
......
Calling make_map_of_node_ontology_ids_to_curie_ids
Calling get_rels_dict
Number of edges: 24710235
Number of nodes: 7076627
Saving JSON file
Sun Aug 16 09:41:09 UTC 2020
================= finished build-multi-ont-kg.sh =================
```
