### ISSUE TITLE
KG2 JSON is not biolink compliant due to spaces in property names`

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1016]
I ran
```
kgx validate  kg2-simplified-test.json -o test
```
on `kg2steve.rtx.ai` with KGX version:
```
kgx, version 0.0.1
```
the output is:
```
2.2.3
    return callback(*args, **kwargs)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/click-7.1.2-py3.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/kgx/venv/bin/translator_kgx.py", line 400, in validate
    t.parse(path, input_format=format)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/kgx/transformers/json_transformer.py", line 45, in parse
    self.load(obj)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/kgx/transformers/json_transformer.py", line 60, in load
    self.load_edges(obj['edges'])
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/kgx/transformers/json_transformer.py", line 88, in load_edges
    self.load_edge(edge)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/kgx/transformers/pandas_transformer.py", line 313, in load_edge
    edge = Transformer.validate_edge(edge)
  File "/home/ubuntu/kgx/venv/lib/python3.7/site-packages/kgx/transformers/transformer.py", line 261, in validate_edge
    raise KeyError("edge does not have 'edge_label' property: {}".format(edge))
KeyError: "edge does not have 'edge_label' property: {'edge label': 'subclass_of', 'negated': False, 'object': 'biolink:MacromolecularMachine', 'provided by': ['biolink_download_source:biolink-model.owl'], 'publications': [], 'publications info': {}, 'relation': 'rdfs:subClassOf', 'simplified edge label': 'subclass_of', 'simplified relation': 'biolink:subclass_of', 'subject': 'biolink:MacromolecularComplex', 'update date': 'Sat Aug  1 00:43:02 2020'}"
```

**Comment by saramsey** [comment]
see JSON example on the KGX data preparation page:

https://github.com/NCATS-Tangerine/kgx/blob/master/data-preparation.md

**Comment by ericawood** [comment]
Hi @saramsey,
I think that this created a new bug.

I ran: (I was working on #927)
```
ubuntu@ip-172-31-23-154:~/kg2-code$ ~/kg2-venv/bin/python3 multi_ont_to_json_kg.py --savePickle --test curies-to-categories.yaml curies-to-urls-map.yaml ont-load-doid.yaml ~/kg2-build/kg2-doid.json > doidtemp.txt
Traceback (most recent call last):
  File "multi_ont_to_json_kg.py", line 1026, in <module>
    save_pickle)
  File "multi_ont_to_json_kg.py", line 147, in make_kg2
    curie_to_uri_expander)
  File "multi_ont_to_json_kg.py", line 613, in make_nodes_dict_from_ontologies_list
    source_ontology_update_date = source_ontology_information['update_date']
KeyError: 'update_date'
```

ont-load-doid.yaml looks like this:
```
- # maps to CURIE prefix: biolink
  url: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl
  file: biolink-model.owl
  download: true
  title: Biolink meta-model
-
  url:  http://purl.obolibrary.org/obo/doid.owl
  file: doid.owl
  download: true
  title: Disease Ontology
```

So, I added in an except, such that if the `KeyError` described above occurred again, it would print out the `source_ontology_information`. Here is that data, before it failed due to an `UnboundLocalError` (part of my debugging process - break it after the first issue).
```
{'id': 'biolink_download_source:biolink-model.owl', 'iri': 'https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl', 'name': 'Biolink meta-model', 'full name': 'Biolink meta-model', 'category': 'biolink:DataFile', 'category label': 'data_file', 'description': None, 'synonym': [], 'publications': [], 'creation date': None, 'update date': 'Fri Aug 14 21:36:49 2020', 'deprecated': False, 'replaced by': None, 'provided by': 'biolink_download_source:biolink-model.owl', 'ontology node ids': ['https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl'], 'xrefs': []}
```
