### ISSUE TITLE
build fail due to typo in Relation Ontology

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1023]
This issue in `ro.owl`:
```
ubuntu@ip-172-31-0-169:~/kg2-build$ grep 'ttp://www.geneontology.org/formats/oboInOwl#created_by' *.owl | grep -v http
ro.owl:    <!-- ttp://www.geneontology.org/formats/oboInOwl#created_by -->
ro.owl:    <owl:AnnotationProperty rdf:about="ttp://www.geneontology.org/formats/oboInOwl#created_by"/>
```
is causing this:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1047, in <module>
    save_pickle)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 147, in make_kg2
    curie_to_uri_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 516, in make_nodes_dict_from_ontologies_list
    bpv_pred_curie = convert_bpv_pred_to_curie_func(bpv_pred)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1010, in <lambda>
    curie_expander)
  File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1001, in convert_bpv_predicate_to_curie
    raise ValueError('unable to expand CURIE: ' + bpv_pred)
ValueError: unable to expand CURIE: ttp://www.geneontology.org/formats/oboInOwl#created_by
```

**Comment by saramsey** [comment]
Looks like this is already fixed in RO:
<img width="515" alt="Screen Shot 2020-08-18 at 9 22 35 AM" src="https://user-images.githubusercontent.com/5562107/90539448-acb03700-e134-11ea-881d-e99fe88d4d4e.png">

**Comment by saramsey** [comment]
I also fixed this in the `/home/ubuntu/kg2-build/ro.owl` file on `kg2dev.rtx.ai`, and restarted the build.
