### ISSUE TITLE
Q31 doesn't work with the UI

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#103]
This is the "what kinds of questions can RTX answer" query template. This may be due to the fact that it doesn't expect any ``terms``, so the UI thinks there was a parsing error. Quick and dirty possible fix: populate ``terms`` with bogus info.

**Comment by edeutsch** [comment]
yes, we changed the rule to: if no terms, then error out. You could modify things to that "RTX" is the term and then question template is "what kinds of questions can <entity> answer?" where {"entity": "RTX"} is a valid terms. one could imagine "2 year olds" being another plausible entity. Or dogs. A bit silly, but seems reasonable within the framework?

**Comment by dkoslicki** [comment]
Ok, should be fixed now (used 'placeholder').

**Comment by edeutsch** [comment]
Tried to roll out this fix and get this:

Failed to add operation for POST /test/api/rtx/v1/query
Traceback (most recent call last):
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation
    pythonic_params=self.pythonic_params)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/operation.py", line 215, in __init__
    resolution = resolver.resolve(self)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 39, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "swagger_server.controllers.query_controller.query"! Import error was 'No module named 'QueryCOHD''>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/__main__.py", line 16, in <module>
    main()
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/__main__.py", line 11, in main
    app.add_api('swagger.yaml', arguments={'title': 'RTX'})
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 73, in add_api
    resolver=resolver, resolver_error=resolver_error, pythonic_params=pythonic_params
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/abstract.py", line 168, in add_api
    pythonic_params=pythonic_params)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/flask_api.py", line 61, in __init__
    pythonic_params=pythonic_params
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 152, in __init__
    self.add_paths()
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 272, in add_paths
    self._handle_add_operation_error(path, method, exc_info)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 286, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/home/rt/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/utils.py", line 39, in get_function_from_name
    raise last_import_error
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/utils.py", line 27, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/query_controller.py", line 7, in <module>
    from RTXQuery import RTXQuery
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/RTXQuery.py", line 19, in <module>
    from ParseQuestion import ParseQuestion
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 3, in <module>
    import Question
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/Question.py", line 22, in <module>
    import ReasoningUtilities as RU
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 18, in <module>
    import QueryCOHD
ImportError: No module named 'QueryCOHD'

**Comment by edeutsch** [comment]
okay, there's no import error any more, but it doesn't quite work yet. It looks like the executed command line is:
python3 WhatQuestionsCanYouAnswer.py

If I run that on the command line I get:
what proteins are associated with Enlargement of the proximal femoral epiphysis
Which genetic conditions might offer protection against noninvasive malignant thymoma?
what drugs target proteins in the pathway Response to elevated platelet cytosolic Ca2+
what are the phenotypes of the disease PORPHYRIA CUTANEA TARDA
what proteins are associated with similar phenotypes to 

The response needs to be JSON, otherwise this won't work. Does this script need a json option?

**Comment by edeutsch** [comment]
hmm, JSON parser is failing. I don't think single quotes is valid JSON? Are you maybe just dumping a Python string instead producing real JSON?

**Comment by dkoslicki** [comment]
Dang it! Was using ``print(response)`` instead of ``response.print()``. Fix pushed

**Comment by edeutsch** [comment]
okay, the code is all working now, thanks. I made a few adjustments to the API code to handle this somewhat gracefully..

Luis, over to you, would do a git pull and improve the rendering of the result of:
what types of questions can rtx answer

**Comment by isbluis** [comment]
Added handling of results with no graph information. 

Question:  for this specific question, should the items in the result list have a confidence of 1?  Since we know we can answer them, or is that a mis-use of this field?  It seems odd to have a confidence of zero, IMO.

**Comment by dkoslicki** [comment]
@isbluis I changed the confidence to 1. Also, it looks like the UI is only showing the text for one of the results, instead of the 5 that are returned.

**Comment by isbluis** [comment]
@dkoslicki Thanks.  I can see all 5 results using the latest commit of rtx.js -- they are each wrapped inside an expandable open/close section, though only the first one is opened by default.  Is this the issue?

**Comment by dkoslicki** [comment]
@isbluis Yes, I now see all 5 results on http://rtx.ncats.io/devLM/. However, these still have a confidence of 0, was the latest code not pulled?

**Comment by isbluis** [comment]
@dkoslicki I just did a git pull again and restarted my Flask server, but still see the zero confidence in the results.  I think it may be an issue with my locally cached results?  I am implementing a bypass for this for issue #108.  Will verify once I commit that change.

**Comment by dkoslicki** [comment]
I still see confidence of 0 when using cache on **and** with cache off (on /devED, /devLM, and production). Confidence is [set to one on my end](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/WhatQuestionsCanYouAnswer.py#L48), so I don't know if this is a caching issue, or something else going on with the UI.

**Comment by edeutsch** [comment]
okay, I will look into it sometime. I have everything about to break again with a new API definition, so this is not super high on the list at the moment. there is code that says if there is no confidence provided, then set it to 0. There might be a bug there.

**Comment by dkoslicki** [comment]
Tested on current implementation, works as intended, confidence of 1. Closing
