### ISSUE TITLE
'EdgeAttribute object is not iterable' error with expand(kp=COHD) query

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1041]
when I run this DSL on https://arax.rtx.ai/test/:
```
add_qnode(curie=DOID:10718, id=n00)
add_qnode(type=chemical_substance, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=COHD, COHD_method=observed_expected_ratio, COHD_method_percentile=95)
resultify()
```
I'm seeing this error during the ranking step:

`ERROR:  An uncaught error occurred: 'EdgeAttribute' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 546, in executeProcessingPlan\n ranker.aggregate_scores(message, response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 67, in aggregate_scores\n for edge_attribute in edge.edge_attributes:\n', "TypeError: 'EdgeAttribute' object is not iterable\n"]`

here's the latter part of the log:
```
2020-08-27 01:40:24.208508 INFO:  After Expand, Message.KnowledgeGraph has 9 nodes and 8 edges (e00: 8, n00: 1, n01: 8)
2020-08-27 01:40:24.208565 INFO:  Processing action 'resultify' with parameters {'': 'true'}
2020-08-27 01:40:24.208585 DEBUG:  Applying Resultifier to Message with parameters {'': 'true'}
2020-08-27 01:40:24.209360 INFO:  Resultify created 8 results
2020-08-27 01:40:24.209375 DEBUG:  Cleaning up the KG to remove nodes not used in the results
2020-08-27 01:40:24.209410 INFO:  After cleaning, the KG contains 9 nodes and 8 edges
2020-08-27 01:40:24.209422 INFO:  Running experimental reranker on results
2020-08-27 01:40:24.209692 ERROR:  An uncaught error occurred: 'EdgeAttribute' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 546, in executeProcessingPlan\n ranker.aggregate_scores(message, response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 67, in aggregate_scores\n for edge_attribute in edge.edge_attributes:\n', "TypeError: 'EdgeAttribute' object is not iterable\n"]
```
looking at the JSON, it looks like the problem is maybe that `edge.edge_attributes` isn't a list on COHD edges? here's an example:
```
{
        "confidence": null,
        "defined_datetime": null,
        "edge_attributes": {
          "name": "ln_observed_expected_ratio",
          "type": "EDAM:data_0951",
          "url": "http://cohd.smart-api.info/",
          "value": "3.832772"
        },
        "evidence_type": null,
        "id": "COHD:MONDO:0001103-has_ln_observed_expected_ratio_with-CHEMBL.COMPOUND:CHEMBL1201567",
        "is_defined_by": "ARAX",
        "negated": null,
        "provided_by": "ARAX/COHD",
        "publications": null,
        "qedge_ids": [
          "e00"
        ],
        "qualifiers": null,
        "relation": null,
        "source_id": "MONDO:0001103",
        "target_id": "CHEMBL.COMPOUND:CHEMBL1201567",
        "type": "has_ln_observed_expected_ratio_with",
        "weight": null
      }
```
I think `edge_attributes` should look like this instead?:
```
        "edge_attributes": [
          {
          "name": "ln_observed_expected_ratio",
          "type": "EDAM:data_0951",
          "url": "http://cohd.smart-api.info/",
          "value": "3.832772"
          }
        ],
```

**Comment by chunyuma** [comment]
Hi @amykglen, I changed the `edge.edge_attributes` to  a list in COHD edge in `master` branch. Could you please help me check if this is still a problem?

**Comment by edeutsch** [comment]
I have just rolled out the latest `master` to /test and /beta for your testing

**Comment by chunyuma** [comment]
Thanks @edeutsch.

**Comment by edeutsch** [comment]
I am seeing errors in the test suite now:
test_ARAX_expand.py::test_COHD_expand_observed_expected_ratio FAILED                                                                                [ 27%]
test_ARAX_expand.py::test_COHD_expand_chi_square INFO: Disconnecting from database
FAILED                                                                                             [ 28%]

**Comment by amykglen** [comment]
yeah, I'm seeing this error now on `/test` when I try running the same query:

```
2020-08-27 16:56:52.059204 DEBUG:  Processing query results for edge e00 by using natural logarithm of observed expected ratio
2020-08-27 16:56:52.059224 INFO:  Getting the OMOP id for n00
2020-08-27 16:56:52.159373 ERROR:  An uncaught error occurred: 'EdgeAttribute' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 492, in executeProcessingPlan\n result = expander.apply(message,action[\'parameters\'], response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 127, in apply\n query_graph, use_synonyms, synonym_handling, log)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 201, in _expand_edge\n answer_kg, edge_to_nodes_map = kp_querier.answer_one_hop_query(edge_query_graph)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 79, in answer_one_hop_query\n final_kg, edge_to_nodes_map = self._answer_query_using_COHD_observed_expected_ratio(query_graph, COHD_method_percentile, continue_if_no_results, log)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 530, in _answer_query_using_COHD_observed_expected_ratio\n swagger_edge = self._convert_to_swagger_edge(source_preferred_id, target_preferred_id, "ln_observed_expected_ratio", new_edge[source_preferred_id][target_preferred_id])\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/COHD_querier.py", line 954, in _convert_to_swagger_edge\n swagger_edge.edge_attributes += EdgeAttribute(type=type, name=name, value=str(value), url=url)\n', "TypeError: 'EdgeAttribute' object is not iterable\n"]
```

**Comment by chunyuma** [comment]
Sorry, I just made a mistake and forgot to modify the test cases. I've pushed the new commit to fix the error. I tested the problem locally and it passed all test cases now. @edeutsch, could you please help rolling out the latest master to /test and /beta again? Thank you!

**Comment by edeutsch** [comment]
I have just rolled out the latest master to /test

**Comment by amykglen** [comment]
nice, looks good to me on `/test` now! closing.
