### ISSUE TITLE
'NoneType object is not iterable' error with overlay predict_drug_treats_disease on /test

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1042]
when I run this JSON query on https://arax.rtx.ai/test/:
```
{
   "edges": [
      {
         "id": "qg2",
         "source_id": "qg1",
         "target_id": "qg0"
      }
   ],
   "nodes": [
      {
         "id": "qg0",
         "curie": "DOID:14330",
         "type": "disease"
      },
      {
         "id": "qg1",
         "type": "chemical_substance"
      }
   ]
}
```
I'm seeing this error:

`
ERROR:  An uncaught error occurred: 'NoneType' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 502, in executeProcessingPlan\n result = overlay.apply(message, action[\'parameters\'], response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 145, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 480, in __predict_drug_treats_disease\n response = PDTD.predict_drug_treats_disease()\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 123, in predict_drug_treats_disease\n res = list(itertools.product(self.convert_to_trained_curies(source_curie), self.convert_to_trained_curies(target_curie)))\n', "TypeError: 'NoneType' object is not iterable\n"]
`

here's the latter part of the log:
```
2020-08-27 21:45:46.178941 DEBUG:  Number of edges in KG with attributes is 1702
2020-08-27 21:45:46.181913 DEBUG:  Number of edges in KG by attribute Counter({'observed_expected_ratio': 1281, 'relation_curie': 421, 'simplified_relation_curie': 421, 'simplified_relation': 421, 'edge_label': 421})
2020-08-27 21:45:46.181942 INFO:  Processing action 'overlay' with parameters {'action': 'predict_drug_treats_disease', 'source_qnode_id': 'qg1', 'target_qnode_id': 'qg0', 'virtual_relation_label': 'P1'}
2020-08-27 21:45:46.181960 DEBUG:  Applying Overlay to Message with parameters {'action': 'predict_drug_treats_disease', 'source_qnode_id': 'qg1', 'target_qnode_id': 'qg0', 'virtual_relation_label': 'P1'}
2020-08-27 21:45:48.488247 DEBUG:  Computing drug disease treatment probability based on a machine learning model
2020-08-27 21:45:48.488273 INFO:  Computing drug disease treatment probability based on a machine learning model: See [this publication](https://doi.org/10.1101/765305) for more details about how this is accomplished.
2020-08-27 21:46:49.952310 ERROR:  An uncaught error occurred: 'NoneType' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 502, in executeProcessingPlan\n result = overlay.apply(message, action[\'parameters\'], response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 145, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 480, in __predict_drug_treats_disease\n response = PDTD.predict_drug_treats_disease()\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 123, in predict_drug_treats_disease\n res = list(itertools.product(self.convert_to_trained_curies(source_curie), self.convert_to_trained_curies(target_curie)))\n', "TypeError: 'NoneType' object is not iterable\n"]
```
I believe this is the DSL template being run behind the scenes for this query, fyi:
https://github.com/RTXteam/RTX/blob/d785edbabbb17461cd0de418b10ed3da145bd917/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L99-L115

**Comment by edeutsch** [comment]
I have just now rolled out the latest to /test and /beta. I am under the impression that I am still waiting for one more fix or testing before we release to manufacturing?

**Comment by chunyuma** [comment]
This issue should be fixed.

**Comment by edeutsch** [comment]
I just did another git pull and there are two more updates:
 code/ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py | 18 +++++++++++++++---
 code/ARAX/ARAXQuery/Overlay/predictor/predictor.py         |  2 +-

All tests are now passing!
RTM?

**Comment by amykglen** [comment]
yep - just confirmed this is now working on `/test`. no other issues that I'm aware of!

**Comment by amykglen** [comment]
actually, I guess there is one more error I know of on `/test`, @edeutsch: issue #1008.
