### ISSUE TITLE
Genetics KP issues

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1086]
1. The DSL
```
add_qnode(curie=MONDO:0001475, id=n00, type=disease)
add_qnode(type=protein, id=n01, is_set=true)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=molecularly_interacts_with)
expand(edge_id=e00, kp=ARAX/KG2, continue_if_no_results=true)
expand(edge_id=e01, kp=GeneticsKP, continue_if_no_results=true)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results, max_results=100)
return(message=true, store=true)
```
Results in:
```
<snip>
2020-10-04 23:10:29.501691 INFO:  Expanding edge e01 using GeneticsKP
2020-10-04 23:10:29.501774 DEBUG:  Modified QG for this edge is (n01:['protein', 'gene'] [196 curies])-molecularly_interacts_with-(n02:chemical_substance)
2020-10-04 23:10:29.511689 ERROR:  An uncaught error occurred: 'list' object has no attribute 'lower': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 497, in executeProcessingPlan\n result = expander.apply(message,action[\'parameters\'], response=response)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 135, in apply\n query_graph, use_synonyms, log)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 216, in _expand_edge\n answer_kg, edge_to_nodes_map = kp_querier.answer_one_hop_query(edge_query_graph)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/genetics_querier.py", line 55, in answer_one_hop_query\n modified_query_graph = self._pre_process_query_graph(query_graph, log)\n', ' File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/genetics_querier.py", line 116, in _pre_process_query_graph\n converted_curies = synonymizer.convert_curie(qnode.curie, self.prefix_mappings[qnode.type])\n', ' File "/mnt/data/orangeboard/test/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/node_synonymizer.py", line 1204, in convert_curie\n curies_and_types = self.get_curies_and_types(curie, kg_name)\n', ' File "/mnt/data/orangeboard/test/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/node_synonymizer.py", line 1071, in get_curies_and_types\n cursor.execute( f"SELECT unique_concept_curie FROM {kg_prefix}_synonym{TESTSUFFIX} WHERE lc_name = ?", (name.lower(),) )\n', "AttributeError: 'list' object has no attribute 'lower'\n"]
```
Seems to be a bug.

2. The DSL
```
add_qnode(curie=MONDO:0001475, id=n00, type=disease)
add_qnode(type=protein, id=n01, is_set=true)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01, type=molecularly_interacts_with)
expand(edge_id=e01, kp=ARAX/KG2, continue_if_no_results=true)
expand(edge_id=e00, kp=GeneticsKP, continue_if_no_results=true)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results, max_results=100)
return(message=true, store=true)
```
(Note the different edges being expanded)
Results in:
```
2020-10-04 23:11:59.851677 DEBUG:  Applying Expand to Message with parameters {'edge_id': 'e01', 'node_id': None, 'kp': 'ARAX/KG2', 'enforce_directionality': False, 'use_synonyms': True, 'continue_if_no_results': True, 'COHD_method': 'paired_concept_freq', 'COHD_method_percentile': 99, 'include_integrated_score': False}
2020-10-04 23:11:59.851826 DEBUG:  Query graph for this Expand() call is: {'nodes': [{'id': 'n01', 'curie': None, 'type': 'protein', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'chemical_substance', 'is_set': None}], 'edges': [{'id': 'e01', 'type': 'molecularly_interacts_with', 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
2020-10-04 23:11:59.851848 INFO:  Expanding edge e01 using ARAX/KG2
2020-10-04 23:11:59.851925 DEBUG:  Modified QG for this edge is (n01:['protein', 'gene'])-molecularly_interacts_with-(n02:chemical_substance)
2020-10-04 23:11:59.851936 ERROR:  Cannot expand an edge for which neither end has any curies. (Could not find curies to use from a prior expand step, and neither qnode has a curie specified.)
```
Why is COHD being consulted when I asked for GeneticsKP?

**Comment by dkoslicki** [comment]
Ok, I see now why the COHD parameters are in there (after updating the documentation), but it's still a problem that while specific curies for n00 and n01 have been populated, GeneticsKP still borks

**Comment by amykglen** [comment]
re: 1) yes, this is because GeneticsKP is only currently set up to be used as the first hop in a query. (I haven't quite yet made it able to accept multiple input curies, and thus it can't be used for the 2nd+ hop right now.)

re: 2) it looks like you're trying to expand edge `e01` first (before `e00`), and neither of `e01`'s nodes are 'pinned' in the QG (i.e., have a curie specified). so expand is rightfully error-ing out, because the KG2 query `(generic protein)--(generic chemical_substance)` would result in a _massive_ answer.

**Comment by dkoslicki** [comment]
Thanks for the clarification @amykglen; I misunderstood the second-hop thing as not being able to use `edge_id=[e1,e2]`, but your comment clarifies it.

**Comment by amykglen** [comment]
cool - I'm going to close this issue then (will wrap up the GeneticsKP integration in #1064)
