### ISSUE TITLE
malformed COHD database

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1141]
In ARAX/test:
```
pytest -v test_ARAX_expand.py -k test_COHD_expand_chi_square
```
I get the following error
```
~/Desktop/RTX/code/ARAX/test$ pytest -v test_ARAX_expand.py -k test_COHD_expand_chi_square
================================ test session starts ================================
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /home/dkoslicki/anaconda3/envs/RTX37/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/dkoslicki/Desktop/RTX/code/ARAX/test
collected 36 items / 35 deselected / 1 selected                                     

test_ARAX_expand.py::test_COHD_expand_chi_square INFO: Disconnecting from database
FAILED                       [100%]

===================================== FAILURES ======================================
____________________________ test_COHD_expand_chi_square ____________________________

    def test_COHD_expand_chi_square():
        actions_list = [
            "add_qnode(curie=DOID:5844, id=n00)",
            "add_qnode(type=chemical_substance, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "expand(edge_id=e00, kp=COHD, COHD_method=chi_square, COHD_method_percentile=95)",
            "return(message=true, store=false)"
        ]
>       nodes_by_qg_id, edges_by_qg_id = _run_query_and_do_standard_testing(actions_list)

test_ARAX_expand.py:568: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

actions_list = ['add_qnode(curie=DOID:5844, id=n00)', 'add_qnode(type=chemical_substance, id=n01)', 'add_qedge(source_id=n00, target_...'expand(edge_id=e00, kp=COHD, COHD_method=chi_square, COHD_method_percentile=95)', 'return(message=true, store=false)']
kg_should_be_incomplete = False, debug = False, should_throw_error = False

    def _run_query_and_do_standard_testing(actions_list: List[str], kg_should_be_incomplete=False, debug=False,
                                           should_throw_error=False) -> Tuple[Dict[str, Dict[str, Node]], Dict[str, Dict[str, Edge]]]:
        # Run the query
        araxq = ARAXQuery()
        response = araxq.query({"previous_message_processing_plan": {"processing_actions": actions_list}})
        message = araxq.message
        if response.status != 'OK':
            print(response.show(level=Response.DEBUG))
>       assert response.status == 'OK' or should_throw_error
E       AssertionError: assert ('ERROR' == 'OK'
E         - OK
E         + ERROR or False)

test_ARAX_expand.py:32: AssertionError
------------------------------- Captured stdout call --------------------------------
INFO: Connecting to database
Response:
  status: ERROR
  n_errors: 1  n_warnings: 0  n_messages: 28
  error_code: UncaughtARAXiError   message: An uncaught error occurred: database disk image is malformed: ['Traceback (most recent call last):\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 499, in executeProcessingPlan\n    result = expander.apply(message,action[\'parameters\'], response=response)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 270, in apply\n    query_graph, use_synonyms, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 355, in _expand_edge\n    answer_kg, edge_to_nodes_map = kp_querier.answer_one_hop_query(edge_query_graph)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 82, in answer_one_hop_query\n    final_kg, edge_to_nodes_map = self._answer_query_using_COHD_chi_square(query_graph, COHD_method_percentile, continue_if_no_results, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 654, in _answer_query_using_COHD_chi_square\n    source_qnode_omop_ids = self._get_omop_id_from_curies(source_qnode, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 920, in _get_omop_id_from_curies\n    omop_ids = self.cohdindex.get_concept_ids(qnode.curie)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/Expand/../../../ARAX/KnowledgeSources/COHD_local/scripts/COHDIndex.py", line 259, in get_concept_ids\n    cursor.execute(f"select distinct t1.preferred_curie, t1.concept_id from CURIE_TO_OMOP_MAPPING t1 inner join CONCEPTS t2 on t1.concept_id = t2.concept_id where preferred_curie=\'{preferred_curie}\';")\n', 'sqlite3.DatabaseError: database disk image is malformed\n']
  - 2020-12-02 15:29:14.491401 INFO: ARAXQuery launching on incoming Message
  - 2020-12-02 15:29:14.491419 INFO: Examine input query for needed information for dispatch
  - 2020-12-02 15:29:14.491423 INFO: Found input processing plan. Sending to the ProcessingPlanExecutor
  - 2020-12-02 15:29:14.491429 DEBUG: Entering executeProcessingPlan
  - 2020-12-02 15:29:14.530464 DEBUG: No starting messages were referenced. Will start with a blank template Message
  - 2020-12-02 15:29:14.530841 DEBUG: Found processing_actions
  - 2020-12-02 15:29:14.530856 INFO: Parsing input actions list
  - 2020-12-02 15:29:14.530860 DEBUG: Parsing action: add_qnode(curie=DOID:5844, id=n00)
  - 2020-12-02 15:29:14.531235 DEBUG: Parsing action: add_qnode(type=chemical_substance, id=n01)
  - 2020-12-02 15:29:14.531250 DEBUG: Parsing action: add_qedge(source_id=n00, target_id=n01, id=e00)
  - 2020-12-02 15:29:14.531262 DEBUG: Parsing action: expand(edge_id=e00, kp=COHD, COHD_method=chi_square, COHD_method_percentile=95)
  - 2020-12-02 15:29:14.531275 DEBUG: Parsing action: return(message=true, store=false)
  - 2020-12-02 15:29:14.539066 INFO: Processing action 'add_qnode' with parameters {'curie': 'DOID:5844', 'id': 'n00'}
  - 2020-12-02 15:29:14.539104 INFO: Adding a QueryNode to Message with input parameters {'id': 'n00', 'curie': 'DOID:5844', 'name': None, 'type': None, 'is_set': None}
  - 2020-12-02 15:29:14.539290 DEBUG: Looking up CURIE DOID:5844 in NodeSynonymizer
  - 2020-12-02 15:29:14.542036 INFO: CURIE DOID:5844 is found. Adding it to the qnode
  - 2020-12-02 15:29:14.542133 INFO: Processing action 'add_qnode' with parameters {'type': 'chemical_substance', 'id': 'n01'}
  - 2020-12-02 15:29:14.542150 INFO: Adding a QueryNode to Message with input parameters {'id': 'n01', 'curie': None, 'name': None, 'type': 'chemical_substance', 'is_set': None}
  - 2020-12-02 15:29:14.542260 INFO: Processing action 'add_qedge' with parameters {'source_id': 'n00', 'target_id': 'n01', 'id': 'e00'}
  - 2020-12-02 15:29:14.542272 INFO: Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': None}
  - 2020-12-02 15:29:14.542291 INFO: Processing action 'expand' with parameters {'edge_id': 'e00', 'kp': 'COHD', 'COHD_method': 'chi_square', 'COHD_method_percentile': '95'}
  - 2020-12-02 15:29:14.542316 DEBUG: Applying Expand to Message with parameters {'kp': 'COHD', 'edge_id': 'e00', 'node_id': None, 'continue_if_no_results': False, 'use_synonyms': True, 'COHD_method': 'chi_square', 'COHD_method_percentile': '95'}
  - 2020-12-02 15:29:14.542423 DEBUG: Query graph for this Expand() call is: {'nodes': [{'id': 'n00', 'curie': 'DOID:5844', 'type': None, 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'chemical_substance', 'is_set': None}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}]}
  - 2020-12-02 15:29:14.542440 INFO: Expanding qedge e00 using COHD
  - 2020-12-02 15:29:14.542479 DEBUG: Modified QG for this qedge is (n00:None DOID:5844)--(n01:chemical_substance)
  - 2020-12-02 15:29:14.547575 DEBUG: Processing query results for edge e00 by using chi square pvalue
  - 2020-12-02 15:29:14.547605 INFO: Getting the OMOP id for n00
  - 2020-12-02 15:29:14.555898 ERROR: An uncaught error occurred: database disk image is malformed: ['Traceback (most recent call last):\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 499, in executeProcessingPlan\n    result = expander.apply(message,action[\'parameters\'], response=response)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 270, in apply\n    query_graph, use_synonyms, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 355, in _expand_edge\n    answer_kg, edge_to_nodes_map = kp_querier.answer_one_hop_query(edge_query_graph)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 82, in answer_one_hop_query\n    final_kg, edge_to_nodes_map = self._answer_query_using_COHD_chi_square(query_graph, COHD_method_percentile, continue_if_no_results, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 654, in _answer_query_using_COHD_chi_square\n    source_qnode_omop_ids = self._get_omop_id_from_curies(source_qnode, log)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/test/../ARAXQuery/Expand/COHD_querier.py", line 920, in _get_omop_id_from_curies\n    omop_ids = self.cohdindex.get_concept_ids(qnode.curie)\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/Expand/../../../ARAX/KnowledgeSources/COHD_local/scripts/COHDIndex.py", line 259, in get_concept_ids\n    cursor.execute(f"select distinct t1.preferred_curie, t1.concept_id from CURIE_TO_OMOP_MAPPING t1 inner join CONCEPTS t2 on t1.concept_id = t2.concept_id where preferred_curie=\'{preferred_curie}\';")\n', 'sqlite3.DatabaseError: database disk image is malformed\n']

============================== short test summary info ==============================
FAILED test_ARAX_expand.py::test_COHD_expand_chi_square - AssertionError: assert (...
========================= 1 failed, 35 deselected in 5.18s ==========================
```
the relevant portion is:
```
cursor.execute(f"select distinct t1.preferred_curie, t1.concept_id from CURIE_TO_OMOP_MAPPING t1 inner join CONCEPTS t2 on t1.concept_id = t2.concept_id where preferred_curie=\'{preferred_curie}\';")\n', 'sqlite3.DatabaseError: database disk image is malformed\n'
```

**Comment by dkoslicki** [comment]
This issue is causing multiple other tests to fail as well

**Comment by amykglen** [comment]
in case it's helpful: I've seen this error before in my local environment when the COHD database download had been interrupted part way through. deleting the database and re-downloading it fixed the problem for me.

**Comment by finnagin** [comment]
@dkoslicki I think like Amy said re-downloading should fix it. I just tried running this and it passed for me.

**Comment by edeutsch** [comment]
all tests are passing on `master` on the main server

**Comment by dkoslicki** [comment]
Ok, it's probably a local DB corruption or the like. @finnagin I assume checking DB integrity would cause a major performance hit, right? Since all tests are passing on master, I'll close this as a non-issue.

**Comment by edeutsch** [comment]
One could easily wrap the database access in a try-except and report a database problem in a nice error message if it fails. That shouldn't cause any performance hit.

**Comment by dkoslicki** [comment]
Ah yes! @finnagin do you mind wrapping all database calls with try/except's?

**Comment by finnagin** [comment]
@dkosliki I've added try/excepts to the OverlayClinicalInfo and PredictDrugTreatsDisease calls when they try to load databases which if they fail it will add an error message to the response like "Internal Error encountered connecting to the local _______ database." and will return the traceback. It looks like the normalized google distance code already has error catching for when it tries to load its database so I didn't need to add anything there.

**Comment by dkoslicki** [comment]
@dkoslicki to test and close
