### ISSUE TITLE
future compatibility issue in python3.9

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1179]
Just an FYI, when I create a clean python3.9 virtualenv and install `ontobio` into it
```
python3 -m venv venv
source venv/bin/activate
pip3 install ontobio
```
and then when I try to import `ontobio`,
```
python3.9
>>> import ontobio
```
I get the following error, which looks to be ontobio using an ancient version of networkx (2.2 ) which is using a method that has been deprecated, and should probably be changed to `math.gcd`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/__init__.py", line 6, in <module>
    from .ontol_factory import OntologyFactory
  File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/ontol_factory.py", line 7, in <module>
    import ontobio.obograph_util as obograph_util
  File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/obograph_util.py", line 5, in <module>
    from ontobio.ontol import LogicalDefinition, PropertyChainAxiom
  File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/ontol.py", line 10, in <module>
    import networkx as nx
  File "/private/tmp/venv/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/private/tmp/venv/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/private/tmp/venv/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/private/tmp/venv/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/private/tmp/venv/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
```

**Comment by saramsey** [comment]
See this:
```
(venv) sramsey-laptop:tmp sramsey$ pip3 freeze | grep ontobio
ontobio==2.1.2
(venv) sramsey-laptop:tmp sramsey$ pip3 freeze | grep networkx
networkx==2.2
```
confirming that even the most recent version of ontobio is hardcoded to use that ancient version of networkx. We should probably file an issue report with the ontobio people.
https://github.com/biolink/ontobio/issues

**Comment by saramsey** [comment]
Have logged this issue in the Ontobio project, here:
https://github.com/biolink/ontobio/issues/506

**Comment by saramsey** [comment]
see the reply from Deepak Unni here:

https://github.com/biolink/ontobio/issues/506#issuecomment-757021111

**Comment by saramsey** [comment]
we should check back monthly, to see when the new ontobio comes out with this issue resolved.

**Comment by saramsey** [comment]
One option is just to fork ontobio. What do you think, @kvarforl ?

**Comment by kvarforl** [comment]
@saramsey just to be clear, you're suggesting forking ontobio and changing the networkx version?

I think that could work, but is it urgent enough to do right now? My thinking is that it might make sense to wait until we are actively trying to upgrade to python3.9, then check back on the status of the PR linked in the above ontobio issue and _then_ make a fork and any changes if needed.

**Comment by saramsey** [comment]
Hi @kvarforl ontobio's master branch now has a fix for the networkx versioning issue. No need to fork. But we will need to update `requirements-kg2-build.txt` for both `networkx` and `ontobio`, and then test `setup-kg2-build.sh`. Can you take care of that, @kvarforl ?  (This of course assumes that the latest version of ontobio is actually on PyPI).

**Comment by kvarforl** [comment]
Hmm, I followed these same steps:

> Just an FYI, when I create a clean python3.9 virtualenv and install `ontobio` into it
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> pip3 install ontobio
> ```
> 
> and then when I try to import `ontobio`,
> 
> ```
> python3.9
> >>> import ontobio
> ```
> 
> I get the following error, which looks to be ontobio using an ancient version of networkx (2.2 ) which is using a method that has been deprecated, and should probably be changed to `math.gcd`:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/__init__.py", line 6, in <module>
>     from .ontol_factory import OntologyFactory
>   File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/ontol_factory.py", line 7, in <module>
>     import ontobio.obograph_util as obograph_util
>   File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/obograph_util.py", line 5, in <module>
>     from ontobio.ontol import LogicalDefinition, PropertyChainAxiom
>   File "/private/tmp/venv/lib/python3.9/site-packages/ontobio/ontol.py", line 10, in <module>
>     import networkx as nx
>   File "/private/tmp/venv/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
>     import networkx.generators
>   File "/private/tmp/venv/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
>     from networkx.generators.intersection import *
>   File "/private/tmp/venv/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
>     from networkx.algorithms import bipartite
>   File "/private/tmp/venv/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
>     from networkx.algorithms.dag import *
>   File "/private/tmp/venv/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
>     from fractions import gcd
> ImportError: cannot import name 'gcd' from 'fractions' (/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/fractions.py)
> ```

and encountered the same error. My ontobio and networkx versions look like this:
```
(venv) lindsey@macbook:~/RamseyResearch$ pip3 freeze | grep ontobio
ontobio==2.4.1
(venv) lindsey@macbook:~/RamseyResearch$ pip3 freeze | grep networkx
networkx==2.2
```
So I do have the lastest version of ontobio.
<img width="601" alt="Screen Shot 2021-02-18 at 9 36 21 AM" src="https://user-images.githubusercontent.com/39020520/108397416-c9552680-71cc-11eb-9e79-51719baf498b.png">

@saramsey should I open a new issue in ontobio, reopen the old one, or let you do so?

**Comment by saramsey** [comment]
Hi @kvarforl sorry for the belated reply. So, I wonder if the latest version of ontobio (2.5.0) is not on PyPI?

**Comment by kvarforl** [comment]
ah yes, that would appear to be the case. I guess we wait?

**Comment by saramsey** [comment]
Hi @kvarforl, I think you are right. Unless there is some urgency to moving to python3.9 that I do not recall (always a possibility, LOL), it may be easiest to stick with PyPI (rather than deploying from GitHub) and wait for 2.5.0 to get pushed to PyPI (which I assume is just a matter of time).
