### ISSUE TITLE
ParseQuestion crash

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#121]
Bug report from @jaredroach:

When posing the question:
what proteins are in the pathway 'glycolysis'
via the UI, I see this crash:

[2018-05-08 22:49:26,192] ERROR in app: Exception on /devED/api/rtx/v1/translate [POST]
Traceback (most recent call last):
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 122, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 293, in wrapper
    return function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 26, in translate
    query = txltr.format_response(question)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 120, in format_response
    question, parameters, error_message, error_code = self.parse_question(input_question)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 54, in parse_question
    parameters = question.get_parameters(input_question)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/Question.py", line 305, in get_parameters
    question_tokenized_no_apos_split[ind - 1] += question_tokenized[ind]
IndexError: list index out of range

**Comment by dkoslicki** [comment]
This is a gnarly one, due to how ``nltk`` tokenizes sentences. Easy solution: don't use single quotes/apostrophes

**Comment by dkoslicki** [comment]
Setting low priority since this is easily solved by educating users. Will investigate post-hackathon about a workaround. ``nltk`` handles ``'`` in a very non-standard way, so it will take me a while to find a robust solution to this.

**Comment by dkoslicki** [comment]
Deciding to close this: can be fixed once we
1. Get continued funding
2. Decide to use a real NLP system
