### ISSUE TITLE
QueryNCBIeUtils crash

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#125]
```python
python3 Q2Solution.py 
Traceback (most recent call last):
  File "Q2Solution.py", line 294, in <module>
    main()
  File "Q2Solution.py", line 291, in main
    res = answerQ2(drug, disease, k, use_json)
  File "Q2Solution.py", line 114, in answerQ2
    RU.weight_graph_with_google_distance(g, context_node_id=disease_name, context_node_descr=disease_descr, default_value=max_gd)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 818, in weight_graph_with_google_distance
    gd_temp = NormGoogleDistance.get_ngd_for_all([source_id, target_id, context_node_id], [source_descr, target_descr, context_node_descr])
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 164, in get_ngd_for_all
    ngd = QueryNCBIeUtils.multi_normalized_google_distance(terms_combined,mesh_flags)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 394, in multi_normalized_google_distance
    counts = QueryNCBIeUtils.multi_pubmed_hits_count(search_string, n_terms=len(name_list))
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 370, in multi_pubmed_hits_count
    res_int += [int(res.json()['esearchresult']['translationstack'][a]['count'])]
TypeError: string indices must be integers
```

**Comment by dkoslicki** [comment]
@finnagin Please address this ASAP

**Comment by finnagin** [comment]
@dkoslicki do you know what was passed to `multi_pubmed_hits_count` that caused the crash?

**Comment by dkoslicki** [comment]
```python
(Osteoporosis[MeSH Terms]) AND (osteoarthritis[MeSH Terms]) AND (osteoarthritis[MeSH Terms]
```
Maybe a missing ``)``?

Other observations:
1. It seems to happen periodically
2. Take a look at lines 352 and 355 of ``QueryNCBIeUtils.py``. Note how the encoded term string is not used in the function.
3. Should I be using ``NormGoogleDistance.py`` instead of ``QueryNCBIeUtils.py``?

**Comment by finnagin** [comment]
It was the Osteoporosis[MeSH Terms] getting returned as 2 terms instead of 1. It should be fixed and not crash now.

**Comment by finnagin** [comment]
Though the fact that single mesh terms can split into 2 terms in the translationstack section is a bit concerning. e.g. the single term Osteoporosis[MeSH Terms] it is returned as 
```
{
                "term": "\"osteoporosis, postmenopausal\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "12295",
                "explode": "Y"
            },
            {
                "term": "\"osteoporosis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "51436",
                "explode": "Y"
            },
            "OR",
            "GROUP",
```
in the translation stack. If we then search just (Osteoporosis)[https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=(Osteoporosis%5BMeSH%20Terms%5D)&retmode=json] then we get a hitcount of 51436 thus, the extra term (osteoporosis, postmenopausal) is a subset of Osteoporosis but how can know if these two terms are not disjoint etc without preforming a second search?

**Comment by dkoslicki** [comment]
Ugh! I don't have any great ideas in how to handle this. Do you have a suggestion?

**Comment by finnagin** [comment]
I'm not sure. We could look for the "GROUPED" flag in the translation stack and then do individual searches if it is found. This would continue to have the 1 query per search for mesh terms when this issue does not occur but will lead to a n+1 (where n is the number of terms in a search) queries per search when this issue is encountered.

**Comment by dkoslicki** [comment]
What about the following:
at https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=(Osteoporosis%5BMeSH%20Terms%5D)&retmode=json

the ``esearchresult`` count is correct, even though the ``translationstack`` contains two counts. Would it be a problem to just capture the esearchresult count?
```
{
    "header": {
        "type": "esearch",
        "version": "0.3"
    },
    "esearchresult": {
        "count": "51436",
        "retmax": "20",
        "retstart": "0",
        "idlist": [
            "29715139",
            "29677304",
            "29642148",
            "29609586",
            "29550473",
            "29544757",
            "29536084",
            "29524406",
            "29502401",
            "29474360",
            "29465598",
            "29460653",
            "29447647",
            "29440901",
            "29440373",
            "29429226",
            "29429184",
            "29403337",
            "29390475",
            "29384970"
        ],
        "translationset": [
            {
                "from": "Osteoporosis[MeSH Terms]",
                "to": "\"osteoporosis, postmenopausal\"[MeSH Terms] OR \"osteoporosis\"[MeSH Terms]"
            }
        ],
        "translationstack": [
            {
                "term": "\"osteoporosis, postmenopausal\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "12295",
                "explode": "Y"
            },
            {
                "term": "\"osteoporosis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "51436",
                "explode": "Y"
            },
            "OR",
            "GROUP"
        ],
        "querytranslation": "\"osteoporosis, postmenopausal\"[MeSH Terms] OR \"osteoporosis\"[MeSH Terms]"
    }
}
```

**Comment by finnagin** [comment]
Yeah that is what I would use to get the correct count for the individual terms when searching again. The problem though is that always displays the count for the whole search. e.g. if we look at the original search:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=(Osteoporosis[MeSH%20Terms])%20AND%20(osteoarthritis[MeSH%20Terms])%20AND%20(osteoarthritis[MeSH%20Terms])&retmode=json
We get the following response:
```
{
    "header": {
        "type": "esearch",
        "version": "0.3"
    },
    "esearchresult": {
        "count": "779",
        "retmax": "20",
        "retstart": "0",
        "idlist": [
            "29267428",
            "29255213",
            "28631583",
            "28590379",
            "28450214",
            "28390570",
            "28365812",
            "28332125",
            "28269746",
            "28161687",
            "28065772",
            "28051119",
            "28041596",
            "28017954",
            "27941690",
            "27898996",
            "27846245",
            "27548840",
            "27515762",
            "26177878"
        ],
        "translationset": [
            {
                "from": "Osteoporosis[MeSH Terms]",
                "to": "\"osteoporosis, postmenopausal\"[MeSH Terms] OR \"osteoporosis\"[MeSH Terms]"
            },
            {
                "from": "osteoarthritis[MeSH Terms]",
                "to": "\"osteoarthritis\"[MeSH Terms]"
            }
        ],
        "translationstack": [
            {
                "term": "\"osteoporosis, postmenopausal\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "12295",
                "explode": "Y"
            },
            {
                "term": "\"osteoporosis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "51436",
                "explode": "Y"
            },
            "OR",
            "GROUP",
            {
                "term": "\"osteoarthritis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "55013",
                "explode": "Y"
            },
            "AND",
            {
                "term": "\"osteoarthritis\"[MeSH Terms]",
                "field": "MeSH Terms",
                "count": "55013",
                "explode": "Y"
            },
            "AND"
        ],
        "querytranslation": "(\"osteoporosis, postmenopausal\"[MeSH Terms] OR \"osteoporosis\"[MeSH Terms]) AND \"osteoarthritis\"[MeSH Terms] AND \"osteoarthritis\"[MeSH Terms]"
    }
}
```
To then get the correct count of 51436 (in case the split terms are not entirely subsets of each other) from the individual term (Osteoporosis[MeSH Terms]) we would then need to search that term individually and then pull the count from the esearchresult field.

**Comment by finnagin** [comment]
@dkoslicki I implemented the fix I discussed above. Since this fix only increases the number of queries sent when this term splitting error is encountered (I'm assuming this is not very often as it would have crashed everytime this happened before today) do you think we can go ahead and close this issue?

**Comment by dkoslicki** [comment]
Thanks! I'll go ahead and close (and yes, I don't think this happens too frequently).
