### ISSUE TITLE
Error in ranker for KG2 API with (curie)--(list of curies) query

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1276]
seeing this error on https://arax.ncats.io/kg2/:

```
2021-02-28T18:15:21.768605 INFO: Running experimental reranker on results
2021-02-28T18:15:21.768979 ERROR: An uncaught error occurred: unhashable type: 'list': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 644, in execute_processing_plan\n ranker.aggregate_scores_dmk(response)\n', ' File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 490, in aggregate_scores_dmk\n result = query_graph_info.assess(message)\n', ' File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/query_graph_info.py", line 81, in assess\n canonical_curies = synonymizer.get_canonical_curies(curies=[qnode.id], return_all_types=True)\n', ' File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/NodeSynonymizer/node_synonymizer.py", line 1293, in get_canonical_curies\n results[curie] = None\n', "TypeError: unhashable type: 'list'\n"]
```

for this query:
```
{
      "edges": {
        "e00": {
          "object": "n01",
          "predicate": "biolink:positively_regulates",
          "subject": "n00"
        }
      },
      "nodes": {
        "n00": {
          "id": "DOID:3312"
        },
        "n01": {
          "category": "biolink:ChemicalSubstance",
          "id": ["UMLS_STY:T192", "CHEMBL.COMPOUND:CHEMBL3707288", "CHEBI:28790"]
        }
      }
    }
```

**Comment by edeutsch** [comment]
thanks. more multiple id pains. I think this is fixed, but will wait until we have synchronized all KG2 and str->list changes

**Comment by edeutsch** [comment]
seems to work now. okay to close?

**Comment by amykglen** [comment]
yep, thanks!
