### ISSUE TITLE
Switch to GeneticsKP's TRAPI 1.0 API

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1282]
https://smart-api.info/ui/99592dd5fc3a69d3ed27692f3f278e47#/1.0.0

**Comment by amykglen** [comment]
hey @finnagin (or other `ranker` people) - so I switched `expand` over to use the GeneticsKP's TRAPI 1.0 endpoint in the `generalquerier` branch, but I noticed that they now seem to only provide one score, which they call "pValue" (has a type of `biolink:p_value`). here's an example: 
```
'GeneticsKP:EFO:0001360-biolink:condition_associated_with_gene-NCBIGene:4354': {'attributes': [{'name': 'pValue',
                 'source': None,
                 'type': 'biolink:p_value',
                 'url': None,
                 'value': 0.030088}],
```
with their old API, they provided a couple scores (MAGMA-pvalue and Genetics-quantile). I'm wondering if the ranker will need some adjustments to know what to do here?

I'm otherwise done with this issue, but figured I should probably wait to merge into `master` until we figure out the ranking.

**Comment by finnagin** [comment]
I can write a function in the ranker to handle the pValue attribute. Is this the same values but with a different name now?

**Comment by amykglen** [comment]
awesome, thanks! I'm assuming so, but haven't been in contact with anyone from that KP since Marcin left. their repo still mentions the same scores we were already aware of: https://github.com/broadinstitute/genetics-kp-dev#data-available

**Comment by amykglen** [comment]
alright, this has been merged to `master`. will test when code is next rolled out to production/test.

**Comment by amykglen** [comment]
hey @finnagin - when I try to run this GeneticsKP query on production:
```
add_qnode(name=type 2 diabetes mellitus, category=biolink:Disease, key=n0)
add_qnode(category=biolink:Gene, key=n1)
add_qedge(subject=n0, object=n1, key=e0, predicate=biolink:condition_associated_with_gene)
expand(edge_key=e0,kp=GeneticsKP)
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
I'm seeing this error in the ranker:
```
2021-03-23T04:53:08.788024 INFO: Resultify created 5395 results
2021-03-23T04:53:08.788133 DEBUG: Cleaning up the KG to remove nodes not used in the results
2021-03-23T04:53:08.807609 INFO: After cleaning, the KG contains 5396 nodes and 10803 edges
2021-03-23T04:53:08.808032 INFO: Running experimental reranker on results
2021-03-23T04:53:09.007033 INFO: Summary of available edge metrics: {'pValue': {'minimum': 5.0188e-163, 'maximum': 0.999502289468445}, 'normalized_google_distance': {'minimum': 0.2421922889071665, 'maximum': 1.1181483681900244}}
2021-03-23T04:53:09.007951 ERROR: An uncaught error occurred: 'NoneType' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 653, in execute_processing_plan\n ranker.aggregate_scores_dmk(response)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 551, in aggregate_scores_dmk\n edge_attributes = {x.name:x.value for x in edge.attributes}\n', "TypeError: 'NoneType' object is not iterable\n"]
```

**Comment by finnagin** [comment]
@amykglen Huh, I'll try to take a look at this after I get my local copy of master working again. After the recent merge a lot of things are failing on my end. I'll also go ahead and add this as a test to test_ARAX_workflows after I fix it.

**Comment by finnagin** [comment]
This looks to now be fixed and working on [arax.ncats.io](https://arax.ncats.io/test/?r=7041) closing now
