### ISSUE TITLE
'all_categories' error with DTD Expand query

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1348]
just noticed that this DSL produces an error on production:
```
add_qnode(key=n0, id=DRUGBANK:DB00394, category=biolink:Drug)
add_qnode(key=n1, category=biolink:Disease)
add_qedge(key=e0, subject=n1, object=n0, predicate=biolink:treated_by)
expand(kp=DTD)
resultify()
```
`2021-04-07T18:47:31.083432 ERROR: An uncaught error occurred: 'all_categories': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 592, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 350, in apply\n answer_kg = self._expand_edge(one_hop_qg, kp_to_use, continue_if_no_results, use_synonyms, mode, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 445, in _expand_edge\n answer_kg = kp_querier.answer_one_hop_query(edge_qg)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/DTD_querier.py", line 95, in answer_one_hop_query\n final_kg = self._answer_query_using_DTD_database(query_graph, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/DTD_querier.py", line 370, in _answer_query_using_DTD_database\n all_types = [item.replace(\'biolink:\',\'\').replace(\'_\',\'\').lower() for item in list(normalizer_result[target_pass_nodes[0]][\'all_categories\'].keys())]\n', "KeyError: 'all_categories'\n"]`

(I'm pretty sure that is a kind of query DTD should be able to answer?)

**Comment by amykglen** [comment]
looks good on production!
