### ISSUE TITLE
DTD error when category not specified (or specified)

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1352]
For this DSL query:
```
add_qnode(name=Neutropenia, key=n0)
add_qnode(key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(edge_key=e0,kp=DTD)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
I get the following error:
```
2021-04-07T22:41:54.548013 DEBUG: Query graph for this Expand() call is: {'nodes': {'n0': {'id': 'MONDO:0001475', 'category': [], 'is_set': False, 'option_group_id': None}, 'n1': {'id': None, 'category': [], 'is_set': False, 'option_group_id': None}}, 'edges': {'e0': {'predicate': [], 'relation': None, 'subject': 'n0', 'object': 'n1', 'exclude': False, 'option_group_id': None}}}
2021-04-07T22:41:54.548129 DEBUG: Modified QG for this qedge is (n0:[] MONDO:0001475)--(n1:[])
2021-04-07T22:41:54.548164 INFO: Expanding qedge e0 using DTD
2021-04-07T22:41:54.548896 DEBUG: Processing query results for edge e0 by using DTD database
2021-04-07T22:41:54.552327 ERROR: An uncaught error occurred: 'NoneType' object has no attribute 'replace': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 592, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 350, in apply\n answer_kg = self._expand_edge(one_hop_qg, kp_to_use, continue_if_no_results, use_synonyms, mode, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 445, in _expand_edge\n answer_kg = kp_querier.answer_one_hop_query(edge_qg)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/DTD_querier.py", line 95, in answer_one_hop_query\n final_kg = self._answer_query_using_DTD_database(query_graph, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/DTD_querier.py", line 227, in _answer_query_using_DTD_database\n category = target_qnode.category.replace(\'biolink:\',\'\').replace(\'_\',\'\').lower()\n', "AttributeError: 'NoneType' object has no attribute 'replace'\n"]
```
And actually, I get a similar error when I do specify the category:
```
add_qnode(name=Neutropenia, key=n0)
add_qnode(key=n1,category=biolink:Drug)
add_qedge(key=e0,subject=n0,object=n1)
expand(edge_key=e0,kp=DTD)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```

**Comment by chunyuma** [comment]
Hi @dkoslicki, thanks for reporting this error. I think the error is because in `expand`, if you don't set `DTD_threshold` and `DTD_slow_mode=True` then it will use the default value 0.8 and search the probability in DTD database instead of directly calling DTD model. Based on our previous discussion, if you search DTD database, it will check the node type.

In both of your cases above, you didn't set a category for `n0` and I think the `add_qnode` will not automatically assign a category. So that's why the category of `n0` is `NoneType`. 

I think there are two ways that might avoid this error:

1. assign a category to `n0`
2. set `DTD_threshold` below 0.8 or set `DTD_slow_mode=True`

But I would also add a `try ... except` to allow this error.

**Comment by dkoslicki** [comment]
Interesting! I thought the category would be inferred from the synonymizer when querying by name. Unfortunately though, it appears that assigning a category to n0 doesn't help:
```
add_qnode(name=Neutropenia, key=n0, category=biolink:Disease)
add_qnode(key=n1,category=biolink:Drug)
add_qedge(key=e0,subject=n0,object=n1)
expand(edge_key=e0,kp=DTD)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
gives the same error.

**Comment by chunyuma** [comment]
Hi @dkoslicki, I think if you assigned a category to n0, it should not give the same error but would say `[NoResults] No paths were found in DTD satisfying qedge e0`. There are two reasons for this: 1) since we're now still using the refreshed DTD probability database, some of curies might be mapped to the old database; 2) no probability >= 0.8 for your query because you're using the default threshold 0.8 for researching DTD probability database.

I just pushed a new commit which adds `try ... except` to avoid the above error. 

If you run this query again:
```
add_qnode(name=Neutropenia, key=n0, category=biolink:Disease)
add_qnode(key=n1,category=biolink:Drug)
add_qedge(key=e0,subject=n0,object=n1)
expand(edge_key=e0,kp=DTD)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
you might still get the error saying no paths were found. Please add `DTD_slow_mode=True` in expand to call DTD model to avoid this error.
```
add_qnode(name=Neutropenia, key=n0, category=biolink:Disease)
add_qnode(key=n1,category=biolink:Drug)
add_qedge(key=e0,subject=n0,object=n1)
expand(edge_key=e0, kp=DTD, DTD_slow_mode=True)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
BTW, please update your local `configv2.json` by downloading arax.ncats.io:/data/orangeboard/databases/KG2.5.2/configv2.json

**Comment by dkoslicki** [comment]
Ah, I see. I can confirm the slow made makes it work, and the category issue now makes sense to me. I see the `try...except` should fix the NoneType error so marking to check in next release

**Comment by dkoslicki** [comment]
Confirmed working as intended at `/test`
