### ISSUE TITLE
Problem Processing New Version of efo.owl

### ISSUE THREAD

**Issue by ericawood** [RTXteam/RTX#1381]
In the old version of efo.owl, this node existed:
```
     "RO:participates_in": {
         "category": "biolink:InformationContentEntity",
         "category_label": "information_content_entity",
         "creation_date": null,
         "deprecated": false,
         "description": "Participates in is a primitive instance-level relation between a continuant and a process in which it participates. For example a scanner participates in a sc       anning process at some specific time.",
         "full_name": null,
         "has_biological_sequence": null,
         "id": "RO:participates_in",
         "iri": "http://purl.obolibrary.org/obo/RO_participates_in",
         "name": "participates_in",
         "ontology node ids": [
             "http://www.obofoundry.org/ro/ro.owl#participates_in"
         ],
         "provided_by": "EFO:efo.owl",
         "publications": [],
         "replaced_by": null,
         "synonym": [],
         "update_date": "3200",
         "xrefs": []
     },
```
That node doesn't exist in the new version of efo.owl, that node DOESN'T exist, so when this edge reaches
https://github.com/RTXteam/RTX/blob/525c362b0a9fb4dcf82ad8f025a0e3fd0936bbd5/code/kg2/multi_ont_to_json_kg.py#L1009-L1017
there is no pred_node and the code fails. Other edges that have the predicate label of participates_in have the relation curie (predicate_curie in the code) of RO:0000056, which has it's node here:
```
     "RO:0000056": {
         "category": "biolink:InformationContentEntity",
         "category_label": "information_content_entity",
         "creation_date": null,
         "deprecated": false,
         "description": "Participates in is a primitive instance-level relation between a continuant and a process in which it participates. For example a scanner participates in a sc       anning process at some specific time.",
         "full_name": null,
         "has_biological_sequence": null,
         "id": "RO:0000056",
         "iri": "http://purl.obolibrary.org/obo/RO_0000056",
         "name": "participates_in",
         "ontology node ids": [
             "RO:0000056"
         ],
         "provided_by": "EFO:efo.owl",
         "publications": [],
         "replaced_by": null,
         "synonym": [],
         "update_date": "3290",
         "xrefs": []
     },
```
This node is not present in the old version of EFO. It seems like, in their update, they forgot to update the whole thing.The problem edge doesn't exist in the old version.
Here's the output for the problem edge in the new version (which doesn't work). Note the predicate curie matches a node from the old version, but not the new version.
```
 Subject Curie Id: EFO:0005769
 Object Curie Id: GO:0055074
 Predicate Curie: RO:participates_in
 Ontology Curie Id: EFO:efo.owl
 Predicate Label: None
 Traceback (most recent call last):
   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1266, in <module>
     save_pickle)
   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 169, in make_kg2
     map_of_node_ontology_ids_to_curie_ids)
   File "/home/ubuntu/kg2-code/multi_ont_to_json_kg.py", line 1054, in get_rels_dict
     assert predicate_label is not None
 AssertionError
```
However, please note the change between the two versions of a SIMILAR edge:
Old -
```
  Subject Curie Id: EFO:1001078
  Object Curie Id: GO:0006954
  Predicate Curie: RO:participates_in
  Ontology Curie Id: EFO:efo.owl
  Predicate Label: participates_in
```
New -
```
  Subject Curie Id: EFO:1001078
  Object Curie Id: GO:0006954
  Predicate Curie: RO:0000056
  Ontology Curie Id: EFO:efo.owl
  Predicate Label: participates_in
```
This further suggests that this was an unintended side effect of their update.

This is a big issue because it is preventing the build of KG2.6.0 from continuing.

**Comment by saramsey** [comment]
Hi @ericawood thanks for bringing this to my attention. Excellent bug report. Can you please remind me, the KG2.6.0 build is being done with `multi_ont_to_json_kg.py` code from what branch?

**Comment by kvarforl** [comment]
the build is being done from the Ontobio507TempFix branch! thank you @saramsey @ericawood  for all of your help :)

**Comment by saramsey** [comment]
In what EC2 instance is the build being done?

**Comment by kvarforl** [comment]
Kg2lindsey :)

**Comment by saramsey** [comment]
Thank you

**Comment by saramsey** [comment]
OK, I have reproduced the problem on my MBP:
```
(venv) sramsey-laptop:kg2 sramsey$ python3 -u multi_ont_to_json_kg.py  --test curies-to-categories.yaml  curies-to-urls-map.yaml ont-load-inventory-issue1381.yaml issue1381.json node_datatype_properties.json
https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl
Reading ontology file: biolink-model.owl.ttl; size: 423.33 KiB
Reading ontology JSON file: biolink-model.owl.json; size: 747.21 KiB
file: biolink-model.owl.ttl; last modified: 2021-04-18 04:50:29 UTC
http://www.ebi.ac.uk/efo/efo.owl
Reading ontology file: efo.owl; size: 158717.22 KiB
Reading ontology JSON file: efo.json; size: 54633.61 KiB
file: efo.owl; last modified: 2021-04-18 04:50:18 UTC
Calling make_nodes_dict_from_ontologies_list
processing ontology: biolink_download_source:biolink-model.owl.ttl
processing ontology: EFO:efo.owl
[http://www.ebi.ac.uk/efo/efo.owl] unexpected None category depth for category RNA product: OBI:0000869
[http://www.ebi.ac.uk/efo/efo.owl] unexpected None category depth for category RNA product: OBI:0000869
Calling make_map_of_node_ontology_ids_to_curie_ids
Calling get_rels_dict
Traceback (most recent call last):
  File "multi_ont_to_json_kg.py", line 1259, in <module>
    save_pickle)
  File "multi_ont_to_json_kg.py", line 169, in make_kg2
    map_of_node_ontology_ids_to_curie_ids)
  File "multi_ont_to_json_kg.py", line 1047, in get_rels_dict
    assert predicate_label is not None
AssertionError
```

**Comment by saramsey** [comment]
Just checking in if there is anything else I should do, for this issue?  if not, I will remove the `sar-look` label

**Comment by kvarforl** [comment]
Nope all good! I restarted the build earlier this evening. Thanks for your help!
