### ISSUE TITLE
Error in filter

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1389]
In trying to address #1385 by switching KG1 to KG2 [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/test/test_ARAX_workflows.py#L122), I discovered that `filter` throws an error:
```
add_qnode(name=DOID:14330, key=n00)
add_qnode(category=biolink:Protein, is_set=true, key=n01)
add_qnode(category=biolink:ChemicalSubstance, key=n02)
add_qedge(subject=n00, object=n01, key=e00)
add_qedge(subject=n01, object=n02, key=e01, predicate=biolink:physically_interacts_with)
expand(edge_key=[e00,e01], kp=ARAX/KG2)
overlay(action=compute_jaccard, start_node_key=n00, intermediate_node_key=n01, end_node_key=n02, virtual_relation_label=J1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=jaccard_index, direction=below, threshold=.2, remove_connected_nodes=t, qnode_key=n02)
filter_kg(action=remove_edges_by_property, edge_property=provided_by, property_value=Pharos)
overlay(action=predict_drug_treats_disease, subject_qnode_key=n02, object_qnode_key=n00, virtual_relation_label=P1)
resultify(ignore_edge_direction=true)
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```
```
2021-04-20T17:05:43.281568 INFO: Processing action 'filter_kg' with parameters {'action': 'remove_edges_by_property', 'edge_property': 'provided_by', 'property_value': 'Pharos'}
2021-04-20T17:05:43.285883 ERROR: An uncaught error occurred: unhashable type: 'list': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 604, in execute_processing_plan\n filter_kg.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_filter_kg.py", line 426, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_filter_kg.py", line 524, in __remove_edges_by_property\n known_values.add(attribute.value)\n', "TypeError: unhashable type: 'list'\n"]
```

**Comment by finnagin** [comment]
I've fixed this now but something I noticed is that the portion of this query before the `remove_edges_by_property` line no longer seems to return Pharos edges in KG2 so not sure if that line makes sense here anymore.

**Comment by dkoslicki** [comment]
Interesting; do you or other KG2 peeps (@kvarforl @ericawood) know if Pharos is no longer in KG2? We might need to update this test if so

**Comment by ericawood** [comment]
For `KG2.6.0`, it is likely that Pharos is no longer in KG2 due to the removal of the KG1 import. Prior to this build, I am unaware of why Pharos edges would be gone.

**Comment by dkoslicki** [comment]
Confirmed that the DSL above doesn’t throw an error, closing!
