### ISSUE TITLE
ARAX's last moments

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1397]
ARAX died overnight. It was apparently still chewing on the forever-query I mentioned at yesterday's meeting. Last moments:

```
2021-04-22T06:26:34.809180 DEBUG: [] Predicting probability that ENPROSTIL treats neutropenia
2021-04-22T06:26:53.692098 DEBUG: [] Predicting probability that SID26757216 treats Adams-Oliver syndrome 3
2021-04-22T06:26:57.532750 DEBUG: [] Predicting probability that IMATINIB treats syndromic X-linked intellectual disability Snyder type
2021-04-22T06:27:08.201506 DEBUG: [] Predicting probability that 2164U90 treats neutropenia
Process ForkPoolWorker-721:
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-722:
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-723:
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-724:
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/queues.py", line 364, in put
    self._writer.send_bytes(obj)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

```

**Comment by dkoslicki** [comment]
Looks like that was a runaway query I had tried. It may have been something like I forgot to specify a curie, so it was doing _all_ diseases. Is there some way to terminate a running query from the UI? Sometimes closing the tab seems to work, sometimes not (hard to tell).

**Comment by edeutsch** [comment]
As far as I know, there is no way to explicitly terminate a running query via the UI or via any mechanism except restarting the flask server. What I don't know is if the client (Chrome) closes the connection to the server whether the server can/will terminate the thread that was servicing it. anyone know what happens in such cases?

**Comment by dkoslicki** [comment]
I'll close this one and be sure to run "ambitious" queries on `test` or `beta`, unless anyone has an objection
