### ISSUE TITLE
Resultify uncaught error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1448]
For the query:
```
add_qnode(key=n0,id=DRUGBANK:DB01255,category=biolink:ChemicalSubstance)
add_qnode(key=n1,id=HGNC:6284,category=biolink:Gene)
add_qedge(key=e0,subject=n0,object=n1)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```
I get the following error in resultify:
```
ERROR: An uncaught error occurred: 'NoneType' object has no attribute 'nodes': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 598, in execute_processing_plan\n resultifier.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 121, in apply\n self._clean_up_kg()\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 263, in _clean_up_kg\n cleaned_kg = KnowledgeGraph(nodes={node_key: node for node_key, node in kg.nodes.items() if node_key in node_keys_used_in_results},\n', "AttributeError: 'NoneType' object has no attribute 'nodes'\n"]
```
Probably due to empty results

**Comment by dkoslicki** [comment]
Thanks @amykglen , always happy to provide rubbish DSL to test error handling :)

**Comment by amykglen** [comment]
ok, the equivalent TRAPI 1.1 query now returns the error `ERROR: No message.knowledge_graph exists for resultify to create results from` on `arax.ncats.io/NewFmt/`
```
add_qnode(key=n0,ids=DRUGBANK:DB01255,categories=biolink:ChemicalSubstance)
add_qnode(key=n1,ids=HGNC:6284,categories=biolink:Gene)
add_qedge(key=e0,subject=n0,object=n1)
resultify(ignore_edge_direction=true)
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```
good to close?
