### ISSUE TITLE
ModuleNotFoundError: No module named 'openapi_server.models.one_ofobjectobject'

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1456]
I'm running DSL query within `NewFmt` but got an error:

```
Traceback (most recent call last):
  File "test_fisher_exact.py", line 9, in <module>
    from ARAX_query import ARAXQuery
  File "/data/cqm5886/work/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_query.py", line 20, in <module>
    from query_graph_info import QueryGraphInfo
  File "/data/cqm5886/work/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/query_graph_info.py", line 16, in <module>
    from openapi_server.models.query_graph import QueryGraph
  File "/data/cqm5886/work/RTX/code/ARAX/ARAXQuery/../../UI/OpenAPI/python-flask-server/openapi_server/models/__init__.py", line 21, in <module>
    from openapi_server.models.operation_fill import OperationFill
  File "/data/cqm5886/work/RTX/code/ARAX/ARAXQuery/../../UI/OpenAPI/python-flask-server/openapi_server/models/operation_fill.py", line 9, in <module>
    from openapi_server.models.one_ofobjectobject import OneOfobjectobject
ModuleNotFoundError: No module named 'openapi_server.models.one_ofobjectobject'
```

It seems like we don't have `one_ofobjectobject` under `RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/models/
 `

**Comment by chunyuma** [comment]
Yes, it seems to work now. Thanks @edeutsch.
