### ISSUE TITLE
overlay_utilities crashes if no qnode_keys?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1462]
I'm trying to run the following request:
```
request = { "message": {}, "operations": { 
          "message_uris": [ "https://arax.ncats.io/api/arax/v1.1/response/9852" ],
          "actions": [
            "overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n1)",
            "resultify()",
            ] } }
```
See $RTX/code/UI/ClientExamples/Python/ExampleQuery_Operations_1.py

It crashes with:
```
2021-05-13T15:53:45.544329 ERROR: [UncaughtARAXiError] An uncaught error occurred: 'Node' object has no attribute 'qnode_keys': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 501, in execute_processing_plan\n    overlay.apply(response, action[\'parameters\'])\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 515, in apply\n    \'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 586, in __compute_ngd\n    response = NGD.compute_ngd()\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/compute_ngd.py", line 77, in compute_ngd\n    node_pairs_to_evaluate = ou.get_node_pairs_to_overlay(subject_qnode_key, object_qnode_key, qg, kg, self.response)\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/ARAX/ARAXQuery/Overlay/overlay_utilities.py", line 27, in get_node_pairs_to_overlay\n    kg_nodes_by_qg_id = get_node_ids_by_qg_id(knowledge_graph)\n', '  File "/mnt/data/orangeboard/NewFmt/RTX/code/ARAX/ARAXQuery/Overlay/overlay_utilities.py", line 68, in get_node_ids_by_qg_id\n    for qnode_key in node.qnode_keys:\n', "AttributeError: 'Node' object has no attribute 'qnode_keys'\n"]
```

I'm guessing that the issue is that after loading previous query result 9852, attempting to overlay NGD fails because qnode_keys is not present because it is not part of the TRAPI schema. It seems like we need to be able to do without or recompute them if we need them.

Any ideas on how to address this?

**Comment by amykglen** [comment]
ah, yeah. I think there's a [method](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_resultify.py#L127-L168) in resultify that does what you're thinking of?
```
    resultifier = ARAXResultify()
    resultifier.recompute_qg_keys(response)
```

**Comment by edeutsch** [comment]
ah, this is perfect. added as suggested and it solves the problem.
awesome, thank you!
