### ISSUE TITLE
If query graph interpreter can’t interpret something, just run as is?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1479]
For the following query:
```
{
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
```
We get the message `ERROR: [QueryGraphInterpreterUnsupportedGraph]    QueryGraphInterpreter cannot interpret this QueryGraph`.
However, the equivalent DSL runs without error:
```
add_qnode(key=n0,categories=biolink:Gene, is_set=True)
add_qnode(key=n1,ids=CHEBI:45783,categories=biolink:ChemicalSubstance)
add_qnode(key=n2,ids=MONDO:0005301,categories=biolink:Disease)
add_qedge(key=e01,subject=n0,object=n1,predicates=biolink:related_to)
add_qedge(key=e02,subject=n0,object=n2,predicates=biolink:related_to)
add_qnode(key=n3,categories=biolink:ChemicalSubstance)
add_qedge(key=e03,subject=n0,object=n3,predicates=biolink:related_to)
expand()
resultify()
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```

**Comment by edeutsch** [comment]
okay, I added some code to just run a generic snippet of DSL as you show above in the scenario where no template matches. This could cause the server to bog down if too complex a query graph is submitted.

This seems to work in /devED but the query is crashing for another reason:
```
2021-05-21T21:04:01.784950 ERROR: An uncaught error occurred: 'ARAX/KG2': ['multiprocessing.pool.RemoteTraceback: \n"""\nTraceback (most recent call last):\n File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker\n result = (True, func(*args, **kwds))\n File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar\n return list(itertools.starmap(args[0], args[1]))\n File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 506, in _expand_edge\n log.data["parameters"] = self._set_and_validate_parameters(kp_to_use, input_parameters, log)\n File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 1049, in _set_and_validate_parameters\n for kp_parameter_name, info_dict in self.kp_command_definitions[kp]["parameters"].items():\nKeyError: \'ARAX/KG2\'\n"""\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 524, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 422, in apply\n for kp_to_use in kps_to_query])\n', ' File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap\n return self._map_async(func, iterable, starmapstar, chunksize).get()\n', ' File "/mnt/data/python/Python-3.7.3/lib/python3.7/multiprocessing/pool.py", line 657, in get\n raise self._value\n', "KeyError: 'ARAX/KG2'\n"]
```

Looks like an issue in Expander?

**Comment by dkoslicki** [comment]
Probably due to the name change in #1475 : ARAX/KG2 -> RTX-KG2

**Comment by edeutsch** [comment]
okay the intermediate problem is solved, and the fix for the original issue has been deployed.

**Comment by edeutsch** [comment]
okay to close?

**Comment by dkoslicki** [comment]
Yup! Not throwing that error, but disappointingly looks like no paths were found. Oh well
