### ISSUE TITLE
FET sqlite operational error

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1623]
seeing an uncaught error on production during the FET step of this DSL:
```
add_qnode(ids=UniProtKB:P00491, categories=biolink:SmallMolecule, key=n0)
add_qnode(categories=biolink:NamedThing, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand()
overlay(action=fisher_exact_test, virtual_relation_label=FETn0-->n1, subject_qnode_key=n0, object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
`   2021-08-25T00:42:49.745825 ERROR: [UncaughtARAXiError]    An uncaught error occurred: near "3": syntax error: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 533, in execute_processing_plan\n overlay.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 531, in apply\n \'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 944, in __fisher_exact_test\n response = FTEST.fisher_exact_test()\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 303, in fisher_exact_test\n result = self.query_size_of_adjacent_nodes(node_curie=list(object_node_dict.keys()), source_type=object_node_category[0], adjacent_type=subject_node_category[0], kp=\'RTX-KG2\', rel_type=None)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 454, in query_size_of_adjacent_nodes\n cursor.execute(sql_query)\n', 'sqlite3.OperationalError: near "3": syntax error\n']`

**Comment by chunyuma** [comment]
Hi @amykglen, it seems like this error is from those special curie ids like `ttd.target:2'3'-Dideoxyinosine`. The quotation mark causes the error when we query it in `kg2c_v1.0_KG2.7.1.sqlite` database. So to prevent this error, we just can only skip this kind of curie ids. Right now, this bug is fixed.

**Comment by amykglen** [comment]
ah, I see. I think you can just escape the quotes in your SQL query rather than skipping those nodes - see: https://github.com/RTXteam/RTX/blob/daddb1f182eb758d66360afe59b5a8741a5064ed/code/ARAX/ARAXQuery/ARAX_decorator.py#L44

**Comment by amykglen** [comment]
just tried this on production, but now I'm seeing a different error for the same query?

`
2021-08-29T00:11:36.191265 ERROR: [UncaughtARAXiError]    An uncaught error occurred: "ttd.target:2'3'-Dideoxyinosine": ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 533, in execute_processing_plan\n overlay.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 531, in apply\n \'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 944, in __fisher_exact_test\n response = FTEST.fisher_exact_test()\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 304, in fisher_exact_test\n result = self.query_size_of_adjacent_nodes(node_curie=list(object_node_dict.keys()), source_type=object_node_category[0], adjacent_type=subject_node_category[0], kp=\'RTX-KG2\', rel_type=None)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 464, in query_size_of_adjacent_nodes\n res_dict = {node:neighbor_counts_dict[mapping[node]].get(adjacent_type) for node in mapping if neighbor_counts_dict[mapping[node]].get(adjacent_type) is not None}\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 464, in <dictcomp>\n res_dict = {node:neighbor_counts_dict[mapping[node]].get(adjacent_type) for node in mapping if neighbor_counts_dict[mapping[node]].get(adjacent_type) is not None}\n', 'KeyError: "ttd.target:2\'3\'-Dideoxyinosine"\n']
`

**Comment by chunyuma** [comment]
It's weird @amykglen. I couldn't get this error when I ran this query locally. But based on the error message that you reported, I added a few lines to avoid this error. Hope it works at this time.

**Comment by amykglen** [comment]
no errors on production now! https://arax.ncats.io/?r=23953
