### ISSUE TITLE
FET error with previously working Translator mini-hackathon query

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1643]
for this query (from https://github.com/NCATSTranslator/minihackathons/issues/231):
```
{
  "edges": {
    "e00": {
      "object": "n01",
      "subject": "n00"
    },
    "e01": {
      "object": "n02",
      "subject": "n01"
    },
    "e02": {
      "object": "n03",
      "subject": "n02"
    },
    "e03": {
      "object": "n04",
      "subject": "n03"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "ids": [
        "DRUGBANK:DB00150"
      ],
      "is_set": false,
      "name": "DRUGBANK:DB00150"
    },
    "n01": {
      "categories": [
        "biolink:Protein"
      ],
      "is_set": false,
      "name": "biolink:Proteins?"
    },
    "n02": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "is_set": false,
      "name": "biolink:MolecularActivitys?"
    },
    "n03": {
      "categories": [
        "biolink:MolecularActivity"
      ],
      "is_set": false,
      "name": "biolink:MolecularActivitys?"
    },
    "n04": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "ids": [
        "KEGG.COMPOUND:C02700"
      ],
      "is_set": false,
      "name": "KEGG.COMPOUND:C02700"
    }
  }
}
```
the QueryGraphInterpreter apparently chooses to Overlay FET, and that step produces an error:
```
2021-09-11T00:49:59.926234 INFO: After Expand, the KG has 20 nodes and 144 edges (e00: 118, e01: 18, e02: 4, e03: 4, n00: 2, n01: 12, n02: 1, n03: 5, n04: 1)
2021-09-11T00:49:59.971291 INFO: Processing action 'overlay' with parameters {'action': 'fisher_exact_test', 'subject_qnode_key': 'n01', 'virtual_relation_label': 'F1', 'object_qnode_key': 'n02', 'filter_type': 'top_n', 'value': '20'}
2021-09-11T00:49:59.982073 DEBUG: Applying Overlay to Message with parameters {'action': 'fisher_exact_test', 'subject_qnode_key': 'n01', 'virtual_relation_label': 'F1', 'object_qnode_key': 'n02', 'filter_type': 'top_n', 'value': '20'}
2021-09-11T00:49:59.982258 INFO: Performing Fisher's Exact Test to add p-value to edge attribute of virtual edge
2021-09-11T00:50:01.036594 ERROR: Traceback (most recent call last): File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 184, in fisher_exact_test temp_kp = [re.sub("infores:", "", x.value) for x in self.message.knowledge_graph.edges[edge_key].attributes if x.attribute_type_id == 'biolink:aggregator_knowledge_source' or x.attribute_type_id == 'biolink:knowledge_source'] File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Overlay/fisher_exact_test.py", line 184, in <listcomp> temp_kp = [re.sub("infores:", "", x.value) for x in self.message.knowledge_graph.edges[edge_key].attributes if x.attribute_type_id == 'biolink:aggregator_knowledge_source' or x.attribute_type_id == 'biolink:knowledge_source'] File "/mnt/data/python/Python-3.7.3/lib/python3.7/re.py", line 192, in sub return _compile(pattern, flags).sub(repl, string, count) TypeError: expected string or bytes-like object
2021-09-11T00:50:01.394160 ERROR: Something went wrong with retrieving edges in message KG
```
(was not able to find a simpler query that reproduces this issue in the couple variations I tried.)

**Comment by amykglen** [comment]
I think this is due to an issue with attribute decoration caused by my changes in #1622 - working on a fix

**Comment by amykglen** [comment]
ok, well there was an issue with node decoration related to #1622 (now fixed), but that was apparently unrelated to this problem (it's still happening).

assigning back to @chunyuma since I'm not sure what the problem is.

**Comment by chunyuma** [comment]
Hi @amykglen, it seems like this is due to the inconsistent format of `edge` attributes. Here is an example:

```
{'attribute_source': None,
 'attribute_type_id': 'biolink:aggregator_knowledge_source',
 'attributes': None,
 'description': None,
 'original_attribute_name': None,
 'value': ['BioThings DGIdb API'],
 'value_type_id': 'biolink:InformationResource',
 'value_url': None}

```

I found that the `value` attribute of most other `biolink:aggregator_knowledge_source` is a string rather than a list. Do you think this is something wrong appeared somewhere in expand?

**Comment by amykglen** [comment]
@chunyuma - ah, I see. when Expand creates such attributes, the value is always a string. but in this instance, this attribute was created by an external KP, and we don't have control over the attributes that other KPs tack onto edges.

technically `attribute.value` is allowed to be any data type, so I'd suggest making it so that your code checks whether the `attribute.value` is a string before inspecting it.

**Comment by chunyuma** [comment]
Ah, I see! Thanks @amykglen. I fixed this bug now. I assume that `attribute.value` should be a string or a list so for other data type, it might still report an error. But I think it should make sense to have this assumption, right?
