### ISSUE TITLE
stack trace from Expand when KP times out?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1645]
This has been happening for a while and perhaps not detrimental to the overall function of Expand, but while looking through the logs I sometimes see a stack trace from Expand? I think it might be happening when a KP times out?

This sometimes (but perhaps not always) happens while running our Example JSON:

```
2021-09-12T21:13:18.190845 WARNING: [] An uncaught error was thrown while trying to Expand using MolePro, so I couldn't get answers from that KP. Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 387, in _expand_edge
    answer_kg = kp_querier.answer_one_hop_query(edge_qg)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 62, in answer_one_hop_query
    qg_copy = eu.make_qg_use_supported_prefixes(self.kp_selector, qg_copy, self.kp_name, log)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/expand_utilities.py", line 269, in make_qg_use_supported_prefixes
    kp_name)
  File "/mnt/data/orangeboard/devED/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 96, in convert_curies_to_supported_prefixes
    supported_prefixes = {prefix.upper() for category in categories
TypeError: 'NoneType' object is not iterable

2021-09-12T21:13:18.359695 WARNING: [] An uncaught error was thrown while trying to Expand using BTE, so I couldn't get answers from that KP. Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 387, in _expand_edge
    answer_kg = kp_querier.answer_one_hop_query(edge_qg)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 62, in answer_one_hop_query
    qg_copy = eu.make_qg_use_supported_prefixes(self.kp_selector, qg_copy, self.kp_name, log)
  File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/Expand/expand_utilities.py", line 269, in make_qg_use_supported_prefixes
    kp_name)
  File "/mnt/data/orangeboard/devED/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 96, in convert_curies_to_supported_prefixes
    supported_prefixes = {prefix.upper() for category in categories
TypeError: 'NoneType' object is not iterable

```

perhaps not a major problem, but perhaps an easy fix to reduce stack traceyness of the logs?

**Comment by amykglen** [comment]
ah, yes, thanks. just pushed a fix to `master`.

**Comment by edeutsch** [comment]
appears fixed in production, thanks, closing
