### ISSUE TITLE
KG2 endpoint errors

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1652]
Working on a query monitoring system. Partially working. It reveals that the KG2 endpoint is failing somewhat often. Stack trace is:
```
2021-09-15T02:10:27.644346 DEBUG: [] Expanding qedge e01
2021-09-15T02:10:27.646649 DEBUG: [] Modified QG for this qedge is (n01:['biolink:Gene', 'biolink:Protein'] [1986 curies])-['biolink:related_to']-(n02:['biolink:MolecularActivity'])
2021-09-15T02:10:27.646707 DEBUG: [] For e01, pre-prune threshold is 500, post-prune threshold is 10000
2021-09-15T02:10:27.646891 ERROR: [UncaughtARAXiError] An uncaught error occurred: 'n01': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 580, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 206, in apply\n    overarching_kg = self._prune_kg(qnode_key, pre_prune_threshold, overarching_kg, query_graph, log)\n', '  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 708, in _prune_kg\n    log.info(f"Pruning back {qnode_key_to_prune} nodes because there are more than "\n', "KeyError: 'n01'\n"]
```

**Comment by edeutsch** [comment]
Here's a query that generates the error:
https://arax.ncats.io/devED/api/arax/v1.2/status?id=782
It doesn't have an n01. Only n0 and n3

**Comment by amykglen** [comment]
ah, thanks - believe this is fixed in `master`.

**Comment by edeutsch** [comment]
super! `master` is now deployed everywhere

**Comment by amykglen** [comment]
great! confirmed the query you shared seems to work now on both /kg2 and production (arax version is here: https://arax.ncats.io/?r=25205)

**Comment by edeutsch** [comment]
brill, thanks! closing.
