### ISSUE TITLE
Pytest failing during Overlay FET step

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1668]
this pytest seems to be failing in `master` during the Overlay FET step:
```
FAILED test_ARAX_workflows.py::test_ranker_float_error_ex1 - AssertionError: assert 'ERROR' == 'OK'
```
```
  - 2021-09-21T21:04:25.549378 DEBUG: [] 1 subject node with qnode key n0 and node type biolink:ChemicalEntity was found in message KG and used to calculate Fisher's Exact Test
  - 2021-09-21T21:04:25.549387 DEBUG: [] 998 object nodes with qnode key n1 and node type biolink:DiseaseOrPhenotypicFeature was found in message KG and used to calculate Fisher's Exact Test
  - 2021-09-21T21:04:25.549500 DEBUG: [] RTX-KG2 was used to calculate total object nodes in Fisher's Exact Test
  - 2021-09-21T21:04:25.648936 ERROR: [UncaughtARAXiError] An uncaught error occurred: 'UMLS:C0495252': ['Traceback (most recent call last):\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 608, in execute_processing_plan\n    overlay.apply(response, action[\'parameters\'])\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_overlay.py", line 531, in apply\n    \'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/ARAX_overlay.py", line 944, in __fisher_exact_test\n    response = FTEST.fisher_exact_test()\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/Overlay/fisher_exact_test.py", line 310, in fisher_exact_test\n    result = self.query_size_of_adjacent_nodes(node_curie=list(object_node_dict.keys()), source_type=object_node_category[0], adjacent_type=subject_node_category[0], kp=\'RTX-KG2\', rel_type=None)\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/Overlay/fisher_exact_test.py", line 473, in query_size_of_adjacent_nodes\n    res_dict = {node:neighbor_counts_dict[mapping[node]].get(adjacent_type) for node in mapping if neighbor_counts_dict[mapping[node]].get(adjacent_type) is not None}\n', '  File "/Users/amyglen/Projects/RTX/code/ARAX/test/../ARAXQuery/Overlay/fisher_exact_test.py", line 473, in <dictcomp>\n    res_dict = {node:neighbor_counts_dict[mapping[node]].get(adjacent_type) for node in mapping if neighbor_counts_dict[mapping[node]].get(adjacent_type) is not None}\n', "KeyError: 'UMLS:C0495252'\n"]
```

**Comment by chunyuma** [comment]
Hi @amykglen , I ran the DSL query of `test_ARAX_workflows.py::test_ranker_float_error_ex1` but got a different error which seems to be a `ARAX_expander.py` error:

```
 - 2021-09-22T01:31:45.157239 ERROR: [UncaughtARAXiError] An uncaught error occurred: no such column: N.node: ['Traceback (most recent call last):\n', '  File "/data/cqm5886/work/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_query.py", line 596, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/data/cqm5886/work/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_expander.py", line 397, in apply\n    decorator.apply(response)\n', '  File "/data/cqm5886/work/RTX/code/ARAX/Testing/../../ARAX/ARAXQuery/ARAX_decorator.py", line 74, in apply\n    cursor.execute(sql_query)\n', 'sqlite3.OperationalError: no such column: N.node\n']
```

Do you have any ideas to solve this error?

**Comment by amykglen** [comment]
hmm, weird, it looks to me like something is off with your KG2c sqlite. I wonder if you have the KG2.7.3 version locally? (`kg2c_v1.0_KG2.7.3.sqlite`) 

since you're running from `master`, you don't want any new databases (you should still be using the regular `configv2.json` that points to all the KG2.7.1 databases).

**Comment by amykglen** [comment]
yes, if you're using the KG2.7.3 `config_local.json`, then `master` will not work right. (the database manager always auto-downloads to match what's in your config file.)

if you're using the KG2.7.3 `config_local.json`, you need to be running code in the `kg2integration` branch; if you're using the regular (KG2.7.1) `configv2.json`, you need to be running code in `master`.

**Comment by chunyuma** [comment]
Ah, I see. Thanks @amykglen. Then I will try running it in the `kg2integration` branch and see what's going on for this issue.

**Comment by chunyuma** [comment]
Hi @amykglen, I fixed this issue in the `kg2integration` branch. Can I directly merge it to `master` branch? Or I do the same modification in the `master` branch?

**Comment by amykglen** [comment]
hi @chunyuma - great! no, if you fixed it in `kg2integration` you can just leave it there (no need to do any merging or add it to `master` as well). at the minihackathon in 20 minutes we'll take care of merging kg2integration into master.

**Comment by chunyuma** [comment]
Awesome, thanks @amykglen.

**Comment by chunyuma** [comment]
@amykglen, I just checked this pytest again and it pass now. I think we close it if it still works in your side.

**Comment by amykglen** [comment]
great, thanks!
