### ISSUE TITLE
Uncaught errors

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1679]
ARAX is throwing some uncaught errors from ARS-initiated queries:
```
2021-09-27T14:48:46.785210 ERROR: [UncaughtARAXiError] An uncaught error occurred: float() argument must be a string or a number, not 'NoneType': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 682, in execute_processing_plan\n    ranker.aggregate_scores_dmk(response)\n', '  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_ranker.py", line 554, in aggregate_scores_dmk\n    value = float(edge_attribute.value)\n', "TypeError: float() argument must be a string or a number, not 'NoneType'\n"]
```

https://arax.ncats.io/devED/api/arax/v1.2/status?id=21713

**Comment by finnagin** [comment]
I'm having a hard time finding examples in that recent_queries list that doesn't say "Normal completion". Is it possible to get the query that the ARS sent that resulted in that error?

**Comment by edeutsch** [comment]
Sure, go here: https://arax.ncats.io/?recent=1
then set the window to 48 hours:
Then click the green OK button
The first column is the query that was run
Unfortunately due to a bug you'll need to add "&last_n_hours=48" to the URL of the query_ids if they're older than 24 hours
so:
https://arax.ncats.io/api/arax/v1.2/status?id=21660&last_n_hours=48

**Comment by finnagin** [comment]
Thanks!

**Comment by edeutsch** [comment]
weird bug now fixed in devED:
https://arax.ncats.io/devED/api/arax/v1.2/status?id=21660
