### ISSUE TITLE
rare ChildProcessError in ARAX query_controller

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1704]
Reported by @edeutsch: 
```
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 44, in <module>
    main()
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 40, in main
    app.run(port=local_config['port'], threaded=True)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 96, in run
    self.app.run(self.host, port=self.port, debug=self.debug, **options)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/werkzeug/serving.py", line 1008, in run_simple
    inner()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/werkzeug/serving.py", line 961, in inner
    srv.serve_forever()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/werkzeug/serving.py", line 717, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 20, in receive_sigchld
    os.waitpid(-1, os.WNOHANG)
ChildProcessError: [Errno 10] No child processes
```

**Comment by edeutsch** [comment]
This is most likely solved with recent work. closing.
