### ISSUE TITLE
Internal server error (all questions)

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#171]
@edeutsch Apparently every question is returning "Internal server error (500)" for all question types.

**Comment by edeutsch** [comment]
hmm, I haven't changed anything. Error is:

[2018-05-21 03:49:42,283] ERROR in app: Exception on /api/rtx/v1/translate [POST]
Traceback (most recent call last):
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 122, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 293, in wrapper
    return function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 26, in translate
    query = txltr.format_response(question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 120, in format_response
    question, parameters, error_message, error_code = self.parse_question(input_question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 54, in parse_question
    parameters = question.get_parameters(input_question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Question.py", line 330, in get_parameters
    node_label = RU.get_node_property(node, "label")  # TODO: Arnab's UMLS lookup
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 211, in get_node_property
    res = session.run(query)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 337, in run
    self._connection.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 263, in send
    self._send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 278, in _send
    self.socket.sendall(data)
  File "/usr/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by edeutsch** [comment]
I simply restarted the flask server just now and it seems happier.

**Comment by dkoslicki** [comment]
@edeutsch It seemed to have worked last night, but this morning I'm still getting internal server errors on http://rtx.ncats.io/ (cache on or off), and on http://rtx.ncats.io/test (cache on or off).

**Comment by dkoslicki** [comment]
Closing this as no longer relevant.
