### ISSUE TITLE
Mysterious error in logs

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1720]
I just noticed the following error in the production ARAX logs:
```
[2021-11-01 15:33:34,369] ERROR in app: Exception on /api/arax/v1.2/query [POST]
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py", line 82, in query
    resp_obj = response.Response.from_dict(json.loads(next(json_generator)))
StopIteration
```

I am uncertain what to make of it.

**Comment by finnagin** [comment]
@edeutsch is this still relevant?

**Comment by edeutsch** [comment]
I have not seen this in years, so closing.
