### ISSUE TITLE
Uncaught errors in KG2!

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1762]
I just noticed in the latest activity monitoring:
![image](https://user-images.githubusercontent.com/12707718/145651975-c393be46-410d-4caf-b546-56e235c1c1d7.png)

I have not had a chance to investigate. Happening a lot.

**Comment by edeutsch** [comment]
```
2021-12-10T22:10:25.106505 ERROR: [UncaughtError] An uncaught error was thrown while trying to Expand using RTX-KG2 (local). Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 531, in _expand_edge_kg2_local
    answer_kg = kg2_querier.answer_one_hop_query(one_hop_qg)
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/Expand/kg2_querier.py", line 70, in answer_one_hop_query
    input_curie_set = set(input_curies)
TypeError: 'NoneType' object is not iterable
```

Looks like the query has no CURIE. I thought we checked for that..
https://arax.ncats.io/devED/api/arax/v1.2/status?id=86757

**Comment by finnagin** [comment]
Just reran and got the following:
```
2022-02-02T07:02:11.869043 ERROR: QueryGraph has no nodes with ids. At least one node must have a specified 'ids'
```

Looks like this has been resolved so I'm going to go ahead and close it.
