### ISSUE TITLE
/beta is failing to handle some queries

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1770]
Some recent queries to /beta such as:
https://arax.ncats.io/devED/api/arax/v1.2/status?id=183712

Are failing with:
```
2022-01-12T14:23:14.107454 DEBUG: [] Number of nodes in KG is 2
2022-01-12T14:23:14.107556 DEBUG: [] Number of nodes in KG by type is Counter({'biolink:ChemicalSubstance': 1})
2022-01-12T14:23:14.107586 DEBUG: [] Number of edges in KG is 1
2022-01-12T14:23:14.107628 DEBUG: [] Number of edges in KG by type is Counter({'biolink:treats': 1})
2022-01-12T14:23:14.107655 DEBUG: [] Number of edges in KG with attributes is 0
2022-01-12T14:23:14.107687 DEBUG: [] Number of edges in KG by attribute Counter()
2022-01-12T14:23:14.107732 DEBUG: [] Storing resulting Message
INFO:root:[query_controller]: child process detected a SIGPIPE; exiting python
ERROR:__main__:Exception on /beta/api/arax/v1.2/query [POST]
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py", line 106, in query
    the_dict = json.loads(next(json_generator))
StopIteration
INFO:werkzeug:127.0.0.1 - - [12/Jan/2022 14:23:14] "POST /beta/api/arax/v1.2/query HTTP/1.1" 500 -
```

**Comment by saramsey** [comment]
OK analysis of this issue led to the observation that we probably should have a try-except block in `query_controller.py`, as shown here:
https://github.com/RTXteam/RTX/blob/fd93509dfd56809bfb3afa829e388e4125fcbe8c/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py#L47

see commit  14a95b2

**Comment by saramsey** [comment]
see also commit 46ee1cc which is for the KG2 query_controller.py

**Comment by finnagin** [comment]
Looks like this is resolved now: https://arax.ncats.io/beta/?r=36243

Okay to close @saramsey @edeutsch ?

**Comment by saramsey** [comment]
Closing this out.
