### ISSUE TITLE
Rerank test

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1778]

**Comment by edeutsch** [comment]
thanks for a great hackathon everyone, I think we have achieved the goal!

There is a new example script here:
https://github.com/RTXteam/RTX/blob/master/code/UI/ClientExamples/Python/ExampleQuery_ReRankTest.py

Its current output is this:
```
$ python ExampleQuery_ReRankTest.py
Retrieved a message with 18 results:
  - 1.000       PTGS1
  - 0.944       L-CITRULLINE
  - 0.944       Calcitonin
  - 0.944       UROKINASE
  - 0.944       STREPTOKINASE
  - 0.944       PTGS2
  - 0.944       Corticotropin
  - 0.944       CYCLIC ADENOSINE MONOPHOSPHATE
  - 0.556       Interleukin-6
  - 0.500       fatty-acid amide hydrolase 1 (rat)
  - 0.500       Cyclooxygenase-2
  - 0.500       SLC22A6
  - 0.333       CD69
  - 0.333       CP
  - 0.333       Binding Sites
  - 0.333       PRB1
  - 0.333       Rheumatoid Factor
  - 0.333       CRP

After score removal:
  -None PTGS1
  -None L-CITRULLINE
  -None Calcitonin
  -None UROKINASE
  -None STREPTOKINASE
  -None PTGS2
  -None Corticotropin
  -None CYCLIC ADENOSINE MONOPHOSPHATE
  -None Interleukin-6
  -None fatty-acid amide hydrolase 1 (rat)
  -None Cyclooxygenase-2
  -None SLC22A6
  -None CD69
  -None CP
  -None Binding Sites
  -None PRB1
  -None Rheumatoid Factor
  -None CRP

Create a new request with the previous message and a workflow to rerank (overlay_connect_knodes,complete_results,score)
Results (18):
  - 1.000       PTGS1
  - 0.944       PTGS2
  - 0.889       STREPTOKINASE
  - 0.833       UROKINASE
  - 0.778       L-CITRULLINE
  - 0.722       Calcitonin
  - 0.667       SLC22A6
  - 0.611       Interleukin-6
  - 0.556       PRB1
  - 0.500       Rheumatoid Factor
  - 0.444       CP
  - 0.389       CRP
  - 0.333       Binding Sites
  - 0.278       CD69
  - 0.222       CYCLIC ADENOSINE MONOPHOSPHATE
  - 0.222       Corticotropin
  - 0.222       Cyclooxygenase-2
  - 0.222       fatty-acid amide hydrolase 1 (rat)
Data: https://arax.ncats.io/api/arax/v1.2/response/35969
GUI: https://arax.ncats.io/beta/?r=35969
```

Note that at the very moment only the /beta endpoint has the required modifications to make this work. Will be replicated to other endpoints soon.

The next and more bold maneuver would be to test with someone else's result!

**Comment by finnagin** [comment]
Awesome!

**Comment by edeutsch** [comment]
Yes, that muffled boom you heard was me trying it on someone else's result set, one from BTE. It failed. Here's the error from the logs:
```
2022-01-27T01:49:56.818820 INFO: [] Processing action 'overlay' with parameters {'action': 'overlay_clinical_info', 'COHD_method': 'paired_concept_frequency'}
2022-01-27T01:49:56.818854 DEBUG: [] Applying Overlay to Message with parameters {'action': 'overlay_clinical_info', 'COHD_method': 'paired_concept_frequency'}
2022-01-27T01:49:57.441348 INFO: [] Converting CURIE identifiers to human readable names
2022-01-27T01:49:57.441429 DEBUG: [] Computing paired concept frequencies.
2022-01-27T01:49:57.441453 INFO: [] Overlaying paired concept frequencies utilizing Columbia Open Health Data. This calls an external knowledge provider and may take a while
2022-01-27T01:49:57.745068 DEBUG: [] Querying Columbia Open Health data for info about Nitrogen dioxide and rheumatoid arthritis
2022-01-27T01:49:57.746543 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:3032552'

2022-01-27T01:49:57.746593 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.746689 DEBUG: [] Querying Columbia Open Health data for info about (1R,2R,3S,7R,9R,10R,12R)-3,10-Dihydroxy-2-(hydroxymethyl)-1,5-dimethylspiro[8-oxatricyclo[7.2.1.02,7]dodec-5-ene-12,2'-oxirane]-4-one and rheumatoid arthritis
2022-01-27T01:49:57.746778 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:442408'

2022-01-27T01:49:57.746807 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.746892 DEBUG: [] Querying Columbia Open Health data for info about Enalapril and rheumatoid arthritis
2022-01-27T01:49:57.746974 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:5388962'

2022-01-27T01:49:57.747003 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.747085 DEBUG: [] Querying Columbia Open Health data for info about Dinoprostone and rheumatoid arthritis
2022-01-27T01:49:57.747165 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:5280360'

2022-01-27T01:49:57.747193 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.747275 DEBUG: [] Querying Columbia Open Health data for info about Maneb and rheumatoid arthritis
2022-01-27T01:49:57.747354 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:3032581'

2022-01-27T01:49:57.747382 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.747462 DEBUG: [] Querying Columbia Open Health data for info about Glyphosate and rheumatoid arthritis
2022-01-27T01:49:57.747540 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:3496'

2022-01-27T01:49:57.747567 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.747652 DEBUG: [] Querying Columbia Open Health data for info about Antigens and rheumatoid arthritis
2022-01-27T01:49:57.747730 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'UMLS:C0003320'

2022-01-27T01:49:57.747764 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.747844 DEBUG: [] Querying Columbia Open Health data for info about Ochratoxin A and rheumatoid arthritis
2022-01-27T01:49:57.747922 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:442530'

2022-01-27T01:49:57.747949 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.748028 DEBUG: [] Querying Columbia Open Health data for info about Kynurenic acid and rheumatoid arthritis
2022-01-27T01:49:57.748105 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:3845'

2022-01-27T01:49:57.748132 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.748216 DEBUG: [] Querying Columbia Open Health data for info about Reactive Oxygen Species and rheumatoid arthritis
2022-01-27T01:49:57.748293 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'UMLS:C0162772'

2022-01-27T01:49:57.748320 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.748403 DEBUG: [] Querying Columbia Open Health data for info about Pesticides and rheumatoid arthritis
2022-01-27T01:49:57.748480 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'MESH:D010575'

2022-01-27T01:49:57.748507 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.748589 DEBUG: [] Querying Columbia Open Health data for info about Immunologic Adjuvants and rheumatoid arthritis
2022-01-27T01:49:57.748665 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'UMLS:C0001551'

2022-01-27T01:49:57.748693 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.748799 DEBUG: [] Querying Columbia Open Health data for info about Leflunomide and rheumatoid arthritis
2022-01-27T01:49:57.748876 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:3899'

2022-01-27T01:49:57.748903 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749009 DEBUG: [] Querying Columbia Open Health data for info about Methotrexate and rheumatoid arthritis
2022-01-27T01:49:57.749087 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:126941'

2022-01-27T01:49:57.749121 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749200 DEBUG: [] Querying Columbia Open Health data for info about Sulfur dioxide and rheumatoid arthritis
2022-01-27T01:49:57.749278 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:1119'

2022-01-27T01:49:57.749321 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749402 DEBUG: [] Querying Columbia Open Health data for info about PENICILLAMINE and rheumatoid arthritis
2022-01-27T01:49:57.749480 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'CHEMBL.COMPOUND:CHEMBL1430'

2022-01-27T01:49:57.749507 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749585 DEBUG: [] Querying Columbia Open Health data for info about Unii-R0HY55EB9E and rheumatoid arthritis
2022-01-27T01:49:57.749689 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:76957227'

2022-01-27T01:49:57.749718 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749797 DEBUG: [] Querying Columbia Open Health data for info about Cyclosporin A and rheumatoid arthritis
2022-01-27T01:49:57.749874 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:5284373'

2022-01-27T01:49:57.749900 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.749978 DEBUG: [] Querying Columbia Open Health data for info about Nitrite and rheumatoid arthritis
2022-01-27T01:49:57.750055 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:946'

2022-01-27T01:49:57.750082 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.750161 DEBUG: [] Querying Columbia Open Health data for info about Atomic oxygen and rheumatoid arthritis
2022-01-27T01:49:57.750238 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'PUBCHEM.COMPOUND:159832'

2022-01-27T01:49:57.750265 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.750355 DEBUG: [] Querying Columbia Open Health data for info about Fertilizers and rheumatoid arthritis
2022-01-27T01:49:57.750433 ERROR: [KeyError] Traceback (most recent call last):
  File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Overlay/overlay_clinical_info.py", line 136, in make_edge_attribute_from_curies
    res = self.mapping_curie_to_omop_ids[subject_curie]
KeyError: 'MESH:D005308'

2022-01-27T01:49:57.750461 ERROR: [UnknownError] Something went wrong when adding the edge attribute from COHD.
2022-01-27T01:49:57.751159 DEBUG: [] Query graph is {'edges': {'e00': {'constraints': [],
                   'exclude': None,
                   'object': 'n01',
                   'option_group_id': None,
                   'predicates': ['biolink:biomarker_for'],
                   'subject': 'n00'}},
 'nodes': {'n00': {'categories': ['biolink:NamedThing'],
                   'constraints': [],
                   'ids': None,
                   'is_set': False,
                   'name': None,
                   'option_group_id': None},
           'n01': {'categories': ['biolink:Disease'],
                   'constraints': [],
                   'ids': ['MONDO:0008383'],
                   'is_set': False,
                   'name': None,
                   'option_group_id': None}}}
2022-01-27T01:49:57.751197 DEBUG: [] Number of nodes in KG is 24
2022-01-27T01:49:57.751268 DEBUG: [] Number of nodes in KG by type is Counter({'biolink:SmallMolecule': 14, 'biolink:ChemicalEntity': 5, 'biolink:ComplexMolecularMixture': 2, 'biolink:MolecularMixture': 2, 'biolink:Disease': 1})
2022-01-27T01:49:57.751294 DEBUG: [] Number of edges in KG is 23
2022-01-27T01:49:57.751343 DEBUG: [] Number of edges in KG by type is Counter({'biolink:biomarker_for': 23})
2022-01-27T01:49:57.751374 DEBUG: [] Number of edges in KG with attributes is 23
2022-01-27T01:49:57.751512 DEBUG: [] Number of edges in KG by attribute Counter({'biolink:aggregator_knowledge_source': 46, None: 23, 'relation': 23, 'normalized_google_distance': 23, 'ngd_publications': 23})
INFO:werkzeug:127.0.0.1 - - [27/Jan/2022 01:49:57] "POST /beta/api/arax/v1.2/query HTTP/1.1" 400 -

```

**Comment by finnagin** [comment]
@chunyuma do you think this might be because those queries are not there when we generate COHD? Maybe we could add some error catching where we just skip that edges if the curies is not present in the `mapping_curie_to_omop_ids` dict. Thoughts?

**Comment by chunyuma** [comment]
Hi @edeutsch and @finnagin, this bug is because those queries have no return from the COHD API (https://cohd.io/api/translator/biolink_to_omop). I've fixed this bug by skipping these edges. It should work now.

**Comment by finnagin** [comment]
Awesome, thanks!

**Comment by edeutsch** [comment]
Yes, thank you! I have just rolled out the latest master to all endpoints that follow master.

Rerunning the example script now succeeds as follows:
```
$ python ExampleQuery_ReRankTest.py
Retrieved a message with 23 results:
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?
  - 1.000       ?

After score removal:
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?
  -None ?

Create a new request with the previous message and a workflow to rerank (overlay_connect_knodes,complete_results,score)
Results (21):
  - 1.000       Dinoprostone
  - 0.952       Atomic oxygen
  - 0.905       Freund's Adjuvant
  - 0.857       Methotrexate
  - 0.810       Leflunomide
  - 0.635       PENICILLAMINE
  - 0.603       Maneb
  - 0.587       Kynurenic acid
  - 0.524       Cyclosporin A
  - 0.524       Nitrite
  - 0.492       Nitrogen dioxide
  - 0.476       Enalapril
  - 0.429       Ochratoxin A
  - 0.413       (1R,2R,3S,7R,9R,10R,12R)-3,10-Dihydroxy-2-(hydroxymethyl)-1,5-dimethylspiro[8-oxatricyclo[7.2.1.02,7]dodec-5-ene-12,2'-oxirane]-4-one
  - 0.349       Reactive Oxygen Species
  - 0.333       Fertilizers
  - 0.333       Pesticides
  - 0.317       Glyphosate
  - 0.317       Unii-R0HY55EB9E
  - 0.095       Immunologic Adjuvants
  - 0.048       Antigens
Data: https://arax.ncats.io/api/arax/v1.2/response/36024
GUI: https://arax.ncats.io/beta/?r=36024
```

The resultset as furnished originally by BTE is this: https://arax.ncats.io/?r=843990fb-4cd0-46c0-95cb-644990b226e5
23 results. Somewhat lackluster scoring and ranking.

The little test program fetches this results, strips out all scores (not really necessary, but perhaps feels like a closer example) and then runs it through /beta with the workflow we devised and the result is: https://arax.ncats.io/beta/?r=36024
Delightfully scored and ranked.
Maybe someone with a keen eye can examine the output to see if all is as expected.
I suppose I notice a few oddities:
1) There don't seem to be any NGD edges. We expect these, no?
2) The top two hits have two fisher exact test edges. This may be related that BTE had 23 results and now we have 21 results. Perhaps two duplicates were merged? but we compute two fisher exact tests first?

Anyway, it works at a basic level, but maybe it could work a bit better.

**Comment by finnagin** [comment]
I think maybe the lack of ngd is because we use the fastngd method which is per-computed from our curies.

**Comment by dkoslicki** [comment]
@edeutsch Is this issue still relevant?

**Comment by edeutsch** [comment]
I think we got it working well enough at the last hackathon, closing.
