### ISSUE TITLE
KG2 is throwing errors right now

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1829]
From the latest logs:
```
2022-05-02T22:04:38.633403 DEBUG: [] Expanding e00 by querying Plover directly
2022-05-02T22:04:39.246708 DEBUG: [] Sending NodeSynonymizer.get_canonical_curies() a list of 1 curies
2022-05-02T22:04:39.861387 DEBUG: [] Got response back from NodeSynonymizer
2022-05-02T22:04:39.861530 DEBUG: [] Using 1 curies as canonical curies for qnode n00
2022-05-02T22:04:39.861588 DEBUG: [] Split 1 input curies into 1 batches to send to Plover
2022-05-02T22:04:39.861673 INFO: [] Max edges allowed per input curie for this query is: 1000
2022-05-02T22:04:39.861698 DEBUG: [] Sending batch 1 to Plover (has 1 input curies)
2022-05-02T22:04:39.878744 ERROR: [UncaughtError] An uncaught error was thrown while trying to Expand using infores:rtx-kg2 (local). Error was: Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f19e143e9d0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kg2cploverdb.ci.transltr.io', port=443): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19e143e9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 543, in _expand_edge_kg2_local
    answer_kg = kg2_querier.answer_one_hop_query(one_hop_qg)
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/Expand/kg2_querier.py", line 78, in answer_one_hop_query
    plover_answer, response_status = self._answer_query_using_plover(query_graph, log)
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/controllers/../../../../../../ARAX/ARAXQuery/Expand/kg2_querier.py", line 184, in _answer_query_using_plover
    headers={'accept': 'application/json'})
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests_cache/session.py", line 122, in request
    **kwargs,
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests_cache/session.py", line 148, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests_cache/session.py", line 178, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kg2cploverdb.ci.transltr.io', port=443): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19e143e9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

2022-05-02T22:04:39.878813 DEBUG: [] Got answers from all KPs; merging them into one KG
2022-05-02T22:04:39.878845 DEBUG: [] Merging answer into Message.KnowledgeGraph
2022-05-02T22:04:39.879324 DEBUG: [] Sending NodeSynonymizer.get_canonical_curies() a list of 1 curies
2022-05-02T22:04:40.583253 DEBUG: [] Got response back from NodeSynonymizer
```

**Comment by edeutsch** [comment]
I am looking for the PloverDB testing sequence, but haven't found it yet.

**Comment by amykglen** [comment]
https://github.com/RTXteam/PloverDB#how-to-test

I'm looking into it too

**Comment by edeutsch** [comment]
Assuming Plover has died, it might be useful to adjust the above code that is now exploding with an exception to instead provide a graceful informative error that Plover is unreachable. and maybe automatically email Ke and Kanna "have you killed our pod again"?

**Comment by amykglen** [comment]
oh, there was a message from Kanna in the devops-teamexpanderagent channel:
```
Hi @Amy Glen (Expander Agent) Ploverdb ci will be down, I'm converting the yaml file to helm charts. I will update you if everything is done from my end.
```

**Comment by amykglen** [comment]
I've expressed that we use the ITRB Plover CI instance for our production KG2/ARAX instance, but I'm not sure they grasp that

**Comment by edeutsch** [comment]
aha, okay, planned downtime.
thanks, I did not see that.

**Comment by amykglen** [comment]
well, "planned" seems like a stretch - that notification was sent immediately before the instance was taken down... I'm switching our config files to point to the production ITRB plover, which seems to be working currently..

**Comment by amykglen** [comment]
ok, both `kg2` and `kg2beta` seem to be working again - I pointed them to the prod ITRB plover (`https://kg2cploverdb.transltr.io`) instead of the CI ITRB plover (`https://kg2cploverdb.ci.transltr.io`)

and I made a note about adding a more informative error when plover isn't working correctly

**Comment by edeutsch** [comment]
thanks for your help, closing!
