### ISSUE TITLE
Trouble getting local ARAX UI to run

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1877]
I'm following the instructions here to try to get my local ARAX UI going (doing testing for #1871):
https://github.com/RTXteam/RTX/wiki/Dev-info#setting-up-local-ui

and this is what my `config.js` looks like:
```
// API config
// this is an optional file that specifies alternate API settings
// if not present, then default settings in rtx.js will be used
// IMPORTANT: change filename to "config.js" for changes to take effect
let config = {};
config.base    = 'http://localhost:5001/';
config.baseAPI = config.base + "api/arax/v1.3";
```

but when I do Step 3 (`python3 -m openapi_server`), I keep seeing this:
```
(arax3.9) amys-mbp:python-flask-server amyglen$ python -m openapi_server

WARNING: '1.3.0-beta' is not a valid release version

WARNING: '1.0.0-beta' is not a valid release version
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/amyglen/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/amyglen/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/amyglen/Projects/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 55, in <module>
    main()
  File "/Users/amyglen/Projects/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 51, in main
    app.run(port=local_config['port'], threaded=True)
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 104, in run
    self.app.run(self.host, port=self.port, debug=self.debug, **options)
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/Users/amyglen/.pyenv/versions/arax3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/Users/amyglen/.pyenv/versions/3.9.7/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Users/amyglen/.pyenv/versions/3.9.7/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Users/amyglen/.pyenv/versions/3.9.7/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```
even though port 5001 does not appear to be in use (confirmed with `sudo lsof -i:5001`). 

I'm running this from a branch off of `NewFmt` (called `queryids`).

anyone know what might be wrong?

**Comment by edeutsch** [comment]
The port that the server listens on is not governed by the config.js, that is Javascript for the client.
The port is governsed by this: https://github.com/RTXteam/RTX/blob/2a982c2b17f9566527795672a92c54139731da79/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py#L44-L48
So it will be 5000 by default, and to override to 5001 you should create a flask_config.json file with:
```
 { "port": 5000 }
```

Might that solve it?

**Comment by amykglen** [comment]
hmm, not sure exactly what you mean. so is there something wrong with the directions in the wiki? (I was following them exactly..) where exactly would I add the `flask_config.json` file?

**Comment by edeutsch** [comment]
yes, those directions are slightly out of date, I suppose. Do you have something running on 5000? another instance?
The easiest would be to switch the wiki to show port 5000
Or if you want to stay with 5001, then add a file RTX/code/UI/OpenAPI/python-flask-server/openapi_server/flask_config.json that reads:
```
 { "port": 5001 }
```
and then try starting flask

**Comment by amykglen** [comment]
ah, I see! turns out apparently my mac did have something listening on port 5000: https://developer.apple.com/forums/thread/682332

I just went ahead and turned that off because I don't use it... 

now it works with port 5000. I'll update the wiki...

**Comment by amykglen** [comment]
well, ok, it seems to run, but doesn't quite answer queries  yet...

![Screen Shot 2022-07-27 at 11 49 40 AM](https://user-images.githubusercontent.com/49423686/181349524-43a0ba8b-1c7b-4a22-8135-6ec86a2f5771.png)

<img width="690" alt="Screen Shot 2022-07-27 at 11 50 20 AM" src="https://user-images.githubusercontent.com/49423686/181349605-0892ff12-9e35-4806-a313-87c071d27a29.png">

**Comment by edeutsch** [comment]
Did you update the config.js (top of this thread) to point to 5000?

**Comment by edeutsch** [comment]
OH, I also notice that there is a mismatch between the config.js saying 1.3, but there is a error message in your log screen shot for v1.2.
Are you using the NewFmt branch for everything?

**Comment by amykglen** [comment]
briefly I had v1.2 in my `config.js`, but even with v1.3 in there, it still gives the same kind of error. my `config.js` currently looks like this:
```
// API config
// this is an optional file that specifies alternate API settings
// if not present, then default settings in rtx.js will be used
// IMPORTANT: change filename to "config.js" for changes to take effect
let config = {};
config.base    = 'http://localhost:5000/';
config.baseAPI = config.base + "api/arax/v1.3";
```
<img width="858" alt="Screen Shot 2022-07-27 at 11 58 25 AM" src="https://user-images.githubusercontent.com/49423686/181351049-dda23046-a7d9-4a1d-9b33-2ee41241e144.png">

![Screen Shot 2022-07-27 at 11 59 16 AM](https://user-images.githubusercontent.com/49423686/181351111-d2c5ba6d-343a-4199-8068-8248bf0c1607.png)

**Comment by amykglen** [comment]
from 8/3 discussion: @rcpeene will try this out as well and then we may coordinate a call with @edeutsch to debug any issues

**Comment by amykglen** [comment]
I think we should leave it open - still hasn't been resolved. planning to get @edeutsch's help debugging at some point.
