### ISSUE TITLE
`connect` throwing an error

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1881]
For this DSL:
```
add_qnode(name=glucose, key=n0)
add_qnode(name=diabetes, key=n1)
connect(action=connect_nodes, max_path_length=3, shortest_path=false)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
We get this error: `ERROR: An uncaught error occurred: '<' not supported between instances of 'str' and 'int': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 762, in execute_processing_plan\n connect.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 193, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 261, in __connect_nodes\n if self.parameters[\'max_path_length\'] < 1 or self.parameters[\'max_path_length\'] > 5:\n', "TypeError: '<' not supported between instances of 'str' and 'int'\n"]`

**Comment by dkoslicki** [comment]
May be related: removing the max_path_length, I get this error: `ERROR: An uncaught error occurred: 'NoneType' object has no attribute 'edges': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 762, in execute_processing_plan\n connect.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 193, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 397, in __connect_nodes\n if new_response.status == \'OK\' and len(new_response.envelope.message.knowledge_graph.edges) > len(self.response.envelope.message.knowledge_graph.edges):\n', "AttributeError: 'NoneType' object has no attribute 'edges'\n"]`
But curiously is not reproducible
