### ISSUE TITLE
DISK FULL!!!

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1898]
arax.ncats.io

```
$ df
Filesystem      1K-blocks      Used Available Use% Mounted on
overlay         101583780  54555844  47011552  54% /
tmpfs               65536         0     65536   0% /dev
tmpfs            32352992         0  32352992   0% /sys/fs/cgroup
shm                 65536         0     65536   0% /dev/shm
/dev/nvme1n1   1031069848 982708568         0 100% /mnt/data
/dev/nvme0n1p1  101583780  54555844  47011552  54% /etc/hosts
```

```
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.12/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/config/__init__.py", line 163, in main
    config=config
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/main.py", line 305, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 428, in pytest_sessionfinish
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))
  File "/mnt/data/python/Python-3.7.12/lib/python3.7/site-packages/_pytest/cacheprovider.py", line 193, in set
    f.write(data)
OSError: [Errno 28] No space left on device
```

**Comment by amykglen** [comment]
was this related to @chunyuma uploading a database?

**Comment by amykglen** [comment]
we should be able to delete any KG2 directories for KG2.7.3 or older

**Comment by chunyuma** [comment]
I have already stopped uploading the new database there.

**Comment by amykglen** [comment]
does anyone object to deleting these two directories on arax.ncats.io? (`config_dbs.json` does not refer to any of these, so I believe it's safe to delete them)
```
/data/orangeboard/databases/KG2.7.2
/data/orangeboard/databases/KG2.7.3
```

**Comment by edeutsch** [comment]
No objections, Highly encouraged!

**Comment by amykglen** [comment]
both of those directories have been deleted - closing
