### ISSUE TITLE
ARAX uncaught error

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1955]
Looking in the system activity logs, I note that ARAX has aborted a few times with:
![image](https://user-images.githubusercontent.com/12707718/213359482-94930e38-2b75-4276-8ac1-e2052e8bd444.png)

A repro query seems to be:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "t_edge": {
          "knowledge_type": "inferred",
          "object": "Prot",
          "predicates": [
            "biolink:affects"
          ],
          "subject": "Chemical"
        }
      },
      "nodes": {
        "Chemical": {
          "categories": [
            "biolink:ChemicalEntity"
          ],
          "ids": [
            "CHEMBL.COMPOUND:CHEMBL403664",
            "CHEMBL.TARGET:CHEMBL2176857",
            "MESH:D037662",
            "CHEMBL.TARGET:CHEMBL2095189",
            "MESH:C000593877",
            "UMLS:C0127082",
            "UMLS:C0033640",
            "UMLS:C0079323",
            "UMLS:C0079904",
            "UMLS:C0145779",
            "UMLS:C0084692",
            "UMLS:C0040018",
            "UMLS:C0389071",
            "UMLS:C0003242",
            "UMLS:C0008145"
          ]
        },
        "Prot": {
          "categories": [
            "biolink:Protein",
            "biolink:Polypeptide"
          ]
        }
      }
    }
  }
}
```

The error appears to be:
```
2023-01-19T05:00:37.183993 DEBUG: Applying Expand to Message with parameters {'kp': None, 'edge_key': ['t_edge'], 'node_key': [], 'prune_threshold': 50, 'kp_timeout': 30, 'return_minimal_metadata': False, 'DTD_threshold': 0.8, 'DTD_slow_mode': False}
2023-01-19T05:00:37.184084 DEBUG: Making sure QG only uses canonical predicates
2023-01-19T05:00:37.186021 ERROR: An uncaught error occurred: 'QNode' object has no attribute 'name': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 735, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/devED/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 373, in apply\n log.error(f"No CURIEs found for {object_qnode.name}", error_code="NoCURIEs")\n', "AttributeError: 'QNode' object has no attribute 'name'\n"]
```

This appears to fail in both production as well as master.
Although the proximal cause is clear, it's not clear to me why this hasn't been a problem all along, or why it's even executing line 373.

**Comment by edeutsch** [comment]
great, thanks! I just confirmed that ARAX doesn't crash now.
But leaving this issue open for @dkoslicki because more development is needed to address the root cause?
