### ISSUE TITLE
various disasters

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1957]
I came back from a meeting to find ARAX non functional.
Most obvious errors were:
```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1040, 'Too many connections')
```

I restarted our central MySQL server.

I then tried restarting some services but got this:

```
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
```

I don't think my recent check ins could have done this??

Also there's this:
![image](https://user-images.githubusercontent.com/12707718/214689616-958d3b8e-fca7-4125-9108-c44329748a23.png)
![image](https://user-images.githubusercontent.com/12707718/214689616-958d3b8e-fca7-4125-9108-c44329748a23.png)
![image](https://user-images.githubusercontent.com/12707718/214689616-958d3b8e-fca7-4125-9108-c44329748a23.png)

I guess we need more capacity control.

**Comment by isbluis** [comment]
Seems like it is mostly Workflow Runner via a few IP addresses (roughly 3000 requests each)  :

![image](https://user-images.githubusercontent.com/37852256/214690972-7916c4b3-5ebd-42a8-88d6-a3f8711d4565.png)


Also worth mentioning that in over 2200 queries, there is an InvalidKP error, but they keep making the same request.  So I would add some end user education to the list.  Do we know who it is?

![image](https://user-images.githubusercontent.com/37852256/214691862-60ec9c02-a4c0-4b8c-b20c-666f3951e15e.png)

**Comment by isbluis** [comment]
Also, over 4800 queries produce the same error, and they are still attempting it:

![image](https://user-images.githubusercontent.com/37852256/214692454-db977fa3-2936-4cc0-8fa5-f26c29ca4ca7.png)


It looks like each of these avoidable hits to our system consume ~10 seconds, so for all 7000 queries it becomes ~20 hours of CPU time.  Maybe time for creative IP blocking?

**Comment by edeutsch** [comment]
workflow runner is a robot. A Translator robot. But maybe it has fallen into the wrong hands..

**Comment by edeutsch** [comment]
I'll try to include some capacity control into the monitoring system

**Comment by edeutsch** [comment]
Probably ChatGPT is looking for some more info..

**Comment by saramsey** [comment]
Is it possible to get a full stack trace of the `UncaughtARAXiError`?

**Comment by edeutsch** [comment]
Sure, of course:
https://arax.transltr.io/api/arax/v1.3/status/logs

One error seems to be:
```
2023-01-26T17:11:35.216475 DEBUG: [] Loading meta map (already exists and isn't due for a refresh)
2023-01-26T17:11:35.221731 WARNING: [] Unable to access infores:text-mining-provider-cooccurrence's /meta_knowledge_graph endpoint (returned status of 502 for URL https://cooccurrence.transltr.io)
2023-01-26T17:11:35.224466 WARNING: [] An uncaught error was thrown while trying to Expand using infores:automat-icees-kg, so I couldn't get answers from that KP. Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 693, in _expand_edge_async
    from Expand.trapi_querier import TRAPIQuerier
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 34, in <module>
    class TRAPIQuerier:
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 37, in TRAPIQuerier
    kp_selector: KPSelector = KPSelector(), force_local: bool = False):
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/kp_selector.py", line 36, in __init__
    self.meta_map = self._load_meta_map()
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/kp_selector.py", line 227, in _load_meta_map
    meta_map = pickle.load(map_file)
_pickle.UnpicklingError: pickle data was truncated

```

and the main one that is featured above:
```
2023-01-26T17:48:12.183545 DEBUG: [] Loading meta map (already exists and isn't due for a refresh)
2023-01-26T17:48:12.184416 DEBUG: [] Writing response JSON to S3 bucket
2023-01-26T17:48:12.188940 ERROR: [UncaughtARAXiError] An uncaught error occurred: 'utf-8' codec can't decode byte 0x95 in position 23: invalid start byte: ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 735, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 183, in apply\n    kp_selector = KPSelector(valid_kps_override={"infores:rtx-kg2"}, log=log) if mode == "RTXKG2" else KPSelector(log=log)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 36, in __init__\n    self.meta_map = self._load_meta_map()\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_selector.py", line 227, in _load_meta_map\n    meta_map = pickle.load(map_file)\n', "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 23: invalid start byte\n"]
```

and one more:
```
2023-01-26T17:48:12.943565 WARNING: [] An uncaught error was thrown while trying to Expand using infores:spoke, so I couldn't get answers from that KP. Error was: Traceback (most recent call last):
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_expander.py", line 693, in _expand_edge_async
    from Expand.trapi_querier import TRAPIQuerier
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 34, in <module>
    class TRAPIQuerier:
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/trapi_querier.py", line 37, in TRAPIQuerier
    kp_selector: KPSelector = KPSelector(), force_local: bool = False):
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/kp_selector.py", line 36, in __init__
    self.meta_map = self._load_meta_map()
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/Expand/kp_selector.py", line 227, in _load_meta_map
    meta_map = pickle.load(map_file)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 23: invalid start byte

```

**Comment by edeutsch** [comment]
Closing in favor of #1952
