### ISSUE TITLE
module 'datetime' has no attribute 'now'

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1973]
The build is still failing. One apparent error is this:
```
2023-03-13T19:00:13.854800 ERROR: [UncaughtARAXiError] An uncaught error occurred: module 'datetime' has no attribute 'now': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 735, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 382, in apply\n    infer_response = inferer.apply(response, infer_input_parameters)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_infer.py", line 336, in apply\n    getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])()  # thank you [https://stackoverflow.com/questions/11649848/call-methods-by-string\n](https://stackoverflow.com/questions/11649848/call-methods-by-string/n)', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_infer.py", line 451, in __drug_treatment_graph_expansion\n    self.response, self.kedge_global_iter, self.qedge_global_iter, self.qnode_global_iter, self.option_global_iter = iu.genrete_treat_subgraphs(self.response, top_drugs, top_paths, qedge_id, self.kedge_global_iter, self.qedge_global_iter, self.qnode_global_iter, self.option_global_iter)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Infer/scripts/infer_utilities.py", line 333, in genrete_treat_subgraphs\n    EdgeAttribute(original_attribute_name="defined_datetime", value=datetime.now().strftime("%Y-%m-%d %H:%M:%S"), attribute_type_id="metatype:Datetime"),\n', "AttributeError: module 'datetime' has no attribute 'now'\n"]
```

Other parts of the code (the logger) is using this, which may be a possible solution?
```
timestamp = str(datetime.datetime.now().isoformat())
```

**Comment by saramsey** [comment]
Is there a stacktrace, by chance?

**Comment by saramsey** [comment]
Seems to be coming from here: https://github.com/RTXteam/RTX/blob/53e34723b2586f91d630ef376245af25da69f402/code/ARAX/ARAXQuery/Infer/scripts/infer_utilities.py#L333

**Comment by saramsey** [comment]
Paging @chunyuma and @dkoslicki

**Comment by edeutsch** [comment]
I should have clarified that this error message comes from running the tests on our automated test machine here:
https://github.com/RTXteam/RTX/actions/runs/4408199578/jobs/7722891489

This problem may not be manifesting itself on arax.ncats.io as I run the test suite there in devED

I wonder if this might have something to do with import order or something only weirdly semi-produceable, perhaps a difference between import datetime and import datetime.datetime. I dunno.

**Comment by chunyuma** [comment]
@edeutsch, I've fixed this bug. It should work now. Could you please test it again in DevED? Thanks!

**Comment by edeutsch** [comment]
yes, that fixed it, tests passed on arax.ncats.io devED

Can anyone see if it is passing now on the integration server?

**Comment by edeutsch** [comment]
I will note that with the current fix, ARAX_response.py does this:
```
import datetime
timestamp = str(datetime.datetime.now().isoformat())
```

and infer_utilities.py does:
```
from datetime import datetime
value=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
```

It is unclear to me whether one is preferred over the other or whether importing datetime in two different ways in two different files has any impact.

I suppose it doesn't matter, but I don't know enough about Python to be certain.

**Comment by chunyuma** [comment]
Thanks @edeutsch!

> It is unclear to me whether one is preferred over the other or whether importing datetime in two different ways in two different files has any impact.

I think it doesn't matter in using either way. The only difference between these two methods might be the first one might consume a little bit more memory (because it imports everything from the `datetime` package ) but it is so tiny can be neglected.

**Comment by edeutsch** [comment]
Thanks, I think this is resolved then, closing.
