### ISSUE TITLE
Uncaught resultify error when a qedge isn't fulfilled

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1989]
seeing an uncaught error for this query, which doesn't produce any answers (at least with the UI's default timeouts and Expand's default pruning), but nonetheless shouldn't result in an uncaught error:
```
add_qnode(name=ATP1A3, key=n0)
add_qnode(categories=biolink:PhenotypicFeature, key=n1)
add_qnode(categories=biolink:Protein, key=n2)
add_qnode(categories=biolink:ChemicalEntity, key=n3)
add_qedge(subject=n0, object=n1, key=e0)
add_qedge(subject=n1, object=n2, key=e1)
add_qedge(subject=n2, object=n3, key=e2)
expand()
resultify()
filter_results(action=limit_number_of_results, max_results=50)
```

```
2023-03-21T20:30:43.816849 DEBUG: After removing dead-end paths, KG counts are: e0: 316, e1: 1106, n0: 1, n1: 48, n2: 50, subclass:n1--n1: 5
2023-03-21T20:30:43.818520 WARNING: No paths were found in any KPs satisfying qedge e2. KPs used were: ['infores:automat-ctd', 'infores:spoke', 'infores:automat-pharos', 'infores:service-provider-trapi', 'infores:automat-gtopdb', 'infores:automat-drug-central', 'infores:automat-icees-kg', 'infores:automat-viral-proteome', 'infores:automat-hetio', 'infores:automat-biolink', 'infores:automat-hmdb', 'infores:automat-intact', 'infores:automat-uberongraph', 'infores:automat-ontology-hierarchy', 'infores:rtx-kg2', 'infores:text-mining-provider-cooccurrence', 'infores:automat-human-goa', 'infores:cam-kp', 'infores:automat-robokop', 'infores:molepro']
2023-03-21T20:30:43.836977 INFO: Processing action 'resultify' with parameters {'': 'true'}
2023-03-21T20:30:43.837067 DEBUG: Applying Resultifier to Message with parameters {'': 'true'}
2023-03-21T20:30:43.837139 DEBUG: Expanded qedges are {'e0', 'e2', 'subclass:n1--n1', 'e1'}, expanded qnodes are {'n1', 'n2', 'n0', 'n3'}; will resultify only this sub-QG
2023-03-21T20:30:43.839334 ERROR: An uncaught error occurred: 'n1': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 748, in execute_processing_plan\n resultifier.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 123, in apply\n self._resultify(describe=False)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 253, in _resultify\n results = _get_results_for_kg_by_qg(kg,\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 460, in _get_results_for_kg_by_qg\n return _get_results_for_kg_by_qg(kg, qg, log=log)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 562, in _get_results_for_kg_by_qg\n subclass_clusters, child_to_parent_map = _get_subclass_clusters(kg_edge_keys_by_qg_key, kg_node_keys_by_qg_key, kg, qg, log)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 1113, in _get_subclass_clusters\n node_keys_for_qnode = kg_node_keys_by_qg_key[subclass_qnode_key]\n', "KeyError: 'n1'\n"]
```

**Comment by ShannonRanio** [comment]
@saramsey do you know if this can be closed or  who I should ask since @amykglen was assigned but she is no longer with us. Thx

**Comment by saramsey** [comment]
Creating branch `issue-1989` to work on this
