### ISSUE TITLE
requirements.txt changes broke synonymizer build (pandas version)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2036]
this isn't urgent because it only affects **build** code, and not running ARAX code, but the changes made to `requirements.txt` in 778976a80825dcef6d13f63d0ce39420fc054fbe seem to have broken the (new) synonymizer build. I think it's probably due to the `pandas` version (which was downgraded from 1.5.3 --> 1.4.3). error looks like this:
```
2023-05-22 09:12:54,821 INFO: Filtering out nodes without any name matches..
/Users/amyglen/Projects/RTX/code/kg2c/synonymizer_build/4_cluster_match_graph.py:235: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  nodes_with_name_matches_df = nodes_with_names_df[nodes_with_names_df.groupby(by="name_simplified").transform("size") > 1]
Traceback (most recent call last):
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1156, in _transform_general
    path, res = self._choose_path(fast_path, slow_path, group)
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1208, in _choose_path
    res = slow_path(group)
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1196, in <lambda>
    slow_path = lambda group: group.apply(
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/frame.py", line 8845, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/apply.py", line 733, in apply
    return self.apply_standard()
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/apply.py", line 857, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/apply.py", line 873, in apply_series_generator
    results[i] = self.f(v)
  File "/Users/amyglen/.pyenv/versions/rtxspring23/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 1197, in <lambda>
    lambda x: getattr(x, func)(*args, **kwargs), axis=self.axis
TypeError: 'int' object is not callable
```
for the latest build I just used my `pyenv` from before those changes to `requirements.txt` were made, which worked fine. but at some point we should fix this...

I'd prefer if we could go back to pandas 1.5.3, but I know we've been having trouble with package dependencies/versions lately, so if that's not an option, I can change the build code to work with 1.4.3

**Comment by edeutsch** [comment]
I think I have fixed this. Let me know if it's still a problem.

**Comment by amykglen** [comment]
yep, works now, thanks!

**Comment by edeutsch** [comment]
ah, sorry for stomping on tabulate
