### ISSUE TITLE
Connect errors

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2039]
Error:
```
2023-05-24T17:44:36.843122 INFO: Processing action 'connect' with parameters {'action': 'connect_nodes', 'max_path_length': '4'}
2023-05-24T17:45:38.870228 ERROR: An uncaught error occurred: 'NoneType' object has no attribute 'edges': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_query.py", line 774, in execute_processing_plan\n connect.apply(response, action[\'parameters\'])\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 193, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/../../../../../ARAX/ARAXQuery/ARAX_connect.py", line 400, in __connect_nodes\n if new_response.status == \'OK\' and len(new_response.envelope.message.knowledge_graph.edges) > len(self.response.envelope.message.knowledge_graph.edges):\n', "AttributeError: 'NoneType' object has no attribute 'edges'\n"]
```
Query:
```
add_qnode(name=il17a)
add_qnode(name=alzheimers disease)
connect(action=connect_nodes,max_path_length=4)
resultify()
filter_results(action=limit_number_of_results, max_results=500)
```

**Comment by kvnthomas98** [comment]
Verified at https://arax.ncats.io/?r=152500
