### ISSUE TITLE
Test Build workflow on cicd.rtx.ai not working again?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2068]
It seems like every commit to `master` causes the continuous testing system to return a fail. It looks like it's a database syncing issue. does anyone know how to fix?

```
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
2023-07-06T07:33:39.559954 ERROR: [UncaughtARAXiError] An uncaught error occurred: Synonymizer specified in config_dbs file does not exist locally, even after running the database manager! It should be at: /mnt/data/orangeboard/production/RTX/code/ARAX/NodeSynonymizer/node_synonymizer_v1.1_KG2.8.0.1.sqlite: ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 743, in execute_processing_plan\n    messenger.add_qnode(response,action[\'parameters\'])\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/test/../ARAXQuery/ARAX_messenger.py", line 244, in add_qnode\n    synonymizer = NodeSynonymizer()\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/../NodeSynonymizer/node_synonymizer.py", line 50, in __init__\n    raise ValueError(f"Synonymizer specified in config_dbs file does not exist locally, even after "\n', 'ValueError: Synonymizer specified in config_dbs file does not exist locally, even after running the database manager! It should be at: /mnt/data/orangeboard/production/RTX/code/ARAX/NodeSynonymizer/node_synonymizer_v1.1_KG2.8.0.1.sqlite\n']
```

**Comment by sundareswarpullela** [comment]
At least a part of this issue is caused by not having a 2.8.0.1c plover instance up and running (Replaced with 2.8.3c). I am still looking into why the `node_synonymizer_v1.1_KG2.8.0.1.sqlite` is not found. It says that the file is not available in the production directory: `mnt/data/orangeboard/production/RTX/code/ARAX/NodeSynonymizer/node_synonymizer_v1.1_KG2.8.0.1.sqlite`, leading me to believe that the file is not present on the ITRB or cats server and not a cicd specific issue.

**Comment by saramsey** [comment]
Any update on this issue, @sundareswarpullela ?  We have PloverDB-KG2.8.0.1c working in CI, test, and prod.

**Comment by sundareswarpullela** [comment]
Hey @saramsey , the issue here seems to be that the flle `node_synonymizer_v1.1_KG2.8.0.1.sqlite` is not present on arax.ncats.io in the path `mnt/data/orangeboard/production/RTX/code/ARAX/NodeSynonymizer/node_synonymizer_v1.1_KG2.8.0.1.sqlite`. I will get my access on Monday (07/24/2023) so I can check then.

**Comment by saramsey** [comment]
Any update on this, @sundareswarpullela ?

**Comment by saramsey** [comment]
I am checking on the completeness and integrity of the KG2.8.3c-derived databases on `cicd.rtx.ai`....

**Comment by saramsey** [comment]
Here is the manifest of what is in `/home/rtxconfig/KG2.8.3` on `arax-databases.rtx.ai`:
```
rtxconfig@ip-172-31-63-185:~/KG2.8.3$ ls -alh
total 100G
drwxrwxr-x  3 rtxconfig rtxconfig 4.0K Jul 29 20:14 .
drwxr-x--- 11 rtxconfig rtxconfig 4.0K Aug  2 18:08 ..
-rw-r--r--  1 rtxconfig rtxconfig  43G Jul 28 17:06 ExplainableDTD_v1.0_KG2.8.3_refresh.db
-rw-rw-r--  1 rtxconfig rtxconfig   73 Jul 29 20:13 ExplainableDTD_v1.0_KG2.8.3_refresh.db.md5
-rw-r--r--  1 rtxconfig rtxconfig 1.3G Jun  6 03:20 autocomplete_v1.0_KG2.8.3.sqlite
-rw-r--r--  1 rtxconfig rtxconfig 4.9G Jun 30 21:16 curie_to_pmids_v1.0_KG2.8.3.sqlite
drwxrwxr-x  2 rtxconfig rtxconfig 4.0K Jul 28 15:54 extra_files
-rw-rw-r--  1 rtxconfig rtxconfig  98K Jun  6 10:07 fda_approved_drugs_v1.0_KG2.8.3c.pickle
-rw-r--r--  1 rtxconfig rtxconfig  38G Jun  6 10:07 kg2c_v1.0_KG2.8.3.sqlite
-rw-rw-r--  1 rtxconfig rtxconfig 8.0M Jun  6 10:07 meta_kg_v1.0_KG2.8.3c.json
-rw-r--r--  1 rtxconfig rtxconfig  13G Jun  6 03:20 node_synonymizer_v1.0_KG2.8.3.sqlite
```
and the corresponding manifest

**Comment by saramsey** [comment]
Here are the MD5 hashes of the files. 

First, for the files on `arax-databases.rtx.ai`:
```
rtxconfig@ip-172-31-63-185:~/KG2.8.3$ for name in `ls *.db *.sqlite *.pickle`; do echo $name; md5sum $name; done
ExplainableDTD_v1.0_KG2.8.3_refresh.db
d8970baa45b8c6a7a94e690cef87dabf  ExplainableDTD_v1.0_KG2.8.3_refresh.db
autocomplete_v1.0_KG2.8.3.sqlite
ec43942334dafe788b320fea0f80fa6f  autocomplete_v1.0_KG2.8.3.sqlite
curie_to_pmids_v1.0_KG2.8.3.sqlite
3efe0ece1f69e96d6cc6128d69d5a3c9  curie_to_pmids_v1.0_KG2.8.3.sqlite
fda_approved_drugs_v1.0_KG2.8.3c.pickle
36e91d29d207457bc02518e9a2d2be1c  fda_approved_drugs_v1.0_KG2.8.3c.pickle
kg2c_v1.0_KG2.8.3.sqlite
46da18fe9290eb433272838353095615  kg2c_v1.0_KG2.8.3.sqlite
node_synonymizer_v1.0_KG2.8.3.sqlite
e9adb03ad6ee02846c2b321f1e03afbb  node_synonymizer_v1.0_KG2.8.3.sqlite
```

**Comment by saramsey** [comment]
And now the files on `cicd.rtx.ai`:
```
ubuntu@ip-172-31-10-160:/mnt/data/orangeboard/databases/KG2.8.3$ for name in `ls`; do echo $name; md5sum $name; done
ExplainableDTD_v1.0_KG2.8.3_refresh.db
d8970baa45b8c6a7a94e690cef87dabf  ExplainableDTD_v1.0_KG2.8.3_refresh.db
autocomplete_v1.0_KG2.8.3.sqlite
ec43942334dafe788b320fea0f80fa6f  autocomplete_v1.0_KG2.8.3.sqlite
curie_to_pmids_v1.0_KG2.8.3.sqlite
3efe0ece1f69e96d6cc6128d69d5a3c9  curie_to_pmids_v1.0_KG2.8.3.sqlite
fda_approved_drugs_v1.0_KG2.8.3c.pickle
36e91d29d207457bc02518e9a2d2be1c  fda_approved_drugs_v1.0_KG2.8.3c.pickle
kg2c_v1.0_KG2.8.3.sqlite
46da18fe9290eb433272838353095615  kg2c_v1.0_KG2.8.3.sqlite
meta_kg_v1.0_KG2.8.3c.json
a6f5cb592562e6fcb7d66b8906e4ed29  meta_kg_v1.0_KG2.8.3c.json
node_synonymizer_v1.0_KG2.8.3.sqlite
e9adb03ad6ee02846c2b321f1e03afbb  node_synonymizer_v1.0_KG2.8.3.sqlite
```

**Comment by saramsey** [comment]
So, the MD5 hashes all match. Only difference is the directory `extra_files` on `arax-databases.rtx.ai`.

**Comment by saramsey** [comment]
So, near as I can tell, `ARAX_database_manager.py` now runs cleanly on `cicd.rtx.ai`:
```
ubuntu@ip-172-31-10-160:~/RTX/code$ python3 ARAX/ARAXQuery/ARAX_database_manager.py
config_secrets.json                                                             100%  572    11.5KB/s   00:00
Local paths:
  cohd_database: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/COHD_local/data/COHDdatabase_v1.0_KG2.8.0.db
  graph_database: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/Prediction/GRAPH_v1.0_KG2.8.0.1_refreshed.sqlite
  log_model: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/Prediction/LogModel_v1.0_KG2.7.6.pkl
  curie_to_pmids: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/NormalizedGoogleDistance/curie_to_pmids_v1.0_KG2.8.3.sqlite
  node_synonymizer: /home/ubuntu/RTX/code/ARAX/NodeSynonymizer/node_synonymizer_v1.0_KG2.8.3.sqlite
  dtd_prob: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/Prediction/DTD_probability_database_v1.0_KG2.8.0.1_refreshed.db
  kg2c_sqlite: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/KG2c/kg2c_v1.0_KG2.8.3.sqlite
  kg2c_meta_kg: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/meta_kg_v1.0_KG2.8.3c.json
  fda_approved_drugs: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/fda_approved_drugs_v1.0_KG2.8.3c.pickle
  autocomplete: /home/ubuntu/RTX/code/autocomplete/autocomplete_v1.0_KG2.8.3.sqlite
  explainable_dtd_db: /home/ubuntu/RTX/code/ARAX/KnowledgeSources/Prediction/ExplainableDTD_v1.0_KG2.8.3_refresh.db
  xcrg_embeddings: /home/ubuntu/RTX/code/ARAX/ARAXQuery/Infer/data/xCRG_data/chemical_gene_embeddings_v1.0.KG2.8.0.1.npz
  xcrg_increase_model: /home/ubuntu/RTX/code/ARAX/ARAXQuery/Infer/data/xCRG_data/xcrg_increase_model_v1.0.KG2.8.0.1.pt
  xcrg_decrease_model: /home/ubuntu/RTX/code/ARAX/ARAXQuery/Infer/data/xCRG_data/xcrg_decrease_model_v1.0.KG2.8.0.1.pt
Remote locations:
  cohd_database: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0/COHDdatabase_v1.0_KG2.8.0.db
  graph_database: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0.1/GRAPH_v1.0_KG2.8.0.1_refreshed.sqlite
  log_model: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.7.6/LogModel_v1.0_KG2.7.6.pkl
  curie_to_pmids: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/curie_to_pmids_v1.0_KG2.8.3.sqlite
  node_synonymizer: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/node_synonymizer_v1.0_KG2.8.3.sqlite
  dtd_prob: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0.1/DTD_probability_database_v1.0_KG2.8.0.1_refreshed.db
  kg2c_sqlite: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/kg2c_v1.0_KG2.8.3.sqlite
  kg2c_meta_kg: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/meta_kg_v1.0_KG2.8.3c.json
  fda_approved_drugs: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/fda_approved_drugs_v1.0_KG2.8.3c.pickle
  autocomplete: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/autocomplete_v1.0_KG2.8.3.sqlite
  explainable_dtd_db: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.3/ExplainableDTD_v1.0_KG2.8.3_refresh.db
  xcrg_embeddings: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0.1/chemical_gene_embeddings_v1.0.KG2.8.0.1.npz
  xcrg_increase_model: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0.1/xcrg_increase_model_v1.0.KG2.8.0.1.pt
  xcrg_decrease_model: rtxconfig@arax-databases.rtx.ai:/home/rtxconfig/KG2.8.0.1/xcrg_decrease_model_v1.0.KG2.8.0.1.pt
Docker paths:
  cohd_database: /mnt/data/orangeboard/databases/KG2.8.0/COHDdatabase_v1.0_KG2.8.0.db
  graph_database: /mnt/data/orangeboard/databases/KG2.8.0.1/GRAPH_v1.0_KG2.8.0.1_refreshed.sqlite
  log_model: /mnt/data/orangeboard/databases/KG2.7.6/LogModel_v1.0_KG2.7.6.pkl
  curie_to_pmids: /mnt/data/orangeboard/databases/KG2.8.3/curie_to_pmids_v1.0_KG2.8.3.sqlite
  node_synonymizer: /mnt/data/orangeboard/databases/KG2.8.3/node_synonymizer_v1.0_KG2.8.3.sqlite
  dtd_prob: /mnt/data/orangeboard/databases/KG2.8.0.1/DTD_probability_database_v1.0_KG2.8.0.1_refreshed.db
  kg2c_sqlite: /mnt/data/orangeboard/databases/KG2.8.3/kg2c_v1.0_KG2.8.3.sqlite
  kg2c_meta_kg: /mnt/data/orangeboard/databases/KG2.8.3/meta_kg_v1.0_KG2.8.3c.json
  fda_approved_drugs: /mnt/data/orangeboard/databases/KG2.8.3/fda_approved_drugs_v1.0_KG2.8.3c.pickle
  autocomplete: /mnt/data/orangeboard/databases/KG2.8.3/autocomplete_v1.0_KG2.8.3.sqlite
  explainable_dtd_db: /mnt/data/orangeboard/databases/KG2.8.3/ExplainableDTD_v1.0_KG2.8.3_refresh.db
  xcrg_embeddings: /mnt/data/orangeboard/databases/KG2.8.0.1/chemical_gene_embeddings_v1.0.KG2.8.0.1.npz
  xcrg_increase_model: /mnt/data/orangeboard/databases/KG2.8.0.1/xcrg_increase_model_v1.0.KG2.8.0.1.pt
  xcrg_decrease_model: /mnt/data/orangeboard/databases/KG2.8.0.1/xcrg_decrease_model_v1.0.KG2.8.0.1.pt
saving new version file to /home/ubuntu/RTX/code/ARAX/KnowledgeSources/db_versions.json
Downloading any missing databases from arax-databases.rtx.ai to /mnt/data/orangeboard/databases
On database cohd_database in download_to_mnt()
  Database already exists, no need to download
On database graph_database in download_to_mnt()
  Database already exists, no need to download
On database log_model in download_to_mnt()
  Database already exists, no need to download
On database curie_to_pmids in download_to_mnt()
  Database already exists, no need to download
On database node_synonymizer in download_to_mnt()
  Database already exists, no need to download
On database dtd_prob in download_to_mnt()
  Database already exists, no need to download
On database kg2c_sqlite in download_to_mnt()
  Database already exists, no need to download
On database kg2c_meta_kg in download_to_mnt()
  Database already exists, no need to download
On database fda_approved_drugs in download_to_mnt()
  Database already exists, no need to download
On database autocomplete in download_to_mnt()
  Database already exists, no need to download
On database explainable_dtd_db in download_to_mnt()
  Database already exists, no need to download
On database xcrg_embeddings in download_to_mnt()
  Database already exists, no need to download
On database xcrg_increase_model in download_to_mnt()
  Database already exists, no need to download
On database xcrg_decrease_model in download_to_mnt()
  Database already exists, no need to download
cohd_database not present locally, downloading or symlinking now......
graph_database not present locally, downloading or symlinking now......
log_model not present locally, downloading or symlinking now......
curie_to_pmids not present locally, downloading or symlinking now......
node_synonymizer not present locally, downloading or symlinking now......
dtd_prob not present locally, downloading or symlinking now......
kg2c_sqlite not present locally, downloading or symlinking now......
kg2c_meta_kg not present locally, downloading or symlinking now......
fda_approved_drugs not present locally, downloading or symlinking now......
autocomplete not present locally, downloading or symlinking now......
explainable_dtd_db not present locally, downloading or symlinking now......
xcrg_embeddings not present locally, downloading or symlinking now......
xcrg_increase_model not present locally, downloading or symlinking now......
xcrg_decrease_model not present locally, downloading or symlinking now......
```

**Comment by saramsey** [comment]
OK, so running `kp_info_cacher.py::refresh_kp_info_caches()` takes on `cicd.rtx.ai`:
```
time python3 test_kp_info_cacher.py
...
The process with process ID 1679538 has FINISHED refreshing the KP info caches

real	0m16.982s
user	0m1.221s
sys	0m0.163s
```

**Comment by saramsey** [comment]
I should probably revert `MAX_TOTAL_WAIT_FOR_CACHE_SEC` to 60 seconds instead of 180 seconds.

**Comment by saramsey** [comment]
OK, so for some reason, `cicd.rtx.ai` is running the code in the `itrb-test` branch:

<img width="764" alt="Screenshot 2023-08-02 at 5 12 33 PM" src="https://github.com/RTXteam/RTX/assets/5562107/888f641f-a682-4b8b-911f-13da6ed523ba">

**Comment by saramsey** [comment]
OK, one of the last three commits did the trick, apparently?

<img width="756" alt="Screenshot 2023-08-03 at 8 34 22 AM" src="https://github.com/RTXteam/RTX/assets/5562107/f134d75f-4c78-4d9e-bebd-a6f7cbac165d">

However, the `pytest` suite is still overall failing due to a (presumably unrelated) `AssertionError` which was present even before any of the above commits:

<img width="726" alt="Screenshot 2023-08-03 at 8 36 06 AM" src="https://github.com/RTXteam/RTX/assets/5562107/a56674e4-164d-402b-aad5-c9ad9b6325c1">

However, _test_ test is one that we can probably test on the laptop.

**Comment by edeutsch** [comment]
ah, so I now realize something that you probably already figured out. By moving the KP meta caching to a background thread in the running application, we created a problem when running tests in a scenario where there is no application running (e.g. pytest)

**Comment by saramsey** [comment]
Fixed.
<img width="950" alt="Screenshot 2023-08-03 at 10 31 27 AM" src="https://github.com/RTXteam/RTX/assets/5562107/65be6c63-73bd-48a3-a82c-f16e62195255">

**Comment by saramsey** [comment]
> ah, so I now realize something that you probably already figured out. By moving the KP meta caching to a background thread in the running application, we created a problem when running tests in a scenario where there is no application running (e.g. pytest)

Yes, that was an adventure sorting out!  But yes, I came to the same conclusion, and have put in countermeasures which I hope will not cause problems elsewhere. In any event, the "Test Build" is now passing.

**Comment by edeutsch** [comment]
Great, thanks. I wonder if it worth documenting somewhere on the overall design (as "as built") of this system. It's quite complex and by documenting it we might A) discover more flaws in design and B) aid future maintainers

**Comment by saramsey** [comment]
> Great, thanks. I wonder if it worth documenting somewhere on the overall design (as "as built") of this KP meta-KG cache system (generation and usage). It's quite complex and by documenting it we might A) discover more flaws in design and B) aid future maintainers

Good idea. Logged as a separate issue request: https://github.com/RTXteam/RTX/issues/2086
