### ISSUE TITLE
query_tracker crash

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2087]
Seen in the KG2 logs:
```
2023-08-07T21:50:10.629473 INFO: [] Processing action 'return' with parameters {'store': 'false'}
2023-08-07T21:50:10.629510 INFO: [] Processing is complete and resulted in 1 results.
INFO: Deleted ARAXOngoingQuery.query_id=1265381
INFO:werkzeug:127.0.0.1 - - [07/Aug/2023 21:50:12] "POST /api/rtxkg2/v1.4/query HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_background_tasker.py", line 134, in run_tasks
    ongoing_queries_by_remote_address = query_tracker.check_ongoing_queries()
  File "/mnt/data/orangeboard/kg2/RTX/code/UI/OpenAPI/python-flask-server/KG2/openapi_server/../../../../../ARAX/ARAXQuery/ARAX_query_tracker.py", line 387, in check_ongoing_queries
    pid = ongoing_query.pid
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 942, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/attributes.py", line 973, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/loading.py", line 1465, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<ARAXOngoingQuery at 0x7fc50e758c10>' has been deleted, or its row is otherwise not present.
```

**Comment by isbluis** [comment]
Added a `try` statement to (hopefully) avoid this error. Closing
