### ISSUE TITLE
Error when expand uses resultify for pruning (option group query)

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2166]
For the DSL:
```
# NSCLC -> n2 -> MET
add_qnode(key=nCANCER,ids=OMIM:MTHU063395)
add_qnode(key=n2)
add_qnode(key=nMET,ids=NCBIGene:4233)
add_qedge(key=e1,subject=nCANCER,object=n2)
add_qedge(key=e2,subject=n2,object=nMET)
# NSCLC -> n2 -[optional]-> n3 ->MET
add_qnode(key=n3,option_group_id=option1)
add_qedge(key=e3,subject=n2,object=n3,option_group_id=option1)
add_qedge(key=e4,subject=n3,object=nMET,option_group_id=option1)
# expand
expand(kp=infores:rtx-kg2)
resultify(ignore_edge_direction=true)
```
Gives the error:
`2023-10-13T16:45:17.406945 DEBUG: Calling Resultify from Expand for pruning
2023-10-13T16:46:45.852565 ERROR: An uncaught error occurred: 'MONDO:0005233': ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 761, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 502, in apply\n overarching_kg = self._prune_kg(qnode_key, pre_prune_threshold, overarching_kg, query_graph, log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 1135, in _prune_kg\n intermediate_results_response = eu.create_results(qg_expanded_thus_far, kg_copy, log,\n', ' File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/expand_utilities.py", line 689, in create_results\n resultifier.apply(prune_response, {})\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 124, in apply\n self._resultify(mode=mode, describe=False)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 254, in _resultify\n results = _get_results_for_kg_by_qg(kg,\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 463, in _get_results_for_kg_by_qg\n return _get_results_for_kg_by_qg(kg, qg, mode, log=log)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 733, in _get_results_for_kg_by_qg\n child_is_useful = _node_in_result_is_useful(result_node_key, subclass_qnode_key, parent_key,\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_resultify.py", line 848, in _node_in_result_is_useful\n parent_neighbors = result_kg_adj_map[qnode_key][parent_key][qnode_neighbor_key]\n', "KeyError: 'MONDO:0005233'\n"]`

**Comment by dkoslicki** [comment]
Here's a picture of the qGraph: 
![image](https://github.com/RTXteam/RTX/assets/6362936/10edfad7-dbfa-40a5-bd77-4f15d2264784)

**Comment by amykglen** [comment]
thanks - I should be able to look into this sometime next week!

**Comment by saramsey** [comment]
Can this be prioritized for after Nov. 7?  Not sure about the urgency but I imagine that post-Nov. 7 would be ideal in terms of timeline?

**Comment by dkoslicki** [comment]
Not urgent @saramsey, I was trying to find a DSL command Andy would find useful for a side project of his. So just a bug to be gotten to eventually

**Comment by dkoslicki** [comment]
Just a note: as of March 13, 2024, the same error persists

**Comment by amykglen** [comment]
Thanks - sorry, I'll try to get to this over spring break!

**Comment by amykglen** [comment]
alright, @dkoslicki - this has been fixed and tested in the `issue2166` branch. the (fast) pytest suite is passing, as well as all the 'slow' tests for resultify and expand.

I guess we should merge it to `master`?

**Comment by amykglen** [comment]
also fyi @dkoslicki - I noticed that there might be a better identifier to use for the cancer/NSCLC node: [MONDO:0005233](https://arax.ncats.io/?term=MONDO:0005233) (instead of [OMIM:MTHU063395](https://arax.ncats.io/?term=OMIM:MTHU063395), which appears to have missed being clustered with other synonyms)

**Comment by amykglen** [comment]
anyone object to me merging this fix into `master`? there were actually a few resultify bugs I fixed (mainly involving option group or `exclude` edge queries)

**Comment by amykglen** [comment]
alright, I merged it into `master`

**Comment by amykglen** [comment]
@dkoslicki - I verified that your original query completes successfully now on /beta, although note that if you're running it in the UI, you have to up the prune threshold and KP timeout settings to get it to return any results (I used 5000 for the prune threshold and 120 for the KP timeout).

https://arax.ncats.io/beta/?r=231492

good to close this issue?

**Comment by dkoslicki** [comment]
Yup, looks good to me! Thanks Amy
