### ISSUE TITLE
AssertionError in Orangeboard.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#221]
reltype passed to add_rel is not in dict_reltype_dirs; reltype=directly_interacts_with
Traceback (most recent call last):
  File "BuildMasterKG.py", line 125, in <module>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "/usr/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "BuildMasterKG.py", line 125, in <lambda>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "BuildMasterKG.py", line 105, in make_master_kg
    add_pc2_to_kg()
  File "BuildMasterKG.py", line 64, in add_pc2_to_kg
    ob.add_rel('directly_interacts_with', 'PC2', node1, node2, extended_reltype="directly_interacts_with")
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/Orangeboard.py", line 371, in add_rel
    assert False
AssertionError

**Comment by dkoslicki** [comment]
Closing due to #788
