### ISSUE TITLE
shutdown bug in ARAX

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2226]
```
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 137, in <module>
    except ChildProcessError as e:
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 130, in main
    def receive_sigchld(signal_number, frame):
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 125, in run
    self.app.run(self.host, port=self.port, debug=self.debug,
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/werkzeug/serving.py", line 1107, in run_simple
    srv.serve_forever()
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/site-packages/werkzeug/serving.py", line 804, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/mnt/data/python/Python-3.9.16/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/__main__.py", line 85, in receive_sigterm
    with open(CONFIG_FILE, 'r') as infile:
AttributeError: module 'os' has no attribute 'exit'
```

**Comment by saramsey** [comment]
Thank you, @kvnthomas98
