### ISSUE TITLE
ARAX opentelemetry/jaeger not working in ITRB

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2227]
Here is the error:
```
Exception while exporting Span batch.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/opentelemetry/sdk/trace/export/__init__.py", line 373, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/opentelemetry/exporter/jaeger/thrift/__init__.py", line 225, in export
    self._agent_client.emit(batch)
  File "/usr/local/lib/python3.9/dist-packages/opentelemetry/exporter/jaeger/thrift/send.py", line 95, in emit
    udp_socket.sendto(buff, self.address)
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by kvnthomas98** [comment]
Changing itrb agent host to "jaeger-otel-agent.sri" fixed issue
