### ISSUE TITLE
Sponsor reports missing scores

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2279]
I got a report from the ARS folks:

we have noticed that ARAX is returning null scores for some of their results. can you look into it?

https://arax.ncats.io/?r=44def7dd-809e-48bd-a411-fc9ae0d8e55c

![image](https://github.com/RTXteam/RTX/assets/12707718/d4299d7f-b7d9-4c93-bcac-75af39e4607f)

Messages shows an exception:

2024-05-17T13:48:09.613686 ERROR: [UncaughtARAXiError]    An uncaught error occurred: 'NoneType' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 780, in execute_processing_plan\n expander.apply(response, action[\'parameters\'], mode=mode)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 357, in apply\n response, overarching_kg = self.get_inferred_answers(inferred_qedge_keys, query_graph, response)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 640, in get_inferred_answers\n infer_response = inferer.apply(response, infer_input_parameters)\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_infer.py", line 340, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_infer.py", line 503, in __drug_treatment_graph_expansion\n self.response, self.kedge_global_iter, self.qedge_global_iter, self.qnode_global_iter, self.option_global_iter = iu.genrete_treat_subgraphs(self.response, top_drugs, top_paths, qedge_id, self.kedge_global_iter, self.qedge_global_iter, self.qnode_global_iter, self.option_global_iter)\n', ' File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Infer/scripts/infer_utilities.py", line 190, in genrete_treat_subgraphs\n node_info = xdtdmapping.get_node_info(node_id=drug_canonical_id)\n', ' File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Infer/scripts/build_mapping_db.py", line 216, in get_node_info\n res = res._make(cursor.fetchone())\n', ' File "/usr/lib/python3.9/collections/__init__.py", line 439, in _make\n result = tuple_new(cls, iterable)\n', "TypeError: 'NoneType' object is not iterable\n"]

Looks like maybe a problem in ARAX_infer.py", line 340, in apply:
```
getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string'
```
or maybe ARAX_infer.py", line 503, I'm uncertain where the ultimate problem lies.

Can anyone familiar with this part of the code look into it?

**Comment by kvnthomas98** [comment]
I'll work on this

**Comment by saramsey** [comment]
Hi @kvnthomas98 just checking back on this?

**Comment by edeutsch** [comment]
fixed.
