### ISSUE TITLE
AttributeError in UpdateNodesInfo.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#228]
Traceback (most recent call last):
  File "UpdateNodesInfo.py", line 554, in <module>
    UpdateNodesInfo.update_anatomy_nodes_desc()
  File "UpdateNodesInfo.py", line 159, in update_anatomy_nodes_desc
    node['desc'] = QueryEBIOLSExtended.get_anatomy_description(node_id)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/QueryEBIOLSExtended.py", line 82, in get_anatomy_description
    return QueryEBIOLSExtended.__get_entity("get_anatomy", anatomy_id)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/QueryEBIOLSExtended.py", line 65, in __get_entity
    ontology_id = entity_id[:entity_id.find(":")]
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by saramsey** [comment]
OK somehow CURIE IDs are not in the KG being built by BuildMasterKG.py.
