### ISSUE TITLE
ExpatError in UpdateNodesInfo.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#239]
Traceback (most recent call last):
  File "UpdateNodesInfo.py", line 569, in <module>
    UpdateNodesInfo.update_metabolite_nodes_desc()
  File "UpdateNodesInfo.py", line 527, in update_metabolite_nodes_desc
    node['desc'] = QueryHMDB.get_compound_desc(hmdb_url)
  File "/mnt/data/orangeboard/RTX/code/reasoningtool/kg-construction/QueryHMDB.py", line 67, in get_compound_desc
    obj = xmltodict.parse(results)
  File "/usr/local/lib/python3.5/dist-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 3, column 382

**Comment by DeqingQu** [comment]
I found the bug and have fixed it this evening. You can pull the latest commit from Github to fix the bug.
The bug is caused by the informal return type of HMDB Url. The return data of "http://www.hmdb.ca/metabolites/HMDB0012194.xml" is not following the XML format. It will jump to http://www.hmdb.ca/metabolites/HMDB0000283 automatically and return a string in HTML format. My solution is to check the first 5 character of the response data whether equals to "<?xml". If not, it will return None temporally. I will try to solve it in a more elegant way.

**Comment by saramsey** [comment]
thanks, I am closing out this issue
