### ISSUE TITLE
DumpNeo4jToCSV crashed when dumping all relations

### ISSUE THREAD

**Issue by DeqingQu** [RTXteam/RTX#254]
The neo4j connection is failed when dumping all relations from the graph. If I add a limit to the cypher, like `'match (n)-[r]-(m) return n.UUID, m.UUID, r LIMIT 10000'`, it can work correctly. So I guess the crash is caused by too many relations in our graph and we cannot dump all relations in one time.

```
10-248-18-67:kg-construction alex$ python3 DumpNeo4jToCSV.py -u xxx -p xxx
Traceback (most recent call last):
  File "DumpNeo4jToCSV.py", line 77, in <module>
    make_rels_file()
  File "DumpNeo4jToCSV.py", line 46, in make_rels_file
    for record in query_result:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neo4j/v1/api.py", line 718, in records
    self._session.fetch()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neo4j/v1/api.py", line 356, in fetch
    detail_count, _ = self._connection.fetch()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 283, in fetch
    return self._fetch()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 300, in _fetch
    self._receive()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 338, in _receive
    raise self.Error("Failed to read from defunct connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to read from defunct connection Address(host='127.0.0.1', port=7687)

```

**Comment by dkoslicki** [comment]
Closing due to #788
