### ISSUE TITLE
QueryOMIM AttributeError

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#298]
Traceback (most recent call last):
  File "BuildMasterKG.py", line 166, in <module>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "/usr/lib/python3.5/timeit.py", line 213, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/lib/python3.5/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "BuildMasterKG.py", line 166, in <lambda>
    running_time = timeit.timeit(lambda: run_function(), number=1)
  File "BuildMasterKG.py", line 119, in make_master_kg
    bne.expand_all_nodes()
  File "/mnt/data/kg-from-scratch-issue295/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 629, in expand_all_nodes
    self.expand_node(node)
  File "/mnt/data/kg-from-scratch-issue295/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 617, in expand_node
    expand_method(self)
  File "/mnt/data/kg-from-scratch-issue295/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 572, in expand_disease
    self.expand_genetic_condition(node)
  File "/mnt/data/kg-from-scratch-issue295/RTX/code/reasoningtool/kg-construction/BioNetExpander.py", line 497, in expand_genetic_condition
    res_dict = self.query_omim_obj.disease_mim_to_gene_symbols_and_uniprot_ids(node.name)
  File "/mnt/data/kg-from-scratch-issue295/RTX/code/reasoningtool/kg-construction/QueryOMIM.py", line 72, in disease_mim_to_gene_symbols_and_uniprot_ids
    result_dict = r.json()
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by DeqingQu** [comment]
I have fixed the AttributeError bug.

However, an assertion error happens in the construction function of the QueryOMIM. I will check it.

**Comment by DeqingQu** [comment]
Hi, @saramsey 
When I tried our API key for cookie (using both our codes and OMIM website), it returned a 400 error. So I guess there might be something wrong with our API key. Can you help me check it?

You can try it on OMIM website. Our API key is 1YCxuN7PRHyrpuZnO7F5gQ.
https://api.omim.org/api/html
