### ISSUE TITLE
MemoryError in build-kg2.sh

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#373]
Seem to be hitting the memory limit of the `r5.12xlarge` EC2 instance:
```
u/kg2-build/kg2-owl.json /home/ubuntu/kg2-build/kg2-semmeddb-edges.json /home/ubuntu/kg2-build/kg2.json
+ /home/ubuntu/kg2-venv/bin/python3 /home/ubuntu/kg2-code/get_nodes_json_from_kg_json.py /home/ubuntu/kg2-build/kg2.json /home/ubuntu/kg2-build/kg2-nodes.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/get_nodes_json_from_kg_json.py", line 38, in <module>
    graph = json.load(input_file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError
```

**Comment by saramsey** [comment]
seems like we may have to move to a `r4.16xlarge` instance

**Comment by saramsey** [comment]
making an AMI `kg2dev` now
