### ISSUE TITLE
out of memory error running push_kg2.py with the whole kg2.json

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#425]
```
Traceback (most recent call last):
  File "RTX/code/kg2/push_kg2.py", line 235, in <module>
    count = kg2_pusher.push_nodes(args.file)
  File "RTX/code/kg2/push_kg2.py", line 123, in push_nodes
    res = self.run_cypher(cypher_upload_nodes)
  File "RTX/code/kg2/push_kg2.py", line 69, in run_cypher
    res = session.run(cypher)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/neo4j/__init__.py", line 499, in run
    self._connection.fetch()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/neobolt/direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/neobolt/direct.py", line 759, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.lang.OutOfMemoryError: Java heap space
Failed to write data to connection Address(host='0.0.0.0', port=7687) (Address(host='127.0.0.1', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2080)'")
Failed to write data to connection Address(host='0.0.0.0', port=7687) (Address(host='127.0.0.1', port=7687)); ("0; 'Underlying socket connection gone (_ssl.c:2080)'")
```

**Comment by saramsey** [comment]
(1) upgraded to an EC2 instance with 128 GiB of RAM (using AMI, so no files were changed)
(2) neo4j was in a corrupted state (not surprising given that Neo4j died with an OutOfMemoryException) so I nuked the database
(3) couldn't log into the Neo4j since I didn't know the password for user "neo4j", so I reset the password (I will give you & Veronica the new password on Wednesday; I try not to send passwords through email).
(4) apoc was not working; I tweaked the config file and got it working
