### ISSUE TITLE
ModuleNotFound error just running upload_kg_json_to_neo4j.py --help

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#428]
python3 kg2-code/upload_kg_json_to_neo4j.py --help
Traceback (most recent call last):
  File "kg2-code/upload_kg_json_to_neo4j.py", line 15, in <module>
    from RTXConfiguration import RTXConfiguration

reported by @BluePiggy49

**Comment by BluePiggy49** [comment]
(kg2-venv) ubuntu@ip-172-31-3-26:~$ python3 kg2-code/upload_kg_json_to_neo4j.py --help
Traceback (most recent call last):
  File "kg2-code/upload_kg_json_to_neo4j.py", line 15, in <module>
    from RTXConfiguration import RTXConfiguration
ModuleNotFoundError: No module named 'RTXConfiguration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kg2-code/upload_kg_json_to_neo4j.py", line 18, in <module>
    from RTXConfiguration import RTXConfiguration
ModuleNotFoundError: No module named 'RTXConfiguration'
