### ISSUE TITLE
hyphens instead of underscores in edge label property

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#473]

**Comment by saramsey** [comment]
```
"disease-causing_germline_mutation(s)_(gain_of_function)_in": 206,
"disease-causing_germline_mutation(s)_(loss_of_function)_in": 1093,
"disease-causing_germline_mutation(s)_in": 4586,
"disease-causing_somatic_mutation(s)_in": 178,
```

**Comment by saramsey** [comment]
Look for others in the JSON report:

https://s3-us-west-2.amazonaws.com/rtx-kg2-public/kg2-report.json

**Comment by edeutsch** [comment]
but this hyphen is because the English is hyphenated, not as a space replacement..

**Comment by saramsey** [comment]
This issue is causing problems with Neo4j indexing on the `edge_label` property:
```
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/create_indexes_constraints.py --user neo4j
Please enter the Neo4j database password


Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/create_indexes_constraints.py", line 123, in <module>
    create_index(edge_label_list, "edge_label")
  File "/home/ubuntu/kg2-code/create_indexes_constraints.py", line 75, in create_index
    run_query(index_query)
  File "/home/ubuntu/kg2-code/create_indexes_constraints.py", line 28, in run_query
    query = session.run(query)
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/neo4j/__init__.py", line 499, in run
    self._connection.fetch()
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/neobolt/direct.py", line 422, in fetch
    return self._fetch()
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/neobolt/direct.py", line 464, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/neobolt/direct.py", line 759, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Invalid input '-': expected an identifier character, whitespace or '(' (line 1, column 41 (offset: 40))
"CREATE INDEX ON :allele_absent_from_wild-type_chromosomal_location (edge_label)"
                                         ^
```

**Comment by saramsey** [comment]
opting to fix this by modifying `kg_json_to_tsv.py`; so hyphens will continue to be in the original `kg2.json` file (since the hyphen has a distinct meaning from an underscore, as Eric points out), but the hyphens will be turned into underscores in the `edges.tsv` file

**Comment by saramsey** [comment]
<img width="527" alt="Screen Shot 2019-09-03 at 12 43 46 PM" src="https://user-images.githubusercontent.com/5562107/64203535-7f497b00-ce48-11e9-9444-f653cb5d46fc.png">
