### ISSUE TITLE
orphan edges

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#544]
This is an issue to document that we are working on dealing with the several million "orphan edges" that could not be connected to nodes in KG2 by the script `merge_graphs.py`.

**Comment by amykglen** [comment]
latest discovery (documenting for the record):
- some of the remaining orphan edges have CUI nodes that don't exist in kg2 in neo4j, even though their CUIs are valid/current (e.g., "CUI:C1527116")
- we think this is due to `umls-mth.ttl` ('Metathesaurus Names') being removed from `owl-load-inventory.yaml` in May 2019 (https://github.com/RTXteam/RTX/commit/40d4fb1a5a6c32f684c63057e0bb6a1187d93d9e - unclear why it was removed)

**Comment by amykglen** [comment]
so, interestingly, the above node I mentioned (CUI:C1527116) **is** now in KG2 after rebuilding with the umls-mth.ttl file included, but it's name seems off - I thought it should be "workers" (see: http://linkedlifedata.com/resource/umls/id/C1527116), but it's appearing as "Delusional disorder", which is oddly the same name as the troublesome "MTH:NOCODE" node (discussed in #558)...

here's node CUI:C1527116's info from neo4j:
```
"properties": {
          "iri": "https://identifiers.org/umls/cui/C1527116",
          "synonym": "[]",
          "category_label": "protein",
          "deprecated": "False",
          "name": "Delusional disorder",
          "provided_by": "https://identifiers.org/umls/cui",
          "id": "CUI:C1527116",
          "category": "http://w3id.org/biolink/vocab/Protein",
          "update_date": "2019-08-02 10:32:18 GMT",
          "publications": "[]"
        }
```

**Comment by saramsey** [comment]
OK, I wonder if we should set up an isolated test to reproduce this bug. We could run the script `multi_owl_to_json_kg.py` with a two-line configuration file `owl-load-inventory-test.yaml` that contains:
```
-
  url: https://identifiers.org/umls/STY
  file: umls_semantictypes.ttl
  download: false
  title: UMLS Semantic Types
-
  download: false
  file: umls-mth.ttl
  title: Metathesaurus Names
  url: https://identifiers.org/umls/MTH
```
and save the results to a file `kg2-test-mth.json`

**Comment by saramsey** [comment]
we could then take a look at the `CUI:C1527116` node in the output file

**Comment by amykglen** [comment]
Sounds good - I'm getting an error when I try to run `multi_owl_to_json_kg.py` as you suggest.. haven't figured it out yet:
```
ubuntu@ip-172-31-0-169:~/kg2-build$ ~/kg2-code/multi_owl_to_json_kg.py --categoriesFile ~/kg2-code/curies-to-categories.yaml --curiesToURILALFile ~/kg2-code/curies-to-urls-lookaside-list.yaml --owlLoadInventoryFile ~/kg2-code/owl-load-inventory-test.yaml --outputFile kg2-test-mth.json
Reading ontology file: umls_semantictypes.ttl; size: 28.90 KiB
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/multi_owl_to_json_kg.py", line 913, in <module>
    test_mode)
  File "/home/ubuntu/kg2-code/multi_owl_to_json_kg.py", line 190, in make_kg2
    ont_source_info_dict['title'])
  File "/home/ubuntu/kg2-code/multi_owl_to_json_kg.py", line 127, in load_owl_file_return_ontology_and_metadata
    ontology = make_ontology_from_local_file(file_name)
  File "/home/ubuntu/kg2-code/multi_owl_to_json_kg.py", line 99, in make_ontology_from_local_file
    cp = subprocess.run(['owltools', file_name, '-o', '-f', 'json', temp_file_name])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'owltools': 'owltools'
``` 
But 'owltools' does exist in kg2-build:
```
ubuntu@ip-172-31-0-169:~/kg2-build$ stat owltools
  File: owltools
  Size: 38617461  	Blocks: 75432      IO Block: 4096   regular file
Device: 10301h/66305d	Inode: 786871      Links: 1
Access: (0775/-rwxrwxr-x)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2019-11-12 16:52:02.221125567 +0000
Modify: 2019-08-02 03:42:54.040826177 +0000
Change: 2019-08-02 03:42:54.040826177 +0000
 Birth: -
```

**Comment by saramsey** [comment]
```
export PATH=$PATH:/home/ubuntu/kg2-build
```

**Comment by amykglen** [comment]
ah, got it, thanks - here's node `CUI:C1527116` from the output file (`kg2-test-mth.json`):

```
{
  "id": "CUI:C1527116",
  "iri": "https://identifiers.org/umls/cui/C1527116",
  "name": "Delusional disorder",
  "full name": null,
  "category": "http://w3id.org/biolink/vocab/Protein",
  "category label": "protein",
  "description": null,
  "synonym": [],
  "publications": [],
  "creation date": null,
  "update date": "2019-08-02 10:32:18 GMT",
  "deprecated": false,
  "replaced by": null,
  "provided by": "https://identifiers.org/umls/cui"
}
```

**Comment by amykglen** [comment]
it may also be worth noting that there are currently ~150k nodes with the name "Delusional disorder" in KG2 on `kg2endpoint2`:

<img width="524" alt="Screen Shot 2019-11-12 at 7 14 54 PM" src="https://user-images.githubusercontent.com/49423686/68732694-ca86b500-0580-11ea-9583-09353ae603d1.png">

while there are only 5 in the old version of KG2 on `kg2endpoint`:

<img width="480" alt="Screen Shot 2019-11-12 at 7 15 00 PM" src="https://user-images.githubusercontent.com/49423686/68732710-d3778680-0580-11ea-8a97-b56ad43e4326.png">

**Comment by saramsey** [comment]
see also #565

**Comment by amykglen** [comment]
latest update: fixing #565 resolved another 270k orphan edges... down to 600k remaining now

**Comment by dkoslicki** [comment]
@amykglen still relevant, or should we close due to #788 and ongoing KG2 dev work?

**Comment by amykglen** [comment]
I think this is still relevant (I believe there are still some orphan edges that have yet to be resolved).

**Comment by saramsey** [comment]
FYI: in work that I am doing in the `kg2-curie-refactoring` branch, I have significantly cut down the number of UMLS TTL files that are loaded in the KG2 build process according to the list in `owl-load-inventory.yaml`, from 92 TTL files in the `master` branch to 31 in the `kg2-curie-refactoring` branch. This eliminates redundancy and eliminates many concepts for which there does not exist any concept-specific web page anywhere on the Internet that we could map to with a concept-level IRI. Also, note that in the `owl-load-inventory.yaml` file, I have set the HL7 UMLS source (`umls-hl7.ttl`) to `laod_on_cuis` since that is the only way that concept-level IRIs for that ontology will resolve via `purl.bioontology.org`. In summary, this work (which is being done under issues #520 and #747) may also help to reduce the number of orphan edges. Once the work in the `kg2-curie-refactoring` branch is complete, we should reassess the number and types of orphan edges.

**Comment by saramsey** [comment]
The orphan edge situation in KG2.3.0 is looking pretty decent, with the exception of PathWhiz (for which IDK, maybe there are a bunch of nonhuman reactions that got ETL'd?)

<img width="476" alt="Screen Shot 2020-08-20 at 6 33 19 PM" src="https://user-images.githubusercontent.com/5562107/90842296-c65ba500-e313-11ea-9b0e-561ef754dfd5.png">

From the report `kg2-report-orphan-edges.json` generated on `kg2dev`

**Comment by ericawood** [comment]
The PathWhiz orphan edges are mostly because there are a lot of links to BTO and there are only some BTO nodes in KG2.

**Comment by saramsey** [comment]
> The PathWhiz orphan edges are mostly because there are a lot of links to BTO and there are only some BTO nodes in KG2.

Yes, sorry, I forgot we were already discussing this in #970.
