### ISSUE TITLE
Issues with SemMedDB and UMLSdb

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#57]
@finnagin Trying to follow the [Readme](https://github.com/RTXteam/RTX/tree/master/code/SemMedDB), I get the following:
```python
umlsdb = QueryUMLSSQL.QueryUMLSSQL('rtxdev.saramsey.org', '3306', 'rtx_read', <password>, 'umlsdb')
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-173-bfde3d52e5f6>", line 1, in <module>
    umlsdb = QueryUMLSSQL.QueryUMLSSQL('rtxdev.saramsey.org', '3306', 'rtx_read', <password>, 'umlsdb')
  File "/home/dkoslicki/Desktop/RTX/code/SemMedDB/QueryUMLSSQL.py", line 25, in __init__
    self.db = _mysql.connect(host=host,port=int(port),user = username,passwd=password,db=database)
_mysql_exceptions.OperationalError: (1044, "Access denied for user 'rtx_read'@'%' to database 'umlsdb'")
In[174]: umlsdb = QueryUMLSSQL.QueryUMLSSQL('rtxdev.saramsey.org', '3306', 'rtx_read', '<password>', 'umlsdb')
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-174-bfde3d52e5f6>", line 1, in <module>
    umlsdb = QueryUMLSSQL.QueryUMLSSQL('rtxdev.saramsey.org', '3306', 'rtx_read', '<password>', 'umlsdb')
  File "/home/dkoslicki/Desktop/RTX/code/SemMedDB/QueryUMLSSQL.py", line 25, in __init__
    self.db = _mysql.connect(host=host,port=int(port),user = username,passwd=password,db=database)
_mysql_exceptions.OperationalError: (1044, "Access denied for user 'rtx_read'@'%' to database 'umlsdb'")
```
where ``<password>`` is the one sent from Slack.

Trying ``'umlsdb'`` instead of ``'semmeddb'`` also didn't work, since then I get:
```python
umlsdb = QueryUMLSSQL.QueryUMLSSQL('rtxdev.saramsey.org', '3306', 'rtx_read', '<password>', 'semmeddb')
In[176]: umlsdb.get_cui_for_omim_id('OMIM:310837')
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-176-9baac86fd06c>", line 1, in <module>
    umlsdb.get_cui_for_omim_id('OMIM:310837')
  File "/home/dkoslicki/Desktop/RTX/code/SemMedDB/QueryUMLSSQL.py", line 95, in get_cui_for_omim_id
    df = self.get_dataframe_from_db(query)
  File "/home/dkoslicki/Desktop/RTX/code/SemMedDB/QueryUMLSSQL.py", line 33, in get_dataframe_from_db
    self.db.query(query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'semmeddb.MRCONSO' doesn't exist")

```

**Comment by finnagin** [comment]
Sorry the error comes from a typo in the readme that I just fixed. I had put the wrong port in the umls section. The correct port is 3406 not 3306. Umls and semmeddb are on different ports because umls requires and old version of mysql.

**Comment by dkoslicki** [comment]
@finnagin Yup, that fixed it! Next issue: I can't seem to get ``smdb`` to return anything:
```python
smdb.get_edges_for_cui('C1422195')
umlsdb.get_cui_for_go_id('GO:0000252')
Out[1602]: 
        CUI
0  C1151041
1  C1753299
2  C2250463
3  C2259845
4  C2259842
5  C2259843
6  C2259844
7  C2259846
8  C2259841
smdb.get_edges_for_cui('C1151041')
smdb.get_edges_for_cui('C2259844')
smdb.get_edges_for_cui('C2259846')
umlsdb.get_cui_for_hp_id('HP:0000176')
Out[1606]: 
        CUI
0  C0432103
1  C4020894
smdb.get_edges_for_cui('C4020894')
smdb.get_edges_for_cui('C0432103')
```
Note how all the ``smdb.get_edges_for_cui`` are all returning blank. Is it expected to not find that many edges? If so, can you give me a CUI for which there are edges connected?

**Comment by dkoslicki** [comment]
@finnagin Hmmm... yeah, that's a bit concerning. Keep me updated about how it goes converting to the "right" CUI.

**Comment by dkoslicki** [comment]
As this issue has been addressed, I will close it. @finnagin I'll open two separate issues regarding what we talked about today.
