### ISSUE TITLE
config.json file fails to scp

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#601]
Ran the following:
```
dkoslicki@ubuntu:~/Desktop/RTX/code/ARAX/Testing$ python test1_whatIsLovastatin.py
```
Got the following error:
```
sh: 1: pscp: not found
Traceback (most recent call last):
  File "test1_whatIsLovastatin.py", line 10, in <module>
    from RTXQuery import RTXQuery
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/Testing/../../UI/OpenAPI/python-flask-server/RTXQuery.py", line 22, in <module>
    from ParseQuestion import ParseQuestion
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 3, in <module>
    import Question
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/Question.py", line 14, in <module>
    from ReasoningUtilities import ReasoningUtilities as RU
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 35, in <module>
    import MarkovLearning
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../../reasoningtool/QuestionAnswering/MarkovLearning.py", line 15, in <module>
    rtxConfig = RTXConfiguration()
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../../RTXConfiguration.py", line 29, in __init__
    f = open(file_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/dkoslicki/Desktop/RTX/code/config.json'
```
Appears to be due to `pscp` not being on ubuntu by default [see this line](https://github.com/RTXteam/RTX/blob/1023d55278d0494644d7bbba30ad376ad0332ef6/code/RTXConfiguration.py#L20). 

Maybe need to add this in the requirements, or just switch over to scp instead of pscp.

**Comment by edeutsch** [comment]
oops, this is my unintentional commit, sorry! I have just reversed it. Please pull and try again.
Would be nice to dream a mechanism to allow a computer-specific config file that allows one to specify the local scp client.

**Comment by saramsey** [comment]
@edeutsch just curious, doesn't Win10 have OpenSSH installed?  

https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

**Comment by edeutsch** [comment]
hmm, well, I just tested on the two windows machines in front of me, and they do! So it's a mystery why scp wasn't working on the machine that I felt the need to switch scp -> pscp. Must be my home machine? I will investigate tonight. In any case, you're right, there is no need to be using pscp, so no need to have a computer-specific scp client after all. puzzling.

**Comment by dkoslicki** [comment]
Ok, appears to work now. Thanks Eric! Closing
