### ISSUE TITLE
mySQL error in ARAX tests

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#602]
Trying to get @edeutsch ARAX stubs and tests working, and running into something I haven't seen before:
```
dkoslicki@ubuntu:~/Desktop/RTX/code/ARAX/Testing$ python test1_whatIsLovastatin.py 
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-
<snip>

pymysql.err.OperationalError: (1045, "Access denied for user 'rt'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test1_whatIsLovastatin.py", line 27, in <module>
    if __name__ == "__main__": main()
  File "test1_whatIsLovastatin.py", line 23, in main
    message = rtxq.query(query)
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/Testing/../../UI/OpenAPI/python-flask-server/RTXQuery.py", line 88, in query
    cachedMessage = rtxFeedback.getCachedMessage(query)
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../Feedback/RTXFeedback.py", line 381, in getCachedMessage
    storedMessage = session.query(Message).filter(Message.query_type==query["message"]["query_type_id"]).filter(Message.tool_version==tool_version).filter(Message.terms==termsString).order_by(desc(Message.message_datetime)).first()

<snip>

  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'rt'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)
Exception ignored in: <bound method RTXFeedback.__del__ of <RTXFeedback.RTXFeedback object at 0x7ff3c1c1f160>>
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../Feedback/RTXFeedback.py", line 127, in __del__
  File "/home/dkoslicki/Desktop/RTX/code/UI/OpenAPI/python-flask-server/../../Feedback/RTXFeedback.py", line 186, in disconnect
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2027, in dispose
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 175, in recreate
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 96, in __init__
  File "<string>", line 2, in __init__
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/event/base.py", line 150, in _update
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "/home/dkoslicki/Desktop/RTX/VE36/lib/python3.6/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: (<weakref at 0x7ff35e062e08; to 'function' at 0x7ff35e0612f0 (on_connect)>,)
```

Do I need to somehow give permissions to the `rt` user? This is in my local dev environment btw.

**Comment by edeutsch** [comment]
This is what I mentioned on Friday that the API system is tied to a local MySQL server that stores and retrieves Messages. I offered to help get it set up on Friday, but it seemed like the alternative plan was to rewrite the tests so that a local MySQL instance could be avoided. I re-wrote the ARAX_Expander test to not use this system. But some of the other still do. There are several steps to getting it set up properly. Although it's not hard.

**Comment by edeutsch** [comment]
Basically the steps are this:

Install a MySQL server on localhost if needed
 
On your localhost MySQL server, create a user ‘rt’ with password xxxxxx
(see the RTXConfiguration for the correct password)
As root, run the command:
  create database rtxfeedback;
 The user rt will need write access to that database

cd G:\Repositories\GitHub\RTX\code\UI\Feedback
python3 reinitiatizeDatabase.py yes
 
- Create the node lookup table locally
cd G:\Repositories\GitHub\RTX\code\reasoningtool\kg-construction
python3 KGNodeIndex.py -b

**Comment by dkoslicki** [comment]
Thanks Eric! For onboarding/completeness, I got it to work with:
```
sudo apt update
sudo apt install mysql-server
sudo mysql
> CREATE USER 'rt'@'localhost' IDENTIFIED BY 'xxxxxxxxxxx';
>  create database rtxfeedback;
> GRANT ALL PRIVILEGES ON * . * TO 'rt'@'localhost';
> exit;
cd ~\RTX\code\UI\Feedback
python3 reinitiatizeDatabase.py yes
cd ~\RTX\code\reasoningtool\kg-construction
python3 KGNodeIndex.py -b
```
