### ISSUE TITLE
ARAX_expander throws error when path doesn't exist

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#621]
In `ARAX_query.py`, the message
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:1227, id=n00)",
            "add_qnode(type=chemical_substance, is_set=true, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "expand(edge_id=e00)",
            "return(message=true, store=true)"
 ]}}
```
runs just fine. But if you add the constraint of the edges being `physically_interacts_with` (of which there are no such edges in our KG attached to `DOID:1227`:
```
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:1227, id=n00)",
            "add_qnode(type=chemical_substance, is_set=true, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00, type=physically_interacts_with)",
            "expand(edge_id=e00)",
            "return(message=true, store=true)"
        ]}}
```
The process dies with the following:
```
DEBUG: n_nodes = 2, n_edges = 1
Traceback (most recent call last):
  File "ARAX_query.py", line 648, in <module>
    if __name__ == "__main__": main()
  File "ARAX_query.py", line 623, in main
    result = araxq.query(query)
  File "ARAX_query.py", line 78, in query
    result = self.executeProcessingPlan(query)
  File "ARAX_query.py", line 398, in executeProcessingPlan
    result = expander.apply(message,action['parameters'])
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_expander.py", line 84, in apply
    self.__merge_answer_kg_into_overarching_kg(answer_message.knowledge_graph)
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_expander.py", line 208, in __merge_answer_kg_into_overarching_kg
    answer_nodes = knowledge_graph.get('nodes')
AttributeError: 'KnowledgeGraph' object has no attribute 'get'
```
and no response is returned. Perhaps a `try,catch` with a message about no such paths existing?

**Comment by amykglen** [comment]
Ope, sorry about that - fixed it in expander branch: https://github.com/RTXteam/RTX/commit/3332cc0bb719afd4b5ae6c6fb417f9e345465532

**Comment by dkoslicki** [comment]
Thanks @amykglen !
