### ISSUE TITLE
Problem with storing messages in Feedback Database

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#642]
Storing some messages results in errors. Example, on `demo` branch, the following works just fine:
```python
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:8398, id=n00)",
            "add_qnode(type=phenotypic_feature, is_set=true, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, type=has_phenotype, id=e00)",
            "expand(edge_id=e00)",
            "return(message=true, store=true)"
        ]}}
```

But the following (while executing just fine with `store=false`) gives a ton of errors (at the end of this issue):
```python
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(name=DOID:731, id=n00, type=disease)",
            "add_qnode(type=phenotypic_feature, id=n01)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "expand(edge_id=e00)",
            'resultify(ignore_edge_direction=true)',
            "return(message=true, store=true)"]}}
```
Tried nuking the Feedback database and starting over from scratch, same issue arises.

Is there some sort of `result_code` that needs to be returned by `resultify` as indicated in this part of the error message: `pymysql.err.IntegrityError: (1048, "Column 'result_code' cannot be null")`

Full error message for the second `query example`:
```bash
$ python ARAX_query.py 17
DEBUG: n_nodes = 2, n_edges = 1
Traceback (most recent call last):
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'result_code' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ARAX_query.py", line 788, in <module>
    if __name__ == "__main__": main()
  File "ARAX_query.py", line 694, in main
    result = araxq.query(query)
  File "ARAX_query.py", line 78, in query
    result = self.executeProcessingPlan(query)
  File "ARAX_query.py", line 439, in executeProcessingPlan
    message_id = rtxFeedback.addNewMessage(message,query)
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 280, in addNewMessage
    session.flush()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2577, in _flush
    flush_context.execute()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1048, "Column 'result_code' cannot be null")
[SQL: INSERT INTO message09 (message_datetime, restated_question, query_type, terms, tool_version, result_code, message, n_results, message_object) VALUES (%(message_datetime)s, %(restated_question)s, %(query_type)s, %(terms)s, %(tool_version)s, %(result_code)s, %(message)s, %(n_results)s, %(message_object)s)]
[parameters: {'message_datetime': datetime.datetime(2020, 2, 21, 22, 32, 45, 216987), 'restated_question': '', 'query_type': 0, 'terms': '{}', 'tool_version': 'ARAX 0.6.0', 'result_code': None, 'message': 'Query returned 3223 results', 'n_results': 3223, 'message_object': b'\x80\x04\x95\x0b\x00\x01\x00\x00\x00\x00\x00}\x94(\x8c\t_datetime\x94\x8c\x132020-02-21 22:32:40\x94\x8c\x10code_description\x94\x8c\x1bQuery return ... (5042283 characters truncated) ... x8c\x12table_column_names\x94N\x8c\x05terms\x94N\x8c\x0ctool_version\x94\x8c\nARAX 0.6.0\x94\x8c\x04type\x94\x8c\x1btranslator_reasoner_message\x94u.'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by edeutsch** [comment]
result_code should be 'OK' and code_description should be some happy description about things going well, like this:
https://github.com/RTXteam/RTX/blob/02fd462816a554eeebd820cc8e8e7dcf65ae3775/code/ARAX/ARAXQuery/ARAX_messenger.py#L56

instead of being set to null like this:
https://github.com/RTXteam/RTX/blob/02fd462816a554eeebd820cc8e8e7dcf65ae3775/code/ARAX/ARAXQuery/ARAX_resultify.py#L136

They are not null in the database. I suppose we could remove the restriction, but they are not intended to be null, but rather always a reflection about the state of the Message (OK or in an ERROR state)

**Comment by dkoslicki** [comment]
Got it! So should be an relatively easy fix for @saramsey to fix in `ARAX_resultify.py` then.

**Comment by edeutsch** [comment]
I have made a partial fix that allows this to run successfully now. Pushed to demo.
However, one part is not a good fix. Need help from @saramsey to put in proper descriptions:
https://github.com/RTXteam/RTX/blob/7525d34c1e7d81d23618a2ff677e6a1cd89f23ae/code/ARAX/ARAXQuery/ARAX_resultify.py#L318

**Comment by edeutsch** [comment]
Nevermind previous post here. Better fix pushed to demo now with commit b5469372bf31f5e34d2ed964e7a1549b25076924
Still not ideal.

**Comment by saramsey** [comment]
OK, if someone can give me a clue as to what the intent of `result.description` is, I can think about how to populate it. But I am fine with `no description available` for now.

An alternative might be to just *number* the results, so the `result.description` could be like "Result number 1 of 157". Not sure if that is remotely the intent of this description field, though?

**Comment by edeutsch** [comment]
The intent of the description field is to describe the essence of the result in English. So, something like "Protein carbonic anhydrase 1 interacts with chemical substance acetaminophen according to ChEMBL" would be nice. Additional provenance would be amazing. "No description available" is fine.
