### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#65]
@dkoslicki @saramsey : I started a process to roll current code out to production. Did a git pull and restarted flask, but was stymied by this (pw changed). What's the state as far as being able to roll out to production, or at least roll out to beta?

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/QuestionTranslator.py", line 19, in <module>

    from code.reasoningtool import ReasoningUtilities as RU

ImportError: No module named 'code.reasoningtool'; 'code' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/__main__.py", line 16, in <module>

    main()

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/__main__.py", line 11, in main

    app.add_api('swagger.yaml', arguments={'title': 'RTX'})

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 73, in add_api

    resolver=resolver, resolver_error=resolver_error, pythonic_params=pythonic_params

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/abstract.py", line 168, in add_api

    pythonic_params=pythonic_params)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/flask_api.py", line 61, in __init__

    pythonic_params=pythonic_params

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 152, in __init__

    self.add_paths()

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 275, in add_paths

    self._handle_add_operation_error(path, method, sys.exc_info())

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 286, in _handle_add_operation_error

    six.reraise(*exc_info)

  File "/home/rt/.local/lib/python3.5/site-packages/six.py", line 693, in reraise

    raise value

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths

    self.add_operation(method, path, endpoint, path_parameters)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation

    pythonic_params=self.pythonic_params)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/operation.py", line 215, in __init__

    resolution = resolver.resolve(self)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 39, in resolve

    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id

    return self.function_resolver(operation_id)

  File "/home/rt/.local/lib/python3.5/site-packages/connexion/utils.py", line 27, in get_function_from_name

    module = importlib.import_module(module_name)

  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 986, in _gcd_import

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 665, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 10, in <module>

    from QuestionTranslator import QuestionTranslator

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/QuestionTranslator.py", line 24, in <module>

    import ReasoningUtilities as RU

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 26, in <module>

    import MarkovLearning

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/MarkovLearning.py", line 6, in <module>

    import Q1Utils

  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Q1Utils.py", line 23, in <module>

    driver = GraphDatabase.driver("bolt://rtxdev.saramsey.org:7887", auth=basic_auth("neo4j", "xxxx"))

  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 126, in driver

    return driver_class(uri, **config)

  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 77, in __init__

    pool.release(pool.acquire())

  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 52, in acquire

    raise ServiceUnavailable("Cannot acquire connection to {!r}".format(self.address))

neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host='rtxdev.saramsey.org', port=7887)

**Comment by saramsey** [comment]
Which branch did you pull?  I assume master?

This looks like an @dkoslicki thing.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 9:19 AM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


@dkoslicki<https://github.com/dkoslicki> @saramsey<https://github.com/saramsey> : I started a process to roll current code out to production. Did a git pull and restarted flask, but was stymied by this (pw changed). What's the state as far as being able to roll out to production, or at least roll out to beta?

File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/QuestionTranslator.py", line 19, in

from code.reasoningtool import ReasoningUtilities as RU


ImportError: No module named 'code.reasoningtool'; 'code' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main

"__main__", mod_spec)


File "/usr/lib/python3.5/runpy.py", line 85, in _run_code

exec(code, run_globals)


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/main.py", line 16, in

main()


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/main.py", line 11, in main

app.add_api('swagger.yaml', arguments={'title': 'RTX'})


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 73, in add_api

resolver=resolver, resolver_error=resolver_error, pythonic_params=pythonic_params


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apps/abstract.py", line 168, in add_api

pythonic_params=pythonic_params)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/flask_api.py", line 61, in init

pythonic_params=pythonic_params


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 152, in init

self.add_paths()


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 275, in add_paths

self._handle_add_operation_error(path, method, sys.exc_info())


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 286, in _handle_add_operation_error

six.reraise(*exc_info)


File "/home/rt/.local/lib/python3.5/site-packages/six.py", line 693, in reraise

raise value


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths

self.add_operation(method, path, endpoint, path_parameters)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation

pythonic_params=self.pythonic_params)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/operation.py", line 215, in init

resolution = resolver.resolve(self)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 39, in resolve

return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id

return self.function_resolver(operation_id)


File "/home/rt/.local/lib/python3.5/site-packages/connexion/utils.py", line 27, in get_function_from_name

module = importlib.import_module(module_name)


File "/usr/lib/python3.5/importlib/init.py", line 126, in import_module

return _bootstrap._gcd_import(name[level:], package, level)


File "", line 986, in _gcd_import

File "", line 969, in _find_and_load

File "", line 958, in _find_and_load_unlocked

File "", line 673, in _load_unlocked

File "", line 665, in exec_module

File "", line 222, in _call_with_frames_removed

File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 10, in

from QuestionTranslator import QuestionTranslator


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/QuestionTranslator.py", line 24, in

import ReasoningUtilities as RU


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 26, in

import MarkovLearning


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/MarkovLearning.py", line 6, in

import Q1Utils


File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Q1Utils.py", line 23, in

driver = GraphDatabase.driver("bolt://rtxdev.saramsey.org:7887", auth=basic_auth("neo4j", "xxxx"))


File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 126, in driver

return driver_class(uri, **config)


File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 77, in init

pool.release(pool.acquire())


File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 52, in acquire

raise ServiceUnavailable("Cannot acquire connection to {!r}".format(self.address))


neo4j.exceptions.ServiceUnavailable: Cannot acquire connection to Address(host='rtxdev.saramsey.org<http://rtxdev.saramsey.org>', port=7887)

**Comment by dkoslicki** [comment]
@edeutsch I think this is due to the container at ``rtxdev.saramsey.org:7674`` not being up at the moment.
@saramsey Can we push the KG at ``rtxdev.saramsey.org:7674`` to ``rtx.ncats.io:7473``? I prefer the production code point to a KG neo4j that's always up and running. I can then change all the code to point to ``rtx.ncats`` so we don't have this issue in the future.

**Comment by saramsey** [comment]
@edeutsch OK to do this now?  This will involve bouncing neo4j on rtx.ncats.io and a few minutes of down-time.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 9:39 AM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@edeutsch<https://github.com/edeutsch> I think this is due to the container at rtxdev.saramsey.org<http://rtxdev.saramsey.org>:7674 not being up at the moment.
@saramsey<https://github.com/saramsey> Can we push the KG at rtxdev.saramsey.org<http://rtxdev.saramsey.org>:7674 to rtx.ncats.io:7473? I prefer the production code point to a KG neo4j that's always up and running. I can then change all the code to point to rtx.ncats so we don't have this issue in the future.

**Comment by saramsey** [comment]
I’ve added this to the agenda as item #7

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 10:25 AM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> maybe best to chat about it at 12 and then make a plan? I am guessing that production will break and remain broken until all issues are smoothed out?

There are some import errors that I might need @dkoslicki<https://github.com/dkoslicki> help when we do this

**Comment by dkoslicki** [comment]
@saramsey are these the correct neo4j connections to be using?
```
http://neo4j:<password>@rtx.ncats.io:7473/db/data
bolt://rtx.ncats.io:7687
```
i.e. does this KG contain the changes coming from the newkg code?

**Comment by saramsey** [comment]
Yes, it seems so:

[cid:74AFE1F5-57E5-403D-97F2-11CFA581FE2F]

Are you seeing any missing stuff or any weirdness, on your end?

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 1:06 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> are these the correct neo4j connections to be using?

http://neo4j:<password>@rtx.ncats.io:7473/db/data
bolt://rtx.ncats.io:7687


i.e. does this KG contain the changes coming from the newkg code?

**Comment by dkoslicki** [comment]
No missing stuff or weirdness, just double checking before pushing to master

**Comment by dkoslicki** [comment]
@edeutsch Ok, the code has been fixed to point at ``rtx.ncats.io`` and has been tested. All tests passing on my end.  Pull, bounce, and let me know if it integrates with the UI and we can close this issue.

I always forget to reference the issue in the commit, but see commit 06ae149d9009735bcdefef5c4ed24560db11d0e9

**Comment by edeutsch** [comment]
@dkoslicki : Did a git pull and bounced the server but get this when invoking the API translate:

[2018-04-16 21:12:17,338] ERROR in app: Exception on /test/api/rtx/v1/translate [POST]
Traceback (most recent call last):
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rt/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rt/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 122, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 293, in wrapper
    return function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/home/rt/.local/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 25, in translate
    txltr = QuestionTranslator()
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/QuestionTranslator.py", line 88, in __init__
    for line in fid.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 6827: ordinal not in range(128)

Ideas on this? I'm not sure what to make of this.

**Comment by dkoslicki** [comment]
@edeutsch I think this may be due to us moving to ``ParseQuestion.py`` to handle the question translation now. As per #52. ``QuestionTranslator.py`` should be depreciated in favor of ``ParseQuestion.py``
(and curiously, I don't get that error on my end)

**Comment by edeutsch** [comment]
ah, okay. I'm a bit confused why I don't have ParseQuestion.py

**Comment by dkoslicki** [comment]
Don't have it as in "can't find the code" or as in "it's not in my translate_controller.py"? May be due to ParseQuestion.py being fully implemented just before you left for vacation (so easy to fall off the mental stack).

**Comment by edeutsch** [comment]
as in "it's not in my translate_controller.py".
My mental stack just tipped over and is scattered about on the floor around my feet..

**Comment by edeutsch** [comment]
@dkoslicki : I just tried switching to ParseQuestion, but seem to get the same result:
...
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 10, in <module>
    from ParseQuestion import ParseQuestion
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 3, in <module>
    import Question
  File "/mnt/data/orangeboard/test/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Question.py", line 39, in <module>
    for line in fid.readlines():
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 6827: ordinal not in range(128)

**Comment by edeutsch** [comment]
Looks like Python on rtx is having a cow on this line:
R-HSA-9027604   Biosynthesis of electrophilic ω-3 PUFA oxo-derivatives
in NodeNamesDescriptions.tsv
I suspect that omega is causing the problem.

**Comment by dkoslicki** [comment]
Yeah, that's really odd. On my machine, that doesn't throw any errors:
```python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ParseQuestion
>>> import Question
>>> 
```

**Comment by dkoslicki** [comment]
Do these help?
https://stackoverflow.com/questions/35028683/python3-unicodedecodeerror-with-readlines-method
https://stackoverflow.com/questions/10487563/unicode-error-handling-with-python-3s-readlines

The ``readlines`` isn't causing errors on my machine, so I cant help, but it seems a combination of ``encodings`` and ``errors`` in the ``readlines`` should fix this.

**Comment by dkoslicki** [comment]
@edeutsch If it helps, replacing [line 34](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/Question.py#L34) in ``Question.py`` with:
```python
fid = open(os.path.dirname(os.path.abspath(__file__))+'/../../../data/KGmetadata/NodeNamesDescriptions.tsv', 'r', encoding='utf-8', errors='ignore')
```
results on no errors on my end (and may fix the issue on yours).

**Comment by dkoslicki** [comment]
``errors='replace'`` also works on my end

**Comment by dkoslicki** [comment]
ah ha! But replacing it with ``encoding=ascii`` does throw the error you're seeing. I've pushed a fix to master, so it 'should' work now...
