### ISSUE TITLE
Inconsistent connection errors from www.uniprot.org triggered by running Example 3

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#679]
Folks, when I run Example 3 on my MBP, I'm getting timeout errors from www.uniprot.org. Here is the exact Example 3 code I am running:
```
def _do_arax_query(query: str) -> List[Union[Response, Message]]:
    from ARAX_query import ARAXQuery
    araxq = ARAXQuery()
    response = araxq.query(query)
    return [response, araxq.message]

def _test_example3():
    query = {"previous_message_processing_plan": {"processing_actions": [
        "add_qnode(name=DOID:9406, id=n00)",
        "add_qnode(type=chemical_substance, is_set=true, id=n01)",
        "add_qnode(type=protein, id=n02)",
        "add_qedge(source_id=n00, target_id=n01, id=e00)",
        "add_qedge(source_id=n01, target_id=n02, id=e01)",
        "expand(edge_id=[e00,e01])",
        "overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)",
        "filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=3, remove_connected_nodes=t, qnode_id=n01)",
        "filter_kg(action=remove_orphaned_nodes, node_type=protein)",
        "overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n01, target_qnode_id=n02)",
        "filter_kg(action=remove_edges_by_attribute, edge_attribute=ngd, direction=above, threshold=0.85, remove_connected_nodes=t, qnode_id=n02)",
        "resultify(ignore_edge_direction=true, debug=true)",
        "return(message=true, store=true)"
    ]}}
    [response, message] = _do_arax_query(query)
    assert response.status == 'OK'
    print(str(len(message.results)))
    assert message.results[0].essence is not None

```
and here is it's response (after hanging for a long time):

```
Traceback (most recent call last):
  File "ARAX_resultify.py", line 1315, in <module>
    main()
  File "ARAX_resultify.py", line 1308, in main
    globals()[func_name]()
  File "ARAX_resultify.py", line 1281, in _test_example3
    [response, message] = _do_arax_query(query)
  File "ARAX_resultify.py", line 521, in _do_arax_query
    response = araxq.query(query)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/ARAX/ARAXQuery/ARAX_query.py", line 80, in query
    result = self.executeProcessingPlan(query)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/ARAX/ARAXQuery/ARAX_query.py", line 407, in executeProcessingPlan
    result = overlay.apply(message, action['parameters'])
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/ARAX/ARAXQuery/ARAX_overlay.py", line 135, in apply
    getattr(self, '_' + self.__class__.__name__ + '__' + parameters['action'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/ARAX/ARAXQuery/ARAX_overlay.py", line 210, in __compute_ngd
    response = NGD.compute_ngd()
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/ARAX/ARAXQuery/Overlay/compute_ngd.py", line 81, in compute_ngd
    ngd_value = self.NGD.get_ngd_for_all_fast([source_curie, target_curie], [source_name, target_name])
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 88, in get_ngd_for_all_fast
    return NormGoogleDistance.get_ngd_for_all(curie_id_list, description_list)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 251, in get_ngd_for_all
    terms[a] = NormGoogleDistance.get_mesh_term_for_all(curie_id_list[a], description_list[a])
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 176, in get_mesh_term_for_all
    res = QueryNCBIeUtils.get_uniprot_names(curie_list[1])
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 557, in get_uniprot_names
    r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})  # send get request
  File "/Users/sramsey/Work/Proj/ncats-translator/git-demo/code/reasoningtool/kg-construction/cache_control_helper.py", line 39, in get
    return self.sess.get(url, params=params, timeout=timeout, headers=headers)
  File "/Users/sramsey/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_cache/core.py", line 126, in request
    **kwargs
  File "/Users/sramsey/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/usr/local/lib/python3.7/site-packages/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/Users/sramsey/Library/Python/3.7/lib/python/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/sramsey/Library/Python/3.7/lib/python/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uniprot/?query=id:P28845&sort=score&columns=entry%20name,protein%20names,genes&format=tab (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x12c523a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```
I'm currently unable to test whether or not the newfangled essence capability in `ARAX_resultify.py` will work with Example 3.

**Comment by saramsey** [comment]
Ah, it just worked!  Kind of a heisenbug, LOL. But the API calls to uniprot are now cached so I am a happy camper for the purposes of testing. Marking this lowpri.

**Comment by dkoslicki** [comment]
Yeah, that's odd. I have never run into those errors before and can't reproduce. Hence the importance of pre-running (many times?) the examples on whatever backend is doing the demo of the iPython notebooks.

**Comment by dkoslicki** [comment]
@saramsey Still an issue? Or close due to #788?

**Comment by dkoslicki** [comment]
@finnagin Can you update the ARAXi to the modern version, run it and check if executes correctly? If so, this can be closed
