### ISSUE TITLE
edge attribute types cause weird errors

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#701]
In `ARAX_query.py` if `"overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)"` with
`overlay_clinical_info.py` line 188:
```python
edge_attribute = EdgeAttribute(type=type, name=name, value=value, url=url)
```
Get the error:
```
Traceback (most recent call last):
  File "ARAX_query.py", line 1055, in <module>
    if __name__ == "__main__": main()
  File "ARAX_query.py", line 850, in main
    result = araxq.query(query)
  File "ARAX_query.py", line 83, in query
    result = self.executeProcessingPlan(query)
  File "ARAX_query.py", line 461, in executeProcessingPlan
    message_id = rtxFeedback.addNewMessage(message,query)
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 278, in addNewMessage
    terms=termsString,tool_version=rtxConfig.version,result_code=message.message_code,message=message.code_description,n_results=n_results,message_object=pickle.dumps(ast.literal_eval(repr(message))))
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 96, in literal_eval
    return _convert(node_or_string)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 85, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 85, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 81, in _convert
    return list(map(_convert, node.elts))
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 85, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 81, in _convert
    return list(map(_convert, node.elts))
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 85, in _convert
    return dict(zip(map(_convert, node.keys),
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 95, in _convert
    return _convert_signed_num(node)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 69, in _convert_signed_num
    operand = _convert_num(node.operand)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/ast.py", line 66, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7f0519d9c1c0>
```
Eric suggest issue has to do with `message_object=pickle.dumps(ast.literal_eval(repr(message))))`
No error when:
`overlay_clinical_info.py` line 188:
```python
edge_attribute = EdgeAttribute(type=type, name=name, value=str(value), url=url)
```

Curiously, with Jaccard index the edge attribute `value` is a float, and this causes no `ast.py` issues.

**Comment by edeutsch** [comment]
Is it possible that with the Jaccard index you're doing:
edge_attribute = { "type": "float", "name": "foo", "value": 0.222 }
?
i.e. difference between creating an object vs. a dict?

**Comment by dkoslicki** [comment]
With Jaccard, I am doing:
```python
edge_attribute = EdgeAttribute(type=attribute_type, name=name, value=value, url=url)
<snip>
edge = Edge(id=id, type=edge_type, relation=relation, source_id=source_id, target_id=target_id,
                      is_defined_by=is_defined_by, defined_datetime=defined_datetime, provided_by=provided_by,
                      confidence=confidence, weight=weight, edge_attributes=[edge_attribute], qedge_id=qedge_id)
message.knowledge_graph.edges.append(edge)
```
where `value.__class__ == float` and the class `EdgeAttribute` comes from 
```
from swagger_server.models.edge_attribute import EdgeAttribute
```

In `overlay_clinical_info`, I am doing:
```python
<snip>
edge_attribute = EdgeAttribute(type=type, name=name, value=value, url=url)
edge = Edge(id=id, type=edge_type, relation=relation, source_id=source_id,
                            target_id=target_id,
                            is_defined_by=is_defined_by, defined_datetime=defined_datetime,
                            provided_by=provided_by,
                            confidence=confidence, weight=weight, edge_attributes=[edge_attribute], qedge_id=qedge_id)
self.message.knowledge_graph.edges.append(edge)
```
where again `value.__class__ == float`.

So basically the same exact thing (i.e. using the object model). Hence the mystery.

**Comment by edeutsch** [comment]
yeah, baffling. well, my Python skills at this sort of thing are way behind yours, so I'm of no help. All I can think of it trying the pickle.dumps() right here in the code and see if you can trace it there.

Oh, I will also add that I once tried upgrading to Python 3.8 on one machine and bad weird  things started happening, so I scurried back to 3.7 and all was well. You might consider running on the latest 3.7. All my instances are 3.7. I see you're 3.8.

**Comment by dkoslicki** [comment]
Closing due to #788 and some previous issue whose number I can’t recall that says to use python 3.7.x
