### ISSUE TITLE
NGD broken on KG2

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#704]
DSL command:
```python
query = { "previous_message_processing_plan": { "processing_actions": [
            "create_message",
            #"add_qnode(id=n00, curie=DOID:0050156)",  # idiopathic pulmonary fibrosis
            "add_qnode(curie=DOID:9406, id=n00)",  # hypopituitarism, original demo example
            "add_qnode(id=n01, type=chemical_substance, is_set=true)",
            "add_qnode(id=n02, type=protein)",
            "add_qedge(id=e00, source_id=n00, target_id=n01)",
            "add_qedge(id=e01, source_id=n01, target_id=n02)",
            "expand(edge_id=[e00,e01], kp=ARAX/KG2)",
            "overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)",
            "overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n01, target_qnode_id=n02)",
            "return(message=true, store=false)",
            ] } }
```

```bash
$ python ARAX_query.py 203
Response:
  status: ERROR
  n_errors: 1  n_warnings: 0  n_messages: 67
  error_code: UncaughtARAXiError   message: An uncaught error occurred: list index out of range: ['Traceback (most recent call last):\n', '  File "ARAX_query.py", line 416, in executeProcessingPlan\n    result = overlay.apply(message, action[\'parameters\'])\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 137, in apply\n    getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 212, in __compute_ngd\n    response = NGD.compute_ngd()\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/Overlay/compute_ngd.py", line 81, in compute_ngd\n    ngd_value = self.NGD.get_ngd_for_all_fast([source_curie, target_curie], [source_name, target_name])\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 88, in get_ngd_for_all_fast\n    return NormGoogleDistance.get_ngd_for_all(curie_id_list, description_list)\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 274, in get_ngd_for_all\n    ngd = QueryNCBIeUtils.multi_normalized_google_distance(terms_combined, mesh_flags)\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 433, in multi_normalized_google_distance\n    if type(counts[1]) == str:\n', 'IndexError: list index out of range\n']
  - 2020-04-09 15:55:19.217740 INFO: ARAXQuery launching
  - 2020-04-09 15:55:19.217753 INFO: Examine input query for needed information for dispatch
  - 2020-04-09 15:55:19.217757 INFO: Found input processing plan. Sending to the ProcessingPlanExecutor
  - 2020-04-09 15:55:19.217760 DEBUG: Entering executeProcessingPlan
  - 2020-04-09 15:55:19.230383 DEBUG: No starting messages were referenced. Will start with a blank template Message
  - 2020-04-09 15:55:19.230602 DEBUG: Found processing_actions
  - 2020-04-09 15:55:19.230611 INFO: Parsing input actions list
  - 2020-04-09 15:55:19.230614 DEBUG: Parsing action: create_message
  - 2020-04-09 15:55:19.230767 DEBUG: Parsing action: add_qnode(curie=DOID:9406, id=n00)
  - 2020-04-09 15:55:19.230959 DEBUG: Parsing action: add_qnode(id=n01, type=chemical_substance, is_set=true)
  - 2020-04-09 15:55:19.230973 DEBUG: Parsing action: add_qnode(id=n02, type=protein)
  - 2020-04-09 15:55:19.230982 DEBUG: Parsing action: add_qedge(id=e00, source_id=n00, target_id=n01)
  - 2020-04-09 15:55:19.230992 DEBUG: Parsing action: add_qedge(id=e01, source_id=n01, target_id=n02)
  - 2020-04-09 15:55:19.231002 DEBUG: Parsing action: expand(edge_id=[e00,e01], kp=ARAX/KG2)
  - 2020-04-09 15:55:19.231099 DEBUG: Parsing action: overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_edge_type=C1, source_qnode_id=n00, target_qnode_id=n01)
  - 2020-04-09 15:55:19.231114 DEBUG: Parsing action: overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n01, target_qnode_id=n02)
  - 2020-04-09 15:55:19.231126 DEBUG: Parsing action: return(message=true, store=false)
  - 2020-04-09 15:55:19.231880 DEBUG: Processing action 'create_message' with parameters None
  - 2020-04-09 15:55:19.231888 INFO: Creating an empty template ARAX Message
  - 2020-04-09 15:55:19.232004 DEBUG: Processing action 'add_qnode' with parameters {'curie': 'DOID:9406', 'id': 'n00'}
  - 2020-04-09 15:55:19.232014 INFO: Adding a QueryNode to Message with parameters {'id': 'n00', 'curie': 'DOID:9406', 'name': None, 'type': None, 'is_set': None}
  - 2020-04-09 15:55:19.232281 DEBUG: Looking up CURIE DOID:9406 in KgNodeIndex
  - 2020-04-09 15:55:19.232663 DEBUG: Processing action 'add_qnode' with parameters {'id': 'n01', 'type': 'chemical_substance', 'is_set': 'true'}
  - 2020-04-09 15:55:19.232674 INFO: Adding a QueryNode to Message with parameters {'id': 'n01', 'curie': None, 'name': None, 'type': 'chemical_substance', 'is_set': 'true'}
  - 2020-04-09 15:55:19.232749 DEBUG: Processing action 'add_qnode' with parameters {'id': 'n02', 'type': 'protein'}
  - 2020-04-09 15:55:19.232758 INFO: Adding a QueryNode to Message with parameters {'id': 'n02', 'curie': None, 'name': None, 'type': 'protein', 'is_set': None}
  - 2020-04-09 15:55:19.232816 DEBUG: Processing action 'add_qedge' with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01'}
  - 2020-04-09 15:55:19.232826 INFO: Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': None}
  - 2020-04-09 15:55:19.232845 DEBUG: Processing action 'add_qedge' with parameters {'id': 'e01', 'source_id': 'n01', 'target_id': 'n02'}
  - 2020-04-09 15:55:19.232851 INFO: Adding a QueryEdge to Message with parameters {'id': 'e01', 'source_id': 'n01', 'target_id': 'n02', 'type': None}
  - 2020-04-09 15:55:19.232859 DEBUG: Processing action 'expand' with parameters {'edge_id': ['e00', 'e01'], 'kp': 'ARAX/KG2'}
  - 2020-04-09 15:55:19.232865 DEBUG: Applying Expand to Message with parameters {'edge_id': ['e00', 'e01'], 'kp': 'ARAX/KG2'}
  - 2020-04-09 15:55:19.232868 INFO: Beginning expansion of edges e00, e01 using ARAX/KG2
  - 2020-04-09 15:55:19.232872 DEBUG: Extracting sub query graph to expand
  - 2020-04-09 15:55:19.232957 DEBUG: Query graph to expand is: {'nodes': [{'id': 'n00', 'curie': 'DOID:9406', 'type': 'disease', 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'chemical_substance', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'protein', 'is_set': None}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}, {'id': 'e01', 'type': None, 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
  - 2020-04-09 15:55:19.232967 INFO: Expanding edge e00
  - 2020-04-09 15:55:19.233747 DEBUG: Sending edge query graph to KG2Querier: {'nodes': [{'id': 'n00', 'curie': 'DOID:9406', 'type': 'disease', 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'chemical_substance', 'is_set': True}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}]}
  - 2020-04-09 15:55:19.233754 DEBUG: Looking for curie synonyms to use
  - 2020-04-09 15:55:19.234206 INFO: Using equivalent curies for node DOID:9406: ['CUI:C0020635', 'CHV:0000006487', 'HPO:HP%3A0040075', 'ICD10:E23.0', 'CUI:C2874189', 'CUI:C2874188', 'CUI:C2874190', 'ICD10CM:E23.0', 'MEDDRA:10021067', 'MEDCIN:30497', 'MESH:D007018', 'CUI:C4553969', 'NCIT:C62591', 'NCI_CTCAE_5:C143194', 'NCI_NICHD:C62591', 'OMIM:MTHU036880', 'SNOMEDCT:74728003', 'EFO:0001380', 'HP:0040075', 'MONDO:0005152', 'DOID:9406']
  - 2020-04-09 15:55:19.234243 DEBUG: Generating cypher for edge e00 query graph
  - 2020-04-09 15:55:19.234258 INFO: Sending cypher query for edge e00 to KG2 neo4j
  - 2020-04-09 15:55:25.688557 INFO: Query for edge e00 returned results (nodes_n00: 4, nodes_n01: 40, edges_e00: 72)
  - 2020-04-09 15:55:25.689007 DEBUG: Processing query results for edge e00
  - 2020-04-09 15:55:25.695971 DEBUG: Merging results into Message.KnowledgeGraph
  - 2020-04-09 15:55:25.696005 INFO: Expanding edge e01
  - 2020-04-09 15:55:25.696129 DEBUG: Sending edge query graph to KG2Querier: {'nodes': [{'id': 'n01', 'curie': ['CUI:C0015688', 'CUI:C0031705', 'CUI:C0026162', 'CUI:C0071505', 'CUI:C0450442', 'CHEMBL.COMPOUND:CHEMBL472', 'CHEMBL.COMPOUND:CHEMBL498', 'CHEMBL.COMPOUND:CHEMBL595', 'CHEMBL.COMPOUND:CHEMBL121', 'CHEMBL.COMPOUND:CHEMBL131', 'CHEMBL.COMPOUND:CHEMBL632', 'CHEMBL.COMPOUND:CHEMBL635', 'CHEMBL.COMPOUND:CHEMBL650', 'CHEMBL.COMPOUND:CHEMBL671', 'CHEMBL.COMPOUND:CHEMBL782', 'CHEMBL.COMPOUND:CHEMBL783', 'CHEMBL.COMPOUND:CHEMBL817', 'CHEMBL.COMPOUND:CHEMBL1073', 'CHEMBL.COMPOUND:CHEMBL1110', 'CHEMBL.COMPOUND:CHEMBL1263', 'CHEMBL.COMPOUND:CHEMBL1272', 'CHEMBL.COMPOUND:CHEMBL1370', 'CHEMBL.COMPOUND:CHEMBL1399', 'CHEMBL.COMPOUND:CHEMBL385517', 'CHEMBL.COMPOUND:CHEMBL389621', 'CHEMBL.COMPOUND:CHEMBL1422', 'CHEMBL.COMPOUND:CHEMBL386630', 'CHEMBL.COMPOUND:CHEMBL384467', 'CHEMBL.COMPOUND:CHEMBL1451', 'CHEMBL.COMPOUND:CHEMBL1431', 'CHEMBL.COMPOUND:CHEMBL1473', 'CHEMBL.COMPOUND:CHEMBL1481', 'CHEMBL.COMPOUND:CHEMBL1501', 'CHEMBL.COMPOUND:CHEMBL1504', 'CHEMBL.COMPOUND:CHEMBL1544', 'CHEMBL.COMPOUND:CHEMBL1624', 'CHEMBL.COMPOUND:CHEMBL1766', 'CHEMBL.COMPOUND:CHEMBL1201621', 'CHEMBL.COMPOUND:CHEMBL1201109', 'CHEMBL.COMPOUND:CHEMBL1201392'], 'type': 'chemical_substance', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'protein', 'is_set': None}], 'edges': [{'id': 'e01', 'type': None, 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
  - 2020-04-09 15:55:25.696134 DEBUG: Looking for curie synonyms to use
  - 2020-04-09 15:55:25.696262 DEBUG: Generating cypher for edge e01 query graph
  - 2020-04-09 15:55:25.696289 INFO: Sending cypher query for edge e01 to KG2 neo4j
  - 2020-04-09 15:55:30.636457 INFO: Query for edge e01 returned results (nodes_n01: 40, nodes_n02: 759, edges_e01: 2868)
  - 2020-04-09 15:55:30.636895 DEBUG: Processing query results for edge e01
  - 2020-04-09 15:55:30.816090 DEBUG: Merging results into Message.KnowledgeGraph
  - 2020-04-09 15:55:30.817361 INFO: After Expand, Message.KnowledgeGraph has 803 nodes and 2940 edges
  - 2020-04-09 15:55:30.817621 DEBUG: Processing action 'overlay' with parameters {'action': 'overlay_clinical_info', 'observed_expected_ratio': 'true', 'virtual_edge_type': 'C1', 'source_qnode_id': 'n00', 'target_qnode_id': 'n01'}
  - 2020-04-09 15:55:30.818520 INFO: Converting CURIE identifiers to human readable names
  - 2020-04-09 15:55:30.819016 DEBUG: Computing observed expected ratios.
  - 2020-04-09 15:55:30.819022 INFO: Overlaying observed expected ratios utilizing Columbia Open Health Data. This calls an external knowledge provider and may take a while
  - 2020-04-09 15:55:42.620650 DEBUG: Applying Overlay to Message with parameters {'action': 'overlay_clinical_info', 'observed_expected_ratio': 'true', 'virtual_edge_type': 'C1', 'source_qnode_id': 'n00', 'target_qnode_id': 'n01'}
  - 2020-04-09 15:55:42.620972 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'observed_expected_ratio',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'C1'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-04-09 15:55:42.620981 DEBUG: Number of nodes in KG is 803
  - 2020-04-09 15:55:42.621428 DEBUG: Number of nodes in KG by type is Counter({'protein': 759, 'chemical_substance': 40, 'disease': 2, 'phenotypic_feature': 1, 'named_thing': 1})
  - 2020-04-09 15:55:42.621436 DEBUG: Number of edges in KG is 3060
  - 2020-04-09 15:55:42.622807 DEBUG: Number of edges in KG by type is Counter({'molecularly_interacts_with': 1620, 'related_to': 346, 'affects': 279, 'interacts_with': 223, 'positively_regulates': 144, 'inhibits': 124, 'C1': 120, 'contraindicated_with': 60, 'agonist': 43, 'produces': 29, 'equivalent_to': 28, 'directly_interacts_with': 18, 'causes_or_contributes_to': 6, 'antagonist': 6, 'is_substance_that_treats': 4, 'derives_into': 4, 'subclass_of': 2, 'activates': 2, 'part_of': 1, 'regulates': 1})
  - 2020-04-09 15:55:42.623762 DEBUG: Number of edges in KG with attributes is 3060
  - 2020-04-09 15:55:42.626603 DEBUG: Number of edges in KG by attribute Counter({'relation_curie': 2940, 'simplified_relation_curie': 2940, 'simplified_relation': 2940, 'edge_label': 2940, 'observed_expected_ratio': 120})
  - 2020-04-09 15:55:42.626627 DEBUG: Processing action 'overlay' with parameters {'action': 'compute_ngd', 'virtual_edge_type': 'N1', 'source_qnode_id': 'n01', 'target_qnode_id': 'n02'}
  - 2020-04-09 15:56:31.972958 ERROR: An uncaught error occurred: list index out of range: ['Traceback (most recent call last):\n', '  File "ARAX_query.py", line 416, in executeProcessingPlan\n    result = overlay.apply(message, action[\'parameters\'])\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 137, in apply\n    getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 212, in __compute_ngd\n    response = NGD.compute_ngd()\n', '  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/Overlay/compute_ngd.py", line 81, in compute_ngd\n    ngd_value = self.NGD.get_ngd_for_all_fast([source_curie, target_curie], [source_name, target_name])\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 88, in get_ngd_for_all_fast\n    return NormGoogleDistance.get_ngd_for_all(curie_id_list, description_list)\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 274, in get_ngd_for_all\n    ngd = QueryNCBIeUtils.multi_normalized_google_distance(terms_combined, mesh_flags)\n', '  File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 433, in multi_normalized_google_distance\n    if type(counts[1]) == str:\n', 'IndexError: list index out of range\n']

Exception ignored in: <function RTXFeedback.__del__ at 0x7f568eb4c040>
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 127, in __del__
    self.disconnect()
  File "/home/dkoslicki/Desktop/RTX/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 187, in disconnect
    engine.dispose()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2030, in dispose
    self.pool = self.pool.recreate()
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 164, in recreate
    return self.__class__(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 96, in __init__
    Pool.__init__(self, creator, **kw)
  File "<string>", line 2, in __init__
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
    self.dispatch._update(_dispatch, only_propagate=False)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 149, in _update
    getattr(self, ls.name).for_modify(self)._update(
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 392, in _update
    registry._stored_in_collection_multi(self, other, to_associate)
  File "/home/dkoslicki/anaconda3/envs/RTX/lib/python3.8/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
    key = old_listener_to_key[listen_ref]
KeyError: <weakref at 0x7f568ea404a0; to 'function' at 0x7f568ea34550 (on_connect)>
```

Underlying error is:
```
File "/home/dkoslicki/Desktop/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 433, in multi_normalized_google_distance\n    if type(counts[1]) == str:\n', 'IndexError: list index out of range\n']
```
So might be a @finnagin issue as the problem is in the `multi_normalized_google_distance`, but it could also be my code not passing the right thing.

Sub-issue of #698

**Comment by finnagin** [comment]
When testing this try running Q14 from this document:

https://docs.google.com/document/d/18bbeTlkH-sdeDqqyl8ZFzBHyZSkg8awuUec1H_kff8c/edit#heading=h.20f2iwmjfj5i

**Comment by saramsey** [comment]
Hey @finnagin can you comment -- do you think this is a KG2 issue or a NGD code issue?

**Comment by finnagin** [comment]
@saramsey after looking into this I think it is a ngd code issue. It looks like NCBIeutils changed how they displayed an error message which caused a bug in the ngd code. I'm testing a fix to see if that was indeed what was causing the issue.

**Comment by finnagin** [comment]
So I got it to get past the original ngd error and it ran for a few hours until it hit a new error:

Response:
  status: ERROR
  n_errors: 1  n_warnings: 0  n_messages: 67
  error_code: UncaughtARAXiError   message: An uncaught error occurred: unable to open database file:

Traceback (most recent call last):

  File "ARAX_query.py", line 414, in executeProcessingPlan
    result = overlay.apply(message, action['parameters'])

  File "/home/finn/Documents/rtx_clone/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 135, in apply
    getattr(self, '_' + self.__class__.__name__ + '__' + parameters['action'])()  # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string

  File "/home/finn/Documents/rtx_clone/RTX/code/ARAX/ARAXQuery/ARAX_overlay.py", line 210, in __compute_ngd
    response = NGD.compute_ngd()

  File "/home/finn/Documents/rtx_clone/RTX/code/ARAX/ARAXQuery/Overlay/compute_ngd.py", line 81, in compute_ngd
    ngd_value = self.NGD.get_ngd_for_all_fast([source_curie, target_curie], [source_name, target_name])

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 88, in get_ngd_for_all_fast
    return NormGoogleDistance.get_ngd_for_all(curie_id_list, description_list)

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 251, in get_ngd_for_all
    terms[a] = NormGoogleDistance.get_mesh_term_for_all(curie_id_list[a], description_list[a])

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 167, in get_mesh_term_for_all
    names = NormGoogleDistance.get_mesh_from_oxo(curie_id)

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 122, in get_mesh_from_oxo
    res = NormGoogleDistance.query_oxo(curie_id)

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 100, in query_oxo
    res = requests.get(url_str, headers={'accept': 'application/json'}, timeout=120)

  File "/home/finn/Documents/rtx_clone/RTX/code/reasoningtool/kg-construction/cache_control_helper.py", line 39, in get
    return self.sess.get(url, params=params, timeout=timeout, headers=headers)

  File "/home/finn/.local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/core.py", line 136, in request
    **kwargs

  File "/home/finn/.local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/core.py", line 109, in send
    return send_request_and_cache_response()

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/core.py", line 99, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/backends/base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/backends/storage/dbdict.py", line 166, in __setitem__
    sqlite.Binary(pickle.dumps(item)))

  File "/home/finn/.local/lib/python3.7/site-packages/requests_cache/backends/storage/dbdict.py", line 130, in __setitem__
    self.table_name, (key, item))

sqlite3.OperationalError: unable to open database file

**Comment by dkoslicki** [comment]
Any update on this @finnagin?

**Comment by finnagin** [comment]
@dkoslicki I've merged expander into filter and everything seems to be working with ngd.

**Comment by finnagin** [comment]
Though when I run the Q14 example I get the following error message:
```
Response:
  status: ERROR
  n_errors: 1  n_warnings: 0  n_messages: 53
  error_code: MultipleQGIDs   message: Node DOID:13636 has been returned as an answer for multiple query graph nodes (n02 and n00)
  - 2020-04-24 02:39:50.839526 INFO: ARAXQuery launching
  - 2020-04-24 02:39:50.839541 INFO: Examine input query for needed information for dispatch
  - 2020-04-24 02:39:50.839545 INFO: Found input processing plan. Sending to the ProcessingPlanExecutor
  - 2020-04-24 02:39:50.839549 DEBUG: Entering executeProcessingPlan
  - 2020-04-24 02:39:51.013219 DEBUG: No starting messages were referenced. Will start with a blank template Message
  - 2020-04-24 02:39:51.013497 DEBUG: Found processing_actions
  - 2020-04-24 02:39:51.013507 INFO: Parsing input actions list
  - 2020-04-24 02:39:51.013511 DEBUG: Parsing action: create_message
  - 2020-04-24 02:39:51.013748 DEBUG: Parsing action: add_qnode(curie=DOID:13636, id=n00)
  - 2020-04-24 02:39:51.014009 DEBUG: Parsing action: add_qnode(type=protein, is_set=true, id=n01)
  - 2020-04-24 02:39:51.014030 DEBUG: Parsing action: add_qnode(type=disease, id=n02)
  - 2020-04-24 02:39:51.014045 DEBUG: Parsing action: add_qedge(source_id=n00, target_id=n01, id=e00)
  - 2020-04-24 02:39:51.014061 DEBUG: Parsing action: add_qedge(source_id=n01, target_id=n02, id=e01)
  - 2020-04-24 02:39:51.014076 DEBUG: Parsing action: expand(edge_id=[e00,e01])
  - 2020-04-24 02:39:51.014151 DEBUG: Parsing action: overlay(action=compute_jaccard, start_node_id=n00, intermediate_node_id=n01, end_node_id=n02, virtual_edge_type=J1)
  - 2020-04-24 02:39:51.014179 DEBUG: Parsing action: overlay(action=compute_ngd, virtual_edge_type=N1, source_qnode_id=n00, target_qnode_id=n01)
  - 2020-04-24 02:39:51.014200 DEBUG: Parsing action: overlay(action=compute_ngd, virtual_edge_type=N2, source_qnode_id=n01, target_qnode_id=n02)
  - 2020-04-24 02:39:51.014218 DEBUG: Parsing action: overlay(action=compute_ngd, virtual_edge_type=N3, source_qnode_id=n00, target_qnode_id=n02)
  - 2020-04-24 02:39:51.014250 DEBUG: Parsing action: resultify(ignore_edge_direction=true, compute_confidence=true)
  - 2020-04-24 02:39:51.014264 DEBUG: Parsing action: filter_results(action=sort_by_confidence, direction=descending, max_results=50)
  - 2020-04-24 02:39:51.015147 INFO: Processing action 'create_message' with parameters None
  - 2020-04-24 02:39:51.015157 INFO: Creating an empty template ARAX Message
  - 2020-04-24 02:39:51.015324 INFO: Processing action 'add_qnode' with parameters {'curie': 'DOID:13636', 'id': 'n00'}
  - 2020-04-24 02:39:51.015338 INFO: Adding a QueryNode to Message with parameters {'id': 'n00', 'curie': 'DOID:13636', 'name': None, 'type': None, 'is_set': None}
  - 2020-04-24 02:39:51.015438 DEBUG: Looking up CURIE DOID:13636 in KgNodeIndex
  - 2020-04-24 02:39:51.015735 INFO: Processing action 'add_qnode' with parameters {'type': 'protein', 'is_set': 'true', 'id': 'n01'}
  - 2020-04-24 02:39:51.015749 INFO: Adding a QueryNode to Message with parameters {'id': 'n01', 'curie': None, 'name': None, 'type': 'protein', 'is_set': 'true'}
  - 2020-04-24 02:39:51.015823 INFO: Processing action 'add_qnode' with parameters {'type': 'disease', 'id': 'n02'}
  - 2020-04-24 02:39:51.015833 INFO: Adding a QueryNode to Message with parameters {'id': 'n02', 'curie': None, 'name': None, 'type': 'disease', 'is_set': None}
  - 2020-04-24 02:39:51.015889 INFO: Processing action 'add_qedge' with parameters {'source_id': 'n00', 'target_id': 'n01', 'id': 'e00'}
  - 2020-04-24 02:39:51.015900 INFO: Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': None}
  - 2020-04-24 02:39:51.015917 INFO: Processing action 'add_qedge' with parameters {'source_id': 'n01', 'target_id': 'n02', 'id': 'e01'}
  - 2020-04-24 02:39:51.015924 INFO: Adding a QueryEdge to Message with parameters {'id': 'e01', 'source_id': 'n01', 'target_id': 'n02', 'type': None}
  - 2020-04-24 02:39:51.015935 INFO: Processing action 'expand' with parameters {'edge_id': ['e00', 'e01']}
  - 2020-04-24 02:39:51.015944 DEBUG: Applying Expand to Message with parameters {'edge_id': ['e00', 'e01'], 'kp': 'ARAX/KG1', 'use_synonyms': True, 'synonym_handling': 'map_back', 'continue_if_no_results': False, 'enforce_directionality': False}
  - 2020-04-24 02:39:51.015951 DEBUG: Extracting sub query graph to expand
  - 2020-04-24 02:39:51.016156 DEBUG: Query graph to expand is: {'nodes': [{'id': 'n00', 'curie': 'DOID:13636', 'type': 'disease', 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'protein', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'disease', 'is_set': None}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}, {'id': 'e01', 'type': None, 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
  - 2020-04-24 02:39:51.016173 INFO: Expanding edge e00 using ARAX/KG1
  - 2020-04-24 02:39:51.017037 DEBUG: Looking for query nodes to use curie synonyms for
  - 2020-04-24 02:39:51.017325 INFO: Could not find any equivalent curies in KG1 for DOID:13636
  - 2020-04-24 02:39:51.017362 DEBUG: Generating cypher for edge e00 query graph
  - 2020-04-24 02:39:51.017380 INFO: Sending cypher query for edge e00 to KG1 neo4j
  - 2020-04-24 02:39:51.661100 INFO: Query for edge e00 returned results (e00: 20, n00: 1, n01: 20)
  - 2020-04-24 02:39:51.661127 DEBUG: Processing query results for edge e00
  - 2020-04-24 02:39:51.661525 DEBUG: Merging results into Message.KnowledgeGraph
  - 2020-04-24 02:39:51.661550 INFO: Expanding edge e01 using ARAX/KG1
  - 2020-04-24 02:39:51.661644 DEBUG: Looking for query nodes to use curie synonyms for
  - 2020-04-24 02:39:51.661743 DEBUG: Generating cypher for edge e01 query graph
  - 2020-04-24 02:39:51.661767 INFO: Sending cypher query for edge e01 to KG1 neo4j
  - 2020-04-24 02:39:52.656376 INFO: Query for edge e01 returned results (e01: 535, n01: 20, n02: 470)
  - 2020-04-24 02:39:52.656417 DEBUG: Processing query results for edge e01
  - 2020-04-24 02:39:52.665707 DEBUG: Merging results into Message.KnowledgeGraph
  - 2020-04-24 02:39:52.665967 ERROR: Node DOID:13636 has been returned as an answer for multiple query graph nodes (n02 and n00)
```
Which makes sense because we are using the query graph (DOID:13636)--(protein)--(disease) so since DOID:13636 is a disease we will of course get it as a result. Though should this raise an error? It seems to me like this should probably just get filtered out if we don't want it in there rather than raise an error since this will always happen with query graphs like this.

**Comment by amykglen** [comment]
Ah! Yeah, definitely ultimately that should not throw an error, but right now our system isn't set up to allow a node to have **multiple** `qnode_id`s (this is actually what caused #720 as well, and we've started discussing ways to allow multiple qnode_ids there)

**Comment by amykglen** [comment]
(And while for this kind of query perhaps we could just filter out the result with DOID:13636 as an n02 and avoid having to assign multiple qnode_ids, there exist queries that do produce valid results with the same node in different qnode positions - [one example here](https://github.com/RTXteam/RTX/issues/720#issuecomment-617261085))

**Comment by dkoslicki** [comment]
@edeutsch @finnagin @amykglen has this been tested on production? If so, let’s close. If not, please test and then report and/or close

**Comment by edeutsch** [comment]
I have no information. fine to close.

**Comment by dkoslicki** [comment]
@finnagin @amykglen care to comment or close?

**Comment by finnagin** [comment]
@dkoslicki I think this is fine to close as the NGD stuff is working but is still erroring due to the issue #720 which is being discussed and worked on in that issue and this query should work after that work is done as the NGD portion runs successfully now.
