### ISSUE TITLE
error in RTXFeedback

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#728]
The following code:
```
    query = {"previous_message_processing_plan": {"processing_actions": [
        "add_qnode(name=CHEMBL.COMPOUND:CHEMBL1276308, id=n00)",
        "add_qnode(type=protein, id=n01)",
        "add_qedge(source_id=n00, target_id=n01, id=e00)",
        "expand(edge_id=e00)",
        "resultify()"]}}
    [response, message] = _do_arax_query(query)
    assert response.status == 'OK'
```
causes an exception in `RTXFeedback`
```
Exception ignored in: <function RTXFeedback.__del__ at 0x7f9330e83e60>
Traceback (most recent call last):
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 127, in __del__
    self.disconnect()
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/../../UI/Feedback/RTXFeedback.py", line 187, in disconnect
    engine.dispose()
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2039, in dispose
    self.pool = self.pool.recreate()
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 175, in recreate
    dialect=self._dialect,
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 96, in __init__
    Pool.__init__(self, creator, **kw)
  File "<string>", line 2, in __init__
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
    self.dispatch._update(_dispatch, only_propagate=False)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 150, in _update
    ls, only_propagate=only_propagate
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 392, in _update
    registry._stored_in_collection_multi(self, other, to_associate)
  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/test/lib/python3.7/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
    key = old_listener_to_key[listen_ref]
KeyError: (<weakref at 0x7f9300944a10; to 'function' at 0x7f9300942f80 (on_connect)>,)
```

**Comment by saramsey** [comment]
Hi @edeutsch please let me know if my proposed solution is not OK: (I added a try block in `RTXFeedback.disconnect`)
```
 def disconnect(self):
    session = self.session
    engine = self.engine
    session.close()
    try:
      engine.dispose()
    except:
      pass
```

**Comment by edeutsch** [comment]
Seems reasonable. Not sure it's a real solution, but certainly an okay band-aid.

I don't I've ever had a engine.dispose() fail like this. This is running on your Mac? I wonder if there is some other problem this is a canary for.

**Comment by saramsey** [comment]
Yes, running on my mac. latest version of package dependencies installed using `requirements.txt`.

Generally, I think we need a try block in this kind of code in an object destructor.
