### ISSUE TITLE
error in ARAX_expander pertaining to "malformed node or string"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#736]
I am working on #731 and in the last three days, it appears something has changed on the ARAX server. A few days ago, the following test function in `ARAX_resultify.py` used to complete successfully and return results (now, admittedly the results had an issue with a disconnected node as documented in #731, but nevertheless, there were results):
```
    query = {"previous_message_processing_plan": {"processing_actions": [
            "add_qnode(name=MONDO:0005737, id=n0, type=disease)",
            "add_qnode(type=protein, id=n1)",
            "add_qnode(type=disease, id=n2)",
            "add_qedge(source_id=n0, target_id=n1, id=e0)",
            "add_qedge(source_id=n1, target_id=n2, id=e1)",
            "expand(edge_id=[e0,e1], kp=ARAX/KG2)",
            "resultify(debug=true)"]}}
    [response, message] = _do_arax_query(query)
```
but as of tonight, this code gives an error:
```
['2020-05-12 21:21:40.837327 ERROR: An uncaught error occurred: malformed node or string: ["[\'http://www.disgenet.org\']"]: [\'Traceback (most recent call last):\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/ARAX_query.py", line 491, in executeProcessingPlan\\n    result = expander.apply(message,action[\\\'parameters\\\'], response=response)\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/ARAX_expander.py", line 120, in apply\\n    answer_knowledge_graph = self.__expand_edge(edge_query_graph, kp_to_use)\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/ARAX_expander.py", line 240, in __expand_edge\\n    answer_kg = kg_querier.answer_one_hop_query(query_graph)\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/Expand/kg_querier.py", line 55, in answer_one_hop_query\\n    self.__add_answers_to_kg(dsl_parameters[\\\'synonym_handling\\\'], synonym_usages_dict, kp)\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/Expand/kg_querier.py", line 204, in __add_answers_to_kg\\n    swagger_edge = self.__convert_kg2_edge_to_swagger_edge(edge, qedge_id)\\n\', \'  File "/Users/sramsey/Work/Proj/ncats-translator/git-master/code/ARAX/ARAXQuery/Expand/kg_querier.py", line 286, in __convert_kg2_edge_to_swagger_edge\\n    swagger_edge.provided_by = ast.literal_eval(neo4j_edge.get(\\\'provided_by\\\'))\\n\', \'  File "/usr/local/anaconda3/lib/python3.7/ast.py", line 91, in literal_eval\\n    return _convert(node_or_string)\\n\', \'  File "/usr/local/anaconda3/lib/python3.7/ast.py", line 90, in _convert\\n    return _convert_signed_num(node)\\n\', \'  File "/usr/local/anaconda3/lib/python3.7/ast.py", line 63, in _convert_signed_num\\n    return _convert_num(node)\\n\', \'  File "/usr/local/anaconda3/lib/python3.7/ast.py", line 55, in _convert_num\\n    raise ValueError(\\\'malformed node or string: \\\' + repr(node))\\n\', \'ValueError: malformed node or string: ["[\\\'http://www.disgenet.org\\\']"]\\n\']']
```
I'll provide below some information about my environment. I am using the master branch (just updated a few minutes ago). I am running python 3.7.4 in a virtualenv on macOS 10.14.6 on a MBP with 32 GiB of RAM and plenty of available disk space. I am using the RTXFeedback database set up in MySQL according to the developer notes in the ARAX Wiki (Homebrew MySQL version 8.0.18).

**Comment by saramsey** [comment]
Tentatively classifying this a bug although I am not 100% sure.

**Comment by amykglen** [comment]
ah, thanks - I think this is due to the change to the KG2 provided_by field for issue #706 (which was rolled out to `kg2endpoint2` today, but is not quite fixed)... I can come up with a temporary fix until that issue is resolved.

**Comment by amykglen** [comment]
alright - this is fixed!

**Comment by saramsey** [comment]
wow, thank you!

should I do a git pull before retesting?

**Comment by amykglen** [comment]
yep - changes are in master
