### ISSUE TITLE
BTE error for connection Jared could make via BTE website 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#759]
Mysterious since Jared said he could connect these two:
DSL command:
```
add_qnode(name=Angioedema, id=n1)
add_qnode(name=vasodilation, id=n2)
add_qedge(source_id=n1, target_id=n2, id=e1)
expand(edge_id=[e1], kp=BTE)
resultify()
```
Error encountered:
```
2020-05-20 20:48:01.927245 INFO:  ARAXQuery launching on incoming Message
2020-05-20 20:48:01.927267 INFO:  Examine input query for needed information for dispatch
2020-05-20 20:48:01.927277 INFO:  Found input processing plan. Sending to the ProcessingPlanExecutor
2020-05-20 20:48:01.927285 DEBUG:  Entering executeProcessingPlan
2020-05-20 20:48:01.929888 DEBUG:  No starting messages were referenced. Will start with a blank template Message
2020-05-20 20:48:01.930230 DEBUG:  Found processing_actions
2020-05-20 20:48:01.930244 INFO:  Parsing input actions list
2020-05-20 20:48:01.930252 DEBUG:  Parsing action: add_qnode(name=Angioedema, id=n1)
2020-05-20 20:48:01.930294 DEBUG:  Parsing action: add_qnode(name=vasodilation, id=n2)
2020-05-20 20:48:01.930326 DEBUG:  Parsing action: add_qedge(source_id=n1, target_id=n2, id=e1)
2020-05-20 20:48:01.930362 DEBUG:  Parsing action: expand(edge_id=[e1], kp=BTE)
2020-05-20 20:48:01.930396 DEBUG:  Parsing action: resultify()
2020-05-20 20:48:01.930465 INFO:  Processing action 'add_qnode' with parameters {'name': 'Angioedema', 'id': 'n1'}
2020-05-20 20:48:01.930485 INFO:  Adding a QueryNode to Message with parameters {'id': 'n1', 'curie': None, 'name': 'Angioedema', 'type': None, 'is_set': None}
2020-05-20 20:48:01.930618 DEBUG:  Looking up CURIE Angioedema in KgNodeIndex
2020-05-20 20:48:01.931041 INFO:  Processing action 'add_qnode' with parameters {'name': 'vasodilation', 'id': 'n2'}
2020-05-20 20:48:01.931066 INFO:  Adding a QueryNode to Message with parameters {'id': 'n2', 'curie': None, 'name': 'vasodilation', 'type': None, 'is_set': None}
2020-05-20 20:48:01.931151 DEBUG:  Looking up CURIE vasodilation in KgNodeIndex
2020-05-20 20:48:01.931384 INFO:  Processing action 'add_qedge' with parameters {'source_id': 'n1', 'target_id': 'n2', 'id': 'e1'}
2020-05-20 20:48:01.931406 INFO:  Adding a QueryEdge to Message with parameters {'id': 'e1', 'source_id': 'n1', 'target_id': 'n2', 'type': None}
2020-05-20 20:48:01.931432 INFO:  Processing action 'expand' with parameters {'edge_id': ['e1'], 'kp': 'BTE'}
2020-05-20 20:48:01.931453 DEBUG:  Applying Expand to Message with parameters {'edge_id': ['e1'], 'node_id': None, 'kp': 'BTE', 'enforce_directionality': False, 'use_synonyms': True, 'synonym_handling': 'map_back', 'continue_if_no_results': False}
2020-05-20 20:48:01.931463 DEBUG:  Extracting sub query graph to expand
2020-05-20 20:48:01.931591 DEBUG:  Query graph to expand is: {'nodes': [{'id': 'n1', 'curie': 'HP:0100665', 'type': 'phenotypic_feature', 'is_set': None}, {'id': 'n2', 'curie': 'GO:0042311', 'type': 'biological_process', 'is_set': None}], 'edges': [{'id': 'e1', 'type': None, 'relation': None, 'source_id': 'n1', 'target_id': 'n2', 'negated': None}]}
2020-05-20 20:48:01.931612 INFO:  Expanding edge e1 using BTE
2020-05-20 20:48:02.262778 ERROR:  Encountered a problem while using BioThings Explorer. Traceback (most recent call last): File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/bte_querier.py", line 32, in answer_one_hop_query values=self.__get_curie_local_id(curie)) File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/biothings_explorer/user_query_dispatcher.py", line 102, in __init__ raise Exception("The input_id is not valid. Valid input id types are {}".format(id_types)) Exception: The input_id is not valid. Valid input id types are ['uberon', 'dictybase', 'symbol', 'snomed', 'pombase', 'uniprot', 'mgi', 'cl', 'mesh', 'so', 'samd', 'zfin', 'chembl', 'mp', 'fbbt', 'orphanet', 'wikipathways', 'umls', 'flybase', 'pathwayFigureID', 'sgd', 'tair', 'clo', 'mop', 'omim', 'pr', 'entrez', 'drugbank', 'chebi', 'go', 'rgd', 'dbsnp', 'hp', 'ensembl', 'mondo', 'reactome', 'doid', 'hgnc', 'efo']
```

**Comment by amykglen** [comment]
Did some looking into this, and there are a couple problems here:

1. BTE can't do `(curie)--(curie)` expansions (only `(curie)--(some type of node, e.g., 'disease')`)
2. BTE only does directional queries, and the connection BTE has between the two nodes you're interested appears to go `vasodilation->angioedema`, rather than `angioedema->vasodilation`

For problem 1, I think I could 'hack the system', so to speak, fairly easily by doing a BTE query that goes `(curie1)--(type of curie2)`, and then checking to see if curie2 turned up in the results.

For problem 2, while I see how I could achieve a bidirectional search for a `(curie)--(curie)` qedge (by doing two BTE queries: one that goes `(curie1)--(type of curie2)` and one that goes `(curie2)--(type of curie1)` and looking for curie2 in results of the former or curie1 in results of the latter), I'm actually not sure how this could be done for the more typical kind of qedge that goes `(curie)--(some non-specific node)`... I couldn't run a 'reverse' query for that behind the scenes because for BTE, I'm pretty sure the 'input' (source) node has to have a specific identifier... so that's interesting. I'm not sure if we'll really be able to do bidirectional Expands using BTE.

**Comment by amykglen** [comment]
Actually, BTE can do (curie)--(curie) queries - I think I just need to use a different tool than the one I have been (`user_query_dispatcher` rather than `single_edge_query_dispatcher`). Will make that work via Expand.

Still not sure about how to achieve bidirectional queries, but will explore some more.

**Comment by amykglen** [comment]
@jaredroach - when you found this connection, were you using BioThings Explorer's `explain` tool? (https://biothings.io/explorer/explain) 

So your query would've looked something like this:
![Screen Shot 2020-05-28 at 2 23 59 PM](https://user-images.githubusercontent.com/49423686/83195361-f4ec2a00-a0ee-11ea-92a2-7f5fac65ae11.png)

And your results something like this?
![Screen Shot 2020-05-28 at 2 21 48 PM](https://user-images.githubusercontent.com/49423686/83195212-bc4c5080-a0ee-11ea-9a97-b59ff7251f6c.png)

**Comment by jaredroach** [comment]
@amykglen Correct.

**Comment by amykglen** [comment]
ok, got it, thanks. so that's actually one further reason why the DSL @dkoslicki posted doesn't work to reproduce that - the `explain` tool finds connections between two curies via a _two-hop_ connection, whereas David's DSL was one-hop. so the equivalent DSL would be:
```
add_qnode(name=Angioedema, id=n0)
add_qnode(id=n1)
add_qnode(name=vasodilation, id=n2)
add_qedge(source_id=n0, target_id=n1, id=e0)
add_qedge(source_id=n1, target_id=n2, id=e1)
expand(edge_id=[e0,e1], kp=BTE)
resultify()
```
(though this still doesn't work currently because I need to come up with a way to get BTE to do (curie)--(curie) queries)

**Comment by amykglen** [comment]
recap on this issue: I made a number of improvements to BTE Expand, and you can now approximate Jared's query with something like this DSL (https://arax.rtx.ai/?m=2440):
```
add_qnode(name=vasodilation, id=n0)
add_qnode(id=n1, type=gene)
add_qnode(name=acquired angioedema, id=n2)
add_qedge(source_id=n0, target_id=n1, id=e0)
add_qedge(source_id=n1, target_id=n2, id=e1)
expand(kp=BTE)
resultify()
```
limitations:
1. ideally you wouldn't have to specify a `type` for qnode n1, but we don't have a way of achieving that currently since `SingleEdgeQueryDispatcher` requires all qnodes to have types (this is on the list to request from BTE team, see #815)
2. BTE queries must be directed - so if you happened to try this query the other way (acquired angioedema --> vasodilation), you wouldn't get any results

have verified this is working on production, so I'll go ahead and close.
