### ISSUE TITLE
Exception in running test case 'test_update_chemical_substance_entity'

### ISSUE THREAD

**Issue by DeqingQu** [RTXteam/RTX#78]
Exception ignored in: 'neo4j.bolt._io.ChunkedInputBuffer.receive'
BufferError: Existing exports of data: object cannot be re-sized

ERROR: test_update_chemical_substance_entity (UpdateNodesInfoTests.UpdateNodesInfoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 473, in _run_transaction
    return unit_of_work(tx, *args, **kwargs)
  File "/home/qud/RTX/code/reasoningtool/kg-construction/Neo4jConnection.py", line 307, in _get_chemical_substance_node
    return result.single()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 750, in single
    records = list(self)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 706, in records
    keys = self.keys()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 694, in keys
    self._session.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 346, in send
    self._connection.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 263, in send
    self._send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 275, in _send
    raise self.Error("Failed to write to closed connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to write to closed connection Address(host='127.0.0.1', port=7887)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 617, in close
    self.sync()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 588, in sync
    self.session.sync()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 364, in sync
    detail_count, _ = self._connection.sync()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 371, in sync
    self.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 263, in send
    self._send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 275, in _send
    raise self.Error("Failed to write to closed connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to write to closed connection Address(host='127.0.0.1', port=7887)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qud/RTX/code/reasoningtool/kg-construction/UpdateNodesInfoTests.py", line 221, in test_update_chemical_substance_entity
    node = conn.get_chemical_substance_node(node_id)
  File "/home/qud/RTX/code/reasoningtool/kg-construction/Neo4jConnection.py", line 124, in get_chemical_substance_node
    return session.write_transaction(self._get_chemical_substance_node, id)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 491, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 485, in _run_transaction
    raise last_error
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 473, in _run_transaction
    return unit_of_work(tx, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 546, in __exit__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 625, in close
    self.session.rollback_transaction()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 457, in rollback_transaction
    self.__rollback__().consume()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 738, in consume
    list(self)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 706, in records
    keys = self.keys()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 694, in keys
    self._session.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 346, in send
    self._connection.send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 263, in send
    self._send()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 275, in _send
    raise self.Error("Failed to write to closed connection {!r}".format(self.server.address))
neo4j.exceptions.ServiceUnavailable: Failed to write to closed connection Address(host='127.0.0.1', port=7887)

**Comment by DeqingQu** [comment]
It is related to a BufferError bug in neo4j-python-driver. https://github.com/neo4j/neo4j-python-driver/issues/201
The bug is fixed in version 1.5.3. https://github.com/neo4j/neo4j-python-driver/wiki/1.5-changelog

**Comment by DeqingQu** [comment]
We can update neo4j-driver through the following command. 

pip3 install -U neo4j-driver

**Comment by saramsey** [comment]
neo4j-driver has been updated in docker container "rtxsteve" on instance "rtxsteve.saramsey.org"

**Comment by saramsey** [comment]
@dkoslicki is it OK to update the Neo4j python driver in the rtxdev container on instance rtxdev.saramsey.org ?

**Comment by dkoslicki** [comment]
@saramsey Yup, go for it! I'm running locally at the moment
