### ISSUE TITLE
Consider parallel FET with KG1, KG2?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#799]
I'm not sure if this was captured somewhere, but I suggested today at the hackathon that we consider using a "fast parallel" cipher query for many nodes at once, rather than looping over N cipher calls for N nodes. This looping seems necessary for BTE and other KPs. But it seems like we could implement parallel cipher for KG1, KG2. This then becomes another showcase example why having local knowledge graphs is a good thing.

One could argue that NCATS does not consider speed an issue.

**Comment by chunyuma** [comment]
@dkoslicki and I can consider this. But based on what I tested [here](https://github.com/RTXteam/RTX/issues/623#issuecomment-639911173), by repeating `add_qnode()`, `add_qedge()`,  `expand()`, `overlay(action=fisher_exact_test)` and `filter_kg` for each hop, it can significantly reduce the running time.

**Comment by edeutsch** [comment]
I don't feel strongly, but register it here for your consideration. If 2:20 can be turned into 10 seconds with a modest effort, maybe it is worth it.

**Comment by chunyuma** [comment]
I found an interesting thing regarding using a single curie name in `add_qnode()` and using a list of curie names in `add_qnode()`.

I compared the difference in the running time of querying the adjacent nodes between via calling DSL one by one for each query node in parallel and via providing a list of query nodes to call one DSL based on the following examples.  So basically, the parallel method uses a single curie name in `add_qnode()` to call DSL for each query node in parallel and the 'curie list' method uses a list of curie names of query nodes in `add_qnode()` in one DSL. 

The following comparisons were ran on a machine with just 4 cores.

#### Case1
try to find paths: DOID:14330 - protein - chemical_substance - phenotypic_feature
|||||
|-----|-----|-----|-----|
| example id |size of query nodes| time of parallel method | time of curie list |
| 1 (first single-hop) | 39 (connected to 1783 source nodes in KG1) | 15.21 sed | 17.10 sed |
| 2 (second single-hop) | 181 (connected to 8480 source nodes in KG1) | 133.67 sed | 56.10 sed |
| 3 (third single-hop) | 23 (connected to 2517 source nodes in KG1) | 6.36 sed | 10.43 sed |
| 4 (three-hop) | 39/181/23 | 151.85 sed |   82.63 sed     |

#### Case2 
try to find paths: CHEMBL521 - protein - biological_process - protein - disease
|||||
|-----|-----|-----|-----|
| example id |size of query nodes| time of parallel method | time of curie list |
| 1 (first single-hop) |  28 (connected to 2778 source nodes in KG1) |  5.86 sed  |   10.45 sed    |
| 2 (second single-hop) |  6 (connected to 475 source nodes in KG1)  |  2.53 sed |   7.94 sed |
| 3 (third single-hop) | 154 (connected to 5134 source nodes in KG1)  | 30.90 sed |   232.50 min    |
| 4 (fourth single-hop)  | 995 (connected to 19623 source nodes) | 591.00 sed  |  fail  |
| 5 (four-hop) |  28/6/154/995 |  --  |  fail |

We can see that sometimes a single curie name is faster than a list of curie names (eg. case2) but sometimes they are reverse (eg. case1). Also, I found that the 'curie list' has some limits for the size of query nodes. For example, if we query the adjacent nodes connected to 995 source nodes (eg. case2 example4), the 'curie list' method fails. Based on these findings, I think using the parallel method to call DSL for each query node will be better for FET.

I optimized FET script to make it run faster than before by replacing most time-consuming `for` loops with parallel running.  

For the case2 example5, It seems like it passed the overlay step and got stuck in `ARAX_resultify.py` based on the following message. It is strange because it can pass if I just ran with a single hop (eg. case2 example1,2,3,4 Please check the DSL below).

@edeutsch and @amykglen, could you please help me check what's going on in `resultify` step? I have already updated the code in master branch. You should be able to run the DSL command of case example5 via `python ARAX_query.py 6237`. Thank you!

```
Traceback (most recent call last):
  File "test_fisher_exact.py", line 138, in <module>
    result = araxq.query(query)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_query.py", line 177, in query
    result = self.executeProcessingPlan(query)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_query.py", line 498, in executeProcessingPlan
    result = resultifier.apply(message, action['parameters'])
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_resultify.py", line 139, in apply
    self._resultify(describe=False)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_resultify.py", line 217, in _resultify
    ignore_edge_direction)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_resultify.py", line 404, in _get_results_for_kg_by_qg
    return _get_results_for_kg_by_qg(kg, qg, qg_nodes_override_treat_is_set_as_false)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_resultify.py", line 622, in _get_results_for_kg_by_qg
    result = _make_result_from_node_set(dict_kg, node_ids_for_subgraph_by_qnode_id, kg_edge_ids_by_qedge_id, qg, ignore_edge_direction)
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../../ARAX/ARAXQuery/ARAX_resultify.py", line 262, in _make_result_from_node_set
    edge_fits_in_same_direction = (edge.source_id in result_node_ids_by_qnode_id[qedge.source_id] and
  File "/home/ubuntu/work/RTX/code/UI/Feedback/../OpenAPI/python-flask-server/swagger_server/models/edge.py", line 192, in source_id
    @property
KeyboardInterrupt

```


#### Case1
##### Example 1:
```
add_qnode(curie=DOID:14330, id=n00, type=disease)
add_qnode(type=protein, is_set=true, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, virtual_relation_label=FET, target_qnode_id=n01)
resultify()
```
##### Example 2:
```
add_qnode(curie=[UniProtKB:Q5S007,UniProtKB:P27338,UniProtKB:Q99683,UniProtKB:P21728,UniProtKB:P02675], is_set=true, id=n00, type=protein)
add_qnode(type=chemical_substance, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET)
resultify()
```
##### Example 3:
```
add_qnode(curie=[CHEMBL.COMPOUND:CHEMBL59,CHEMBL.COMPOUND:CHEMBL887,CHEMBL.COMPOUND:CHEMBL654], type=chemical_substance, id=n00)
add_qnode(type=phenotypic_feature, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET3)
resultify()
```
##### Example 4:
```
add_qnode(curie=DOID:14330, id=n00, type=disease)
add_qnode(type=protein, is_set=true, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.001, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n01, target_id=n02, id=e01, type=physically_interacts_with)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.001, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=phenotypic_feature, id=n03)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
resultify()
```

#### Case2
##### Example 1:
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, virtual_relation_label=FET, target_qnode_id=n01)
resultify()
```

##### Example 2:
```
add_qnode(id=n00, curie=UniProtKB:P06734, type=protein)
add_qnode(id=n01, type=biological_process)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, virtual_relation_label=FET, target_qnode_id=n01)
resultify()
```
##### Example 3:
```
add_qnode(id=n00, curie=[GO:0051770, GO:0051000, GO:0051712, GO:0007219, GO:0002925], type=biological_process)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, virtual_relation_label=FET, target_qnode_id=n01)
resultify()
```
##### Example 4:
```
add_qnode(id=n00, curie=[UniProtKB:P08727,UniProtKB:Q9HC29,UniProtKB:Q09472,UniProtKB:Q96E22,UniProtKB:P01106,UniProtKB:P09525,UniProtKB:Q96JK9,UniProtKB:P14222,UniProtKB:Q9NYJ7,UniProtKB:O14672,UniProtKB:Q04721,UniProtKB:Q96BI3,UniProtKB:P31249,UniProtKB:P15259,UniProtKB:P50553,UniProtKB:Q9Y5J3,UniProtKB:Q9Y2E6,UniProtKB:Q03014,UniProtKB:P42224,UniProtKB:P26678,UniProtKB:P41595,UniProtKB:Q8WTV0,UniProtKB:P01579,UniProtKB:Q13573,UniProtKB:P55285,UniProtKB:Q9NZ42,UniProtKB:P49810,UniProtKB:Q99466,UniProtKB:Q9Y264,UniProtKB:Q9Y219,UniProtKB:Q92858,UniProtKB:O75365,UniProtKB:Q92793,UniProtKB:O43623,UniProtKB:P78504,UniProtKB:Q9H3D4,UniProtKB:Q9Y239,UniProtKB:Q15554,UniProtKB:P43490,UniProtKB:P01589,UniProtKB:Q9UM47,UniProtKB:Q6V0I7,UniProtKB:Q92542,UniProtKB:Q06330,UniProtKB:P30793,UniProtKB:Q5TAB7,UniProtKB:Q86YT6,UniProtKB:Q99958,UniProtKB:P50052,UniProtKB:P13500,UniProtKB:P78536,UniProtKB:O75052,UniProtKB:O00548,UniProtKB:Q86Y01,UniProtKB:O76050,UniProtKB:Q86UW9,UniProtKB:Q0VG99,UniProtKB:O60603,UniProtKB:Q96RI1,UniProtKB:P01116,UniProtKB:P46527,UniProtKB:Q9BYE0,UniProtKB:P02790,UniProtKB:P55317,UniProtKB:Q9NR96,UniProtKB:Q99500,UniProtKB:P35968,UniProtKB:P01374,UniProtKB:Q96J02,UniProtKB:O14746,UniProtKB:Q12860,UniProtKB:Q8IZL2,UniProtKB:P22460,UniProtKB:P00374,UniProtKB:Q96T58,UniProtKB:Q9UBP5,UniProtKB:P17174,UniProtKB:P49715,UniProtKB:Q9H488,UniProtKB:P23297,UniProtKB:P35228,UniProtKB:P67809,UniProtKB:Q96LB3,UniProtKB:Q2M1K9,UniProtKB:P21741,UniProtKB:Q9UG01,UniProtKB:Q15466,UniProtKB:P35680,UniProtKB:Q9NR61,UniProtKB:Q12948,UniProtKB:P21549,UniProtKB:P06734], type=protein)
add_qnode(type=disease, id=n01)
add_qedge(source_id=n00, target_id=n01, id=e00)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET)
resultify()
```

##### Example 5:
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=biological_process, id=n02)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=protein, id=n03)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n03)
add_qnode(type=disease, id=n04)
add_qedge(source_id=n03, target_id=n04, id=e03)
expand(edge_id=e03, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n03, target_qnode_id=n04, virtual_relation_label=FET4)
resultify()
```

**Comment by amykglen** [comment]
@chunyuma - I think `resultify` is getting maxed out due to the number of possible results because none of the 3 intermediate nodes in your 4-hop query have `is_set=true`. when I change those (`n01`, `n02`, `n03`) to have `is_set=true` so the DSL looks like:
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521, type=chemical_substance)
add_qnode(id=n01, type=protein, is_set=true)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n00, target_qnode_id=n01, virtual_relation_label=FET1)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n01)
add_qnode(type=biological_process, id=n02, is_set=true)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(edge_id=e01, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n01, target_qnode_id=n02, virtual_relation_label=FET2)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n02)
add_qnode(type=protein, id=n03, is_set=true)
add_qedge(source_id=n02, target_id=n03, id=e02)
expand(edge_id=e02, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n02, target_qnode_id=n03, virtual_relation_label=FET3)
filter_kg(action=remove_edges_by_attribute, edge_attribute=fisher_exact_test_p-value, direction=above, threshold=0.01, remove_connected_nodes=t, qnode_id=n03)
add_qnode(type=disease, id=n04)
add_qedge(source_id=n03, target_id=n04, id=e03)
expand(edge_id=e03, kp=ARAX/KG1)
overlay(action=fisher_exact_test, source_qnode_id=n03, target_qnode_id=n04, virtual_relation_label=FET4)
resultify()
```
then case 2 example 5 completes ok for me, producing 484 results. https://arax.rtx.ai/test/?m=2388

while it's probably possible to speed up `resultify`, I think you probably want `is_set=true` for intermediate nodes anyway?

**Comment by chunyuma** [comment]
Thanks @amykglen, I just tried your suggestion and it did work.
