### ISSUE TITLE
get "description" field for each node

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#81]
this work will be done as a feature request for UpdateNodesInfo.py

**Comment by saramsey** [comment]
@DeqingQu come see me when you have time, and we can discuss implementation of this feature.

**Comment by saramsey** [comment]
for microRNAs, it may be better to use the "comments" field from mirBase:
http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc=MI0000681

**Comment by saramsey** [comment]
@DeqingQu can you please look into this?  Can we catch the 502 error in QueryOMIM.py?  See line 67 here for example: https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/kg-construction/QueryReactome.py

https://www.ebi.ac.uk/ols/api/ontologies/hp/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0006963
Status code 404 for url: https://www.ebi.ac.uk/ols/api/ontologies/hp/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0006963
Status code 502 for URL: https://api.omim.org/api/entry?mimNumber=614747&include=text:description&format=json
Traceback (most recent call last):
  File "UpdateNodesInfo.py", line 376, in <module>
    UpdateNodesInfo.update_disease_nodes_desc()
  File "UpdateNodesInfo.py", line 304, in update_disease_nodes_desc
    node['desc'] = QueryOMIM().disease_mim_to_description(node_id)
  File "/mnt/data/sramsey/RTX/code/reasoningtool/kg-construction/QueryOMIMExtended.py", line 92, in disease_mim_to_description
    result_dict = r.json()
AttributeError: 'NoneType' object has no attribute 'json'
rt@ip-172-31-40-65:~/kg-construction$

**Comment by DeqingQu** [comment]
working on it

**Comment by saramsey** [comment]
Hi Steve,

I fixed the 400 bug in QueryOMIMExtended.py. I don’t want to mess up the original QueryOMIM.py, so I copied it to a new file called QueryOMIMExtended.py. There are only two differences between QueryOMIMExtended.py and QueryOMIM.py. 1. 400 bug is fixed in QueryOMIMExtended.py. 2. The requests cache is used in QueryOMIMExtended.py and lru_cache is used in QueryOMIM.py. 

The description field updating for chemical substance is done, but about 50% of the results are “UNKNOWN”.

I think it is fine to run UpdateNodesInfo.py now.

Best Regards,
Deqing Qu

**Comment by saramsey** [comment]
From latest KG (dated Friday 4/27), here are the statistics on completeness of the description fields for different node types (100% means every node has a description field that is not "unknown"):

| anatomical_entity |  97.6% |
| biological_process | 99.9% |
| chemical_substance | 50.2% |
| disease (OMIM:) | 42.3% |
| disease (DOID) | 60.5% |
| microRNA | 98.8% |
| protein | 63.7% | 
| phenotypic_feature | 79.3% |
| pathway | TBD|

**Comment by saramsey** [comment]
dump of latest version of the KG (with the above descriptions) has been pushed to rtxkgdump.saramsey.org:

![screen shot 2018-04-30 at 10 08 31 am](https://user-images.githubusercontent.com/5562107/39440029-75c5e93c-4c5e-11e8-991b-d274c61f7a9b.png)

**Comment by edeutsch** [comment]
great! Why did it got a lot smaller?
