### ISSUE TITLE
bug in QueryMyGeneExtended

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#82]
Running latest version of UpdateNodesInfo.py on rtxdev.saramsey.org inside container "rtxsteve" as user "rt" in directory /mnt/data/sramsey/RTX/code/reasoningtool/kg-construction

Traceback (most recent call last):
  File "UpdateNodesInfo.py", line 138, in <module>
    UpdateNodesInfo.update_protein_nodes()
  File "UpdateNodesInfo.py", line 118, in update_protein_nodes
    UpdateNodesInfo.__update_nodes('protein')
  File "UpdateNodesInfo.py", line 80, in __update_nodes
    node['extended_info_json'] = get_entity_mtd(node_id)
  File "/mnt/data/sramsey/RTX/code/reasoningtool/kg-construction/QueryMyGeneExtended.py", line 31, in get_protein_entity
    results = str(mg.query(protein_id, fields='all', return_raw='True'))
  File "/usr/local/lib/python3.5/dist-packages/mygene/__init__.py", line 450, in query
    from_cache, out = self._get(_url, kwargs, verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/mygene/__init__.py", line 145, in _get
    res.raise_for_status()
  File "/home/rt/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://mygene.info/v3/query?fields=all

**Comment by saramsey** [comment]
@DeqingQu I have figured out how to fix this.  Implementing the fix now....  (this is not a bug in your code; but when I fixed issue requests #80 and #79, it broke UpdateNodesInfo.py)
