### ISSUE TITLE
Q4 broken?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#88]
@dkoslicki I think this was working before, but now with the latest code,
python3 SimilarityQuestionSolution.py -s 'DOID:12365' -t 'disease' -a 'phenotypic_feature' --threshold 0.2 -j

yields:
Traceback (most recent call last):
  File "SimilarityQuestionSolution.py", line 159, in <module>
    main()
  File "SimilarityQuestionSolution.py", line 155, in main
    Q.answer(source_node_ID, target_node_type, association_node_type, use_json=use_json, threshold=threshold, n=n)
  File "SimilarityQuestionSolution.py", line 109, in answer
    for path in all_paths:
  File "/home/rt/.local/lib/python3.5/site-packages/networkx/algorithms/shortest_paths/generic.py", line 387, in all_shortest_paths
    raise nx.NetworkXNoPath()
networkx.exception.NetworkXNoPath

This is the stock Q4 on the web interface. Used to provide nice answers.

**Comment by dkoslicki** [comment]
Two problems I see:
1. Errant print command (fixed)
2. Issue with pathfinding in networkx (will address tomorrow)

**Comment by dkoslicki** [comment]
@edeutsch This should be fixed now (had more debugging code that accidental got pushed to master). Could you pull and check on your end so we can close this issue?

**Comment by edeutsch** [comment]
yes, fixed now, thanks!
