### ISSUE TITLE
test_example_3 in test_ARAX_workflows.py failing in node-normalization branch

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#887]
This test is failing in the `node-normalization` branch:
```
FAILED test_ARAX_workflows.py::test_example_3 - AssertionError: assert 0 in [47, 48]
```
The `knowledge_graph` is empty by the time it reaches `resultify`; not sure what's causing `filter` to remove everything from the KG.
```
____________________________________________________________ test_example_3 _____________________________________________________________

    def test_example_3():
        query = {"previous_message_processing_plan": {"processing_actions": [
            "add_qnode(name=DOID:9406, id=n00)",
            "add_qnode(type=chemical_substance, is_set=true, id=n01)",
            "add_qnode(type=protein, id=n02)",
            "add_qedge(source_id=n00, target_id=n01, id=e00)",
            "add_qedge(source_id=n01, target_id=n02, id=e01)",
            "expand(edge_id=[e00,e01])",
            "overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_relation_label=C1, source_qnode_id=n00, target_qnode_id=n01)",
            "filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=3, remove_connected_nodes=t, qnode_id=n01)",
            "filter_kg(action=remove_orphaned_nodes, node_type=protein)",
            "overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n01, target_qnode_id=n02)",
            "filter_kg(action=remove_edges_by_attribute, edge_attribute=normalized_google_distance, direction=above, threshold=0.85, remove_connected_nodes=t, qnode_id=n02)",
            "resultify(ignore_edge_direction=true, debug=true)",
            "return(message=true, store=false)"
        ]}}
        [response, message] = _do_arax_query(query)
        assert response.status == 'OK'
        print(response.show(level=response.DEBUG))
>       assert len(message.results) in [47, 48]  # :BUG: sometimes the workflow returns 47 results, sometimes 48 (!?)
E       AssertionError: assert 0 in [47, 48]
E        +  where 0 = len([])
E        +    where [] = {'_datetime': '2020-07-06 14:32:04',\n 'code_description': 'Normal completion',\n 'context': 'https://raw.githubusercont...ce', 'essence', 'essence_type'],\n 'terms': None,\n 'tool_version': 'ARAX 0.6.0',\n 'type': 'translator_reasoner_message'}.results

test_ARAX_workflows.py:132: AssertionError
```

here's the log:
```
Response:
  status: OK
  n_errors: 0  n_warnings: 3  n_messages: 115
  - 2020-07-06 14:32:04.723957 INFO: ARAXQuery launching on incoming Message
  - 2020-07-06 14:32:04.723979 INFO: Examine input query for needed information for dispatch
  - 2020-07-06 14:32:04.723989 INFO: Found input processing plan. Sending to the ProcessingPlanExecutor
  - 2020-07-06 14:32:04.723999 DEBUG: Entering executeProcessingPlan
  - 2020-07-06 14:32:04.782524 DEBUG: No starting messages were referenced. Will start with a blank template Message
  - 2020-07-06 14:32:04.783187 DEBUG: Found processing_actions
  - 2020-07-06 14:32:04.783211 INFO: Parsing input actions list
  - 2020-07-06 14:32:04.783221 DEBUG: Parsing action: add_qnode(name=DOID:9406, id=n00)
  - 2020-07-06 14:32:04.784083 DEBUG: Parsing action: add_qnode(type=chemical_substance, is_set=true, id=n01)
  - 2020-07-06 14:32:04.784125 DEBUG: Parsing action: add_qnode(type=protein, id=n02)
  - 2020-07-06 14:32:04.784152 DEBUG: Parsing action: add_qedge(source_id=n00, target_id=n01, id=e00)
  - 2020-07-06 14:32:04.784184 DEBUG: Parsing action: add_qedge(source_id=n01, target_id=n02, id=e01)
  - 2020-07-06 14:32:04.784213 DEBUG: Parsing action: expand(edge_id=[e00,e01])
  - 2020-07-06 14:32:04.784567 DEBUG: Parsing action: overlay(action=overlay_clinical_info, observed_expected_ratio=true, virtual_relation_label=C1, source_qnode_id=n00, target_qnode_id=n01)
  - 2020-07-06 14:32:04.784626 DEBUG: Parsing action: filter_kg(action=remove_edges_by_attribute, edge_attribute=observed_expected_ratio, direction=below, threshold=3, remove_connected_nodes=t, qnode_id=n01)
  - 2020-07-06 14:32:04.784678 DEBUG: Parsing action: filter_kg(action=remove_orphaned_nodes, node_type=protein)
  - 2020-07-06 14:32:04.784703 DEBUG: Parsing action: overlay(action=compute_ngd, virtual_relation_label=N1, source_qnode_id=n01, target_qnode_id=n02)
  - 2020-07-06 14:32:04.784735 DEBUG: Parsing action: filter_kg(action=remove_edges_by_attribute, edge_attribute=normalized_google_distance, direction=above, threshold=0.85, remove_connected_nodes=t, qnode_id=n02)
  - 2020-07-06 14:32:04.784774 DEBUG: Parsing action: resultify(ignore_edge_direction=true, debug=true)
  - 2020-07-06 14:32:04.784797 DEBUG: Parsing action: return(message=true, store=false)
  - 2020-07-06 14:32:04.800319 INFO: Processing action 'add_qnode' with parameters {'name': 'DOID:9406', 'id': 'n00'}
  - 2020-07-06 14:32:04.801771 INFO: Adding a QueryNode to Message with parameters {'id': 'n00', 'curie': None, 'name': 'DOID:9406', 'type': None, 'is_set': None}
  - 2020-07-06 14:32:04.803139 DEBUG: Looking up CURIE DOID:9406 in KgNodeIndex
  - 2020-07-06 14:32:04.808335 INFO: Processing action 'add_qnode' with parameters {'type': 'chemical_substance', 'is_set': 'true', 'id': 'n01'}
  - 2020-07-06 14:32:04.808387 INFO: Adding a QueryNode to Message with parameters {'id': 'n01', 'curie': None, 'name': None, 'type': 'chemical_substance', 'is_set': 'true'}
  - 2020-07-06 14:32:04.808795 INFO: Processing action 'add_qnode' with parameters {'type': 'protein', 'id': 'n02'}
  - 2020-07-06 14:32:04.808829 INFO: Adding a QueryNode to Message with parameters {'id': 'n02', 'curie': None, 'name': None, 'type': 'protein', 'is_set': None}
  - 2020-07-06 14:32:04.809113 INFO: Processing action 'add_qedge' with parameters {'source_id': 'n00', 'target_id': 'n01', 'id': 'e00'}
  - 2020-07-06 14:32:04.809141 INFO: Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': None}
  - 2020-07-06 14:32:04.809173 INFO: Processing action 'add_qedge' with parameters {'source_id': 'n01', 'target_id': 'n02', 'id': 'e01'}
  - 2020-07-06 14:32:04.809187 INFO: Adding a QueryEdge to Message with parameters {'id': 'e01', 'source_id': 'n01', 'target_id': 'n02', 'type': None}
  - 2020-07-06 14:32:04.809208 INFO: Processing action 'expand' with parameters {'edge_id': ['e00', 'e01']}
  - 2020-07-06 14:32:04.809230 DEBUG: Applying Expand to Message with parameters {'edge_id': ['e00', 'e01'], 'node_id': None, 'kp': 'ARAX/KG1', 'enforce_directionality': False, 'use_synonyms': True, 'synonym_handling': 'map_back', 'continue_if_no_results': False}
  - 2020-07-06 14:32:04.809495 DEBUG: Query graph for this Expand() call is: {'nodes': [{'id': 'n00', 'curie': 'DOID:9406', 'type': 'disease', 'is_set': None}, {'id': 'n01', 'curie': None, 'type': 'chemical_substance', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'protein', 'is_set': None}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}, {'id': 'e01', 'type': None, 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
  - 2020-07-06 14:32:04.809529 INFO: Expanding edge e00 using ARAX/KG1
  - 2020-07-06 14:32:04.809592 DEBUG: Looking for query nodes to use curie synonyms for
  - 2020-07-06 14:32:04.809600 DEBUG: Getting curie synonyms for qnode n00 using the NodeSynonymizer
  - 2020-07-06 14:32:04.869160 DEBUG: Generating cypher for edge e00 query graph
  - 2020-07-06 14:32:04.869239 INFO: Sending cypher query for edge e00 to KG1 neo4j
  - 2020-07-06 14:32:05.572023 DEBUG: Processing query results for edge e00
  - 2020-07-06 14:32:05.573366 INFO: Query for edge e00 returned results (e00: 29, n00: 1, n01: 29)
  - 2020-07-06 14:32:05.573400 DEBUG: Deduplicating nodes
  - 2020-07-06 14:32:05.573430 DEBUG: Getting preferred curies for n00 nodes returned in this step via the NodeSynonymizer
  - 2020-07-06 14:32:05.573756 DEBUG: Sending NodeSynonymizer a list of 1 curies
  - 2020-07-06 14:32:05.574982 DEBUG: Got results back from NodeSynonymizer for 1 curies
  - 2020-07-06 14:32:05.575197 DEBUG: Getting preferred curies for n01 nodes returned in this step via the NodeSynonymizer
  - 2020-07-06 14:32:05.575412 DEBUG: Sending NodeSynonymizer a list of 29 curies
  - 2020-07-06 14:32:06.722928 DEBUG: Got results back from NodeSynonymizer for 29 curies
  - 2020-07-06 14:32:06.724906 DEBUG: After deduplication, answer KG counts are: e00: 29, n00: 1, n01: 28
  - 2020-07-06 14:32:06.724953 DEBUG: Removing any self-edges from the answer KG
  - 2020-07-06 14:32:06.725023 DEBUG: Merging answer into Message.KnowledgeGraph
  - 2020-07-06 14:32:06.725073 DEBUG: Pruning any paths that are now dead ends
  - 2020-07-06 14:32:06.725269 INFO: Expanding edge e01 using ARAX/KG1
  - 2020-07-06 14:32:06.725360 DEBUG: Looking for query nodes to use curie synonyms for
  - 2020-07-06 14:32:06.725367 DEBUG: Getting curie synonyms for qnode n01 using the NodeSynonymizer
  - 2020-07-06 14:32:06.778692 DEBUG: Generating cypher for edge e01 query graph
  - 2020-07-06 14:32:06.779068 INFO: Sending cypher query for edge e01 to KG1 neo4j
  - 2020-07-06 14:32:08.406285 DEBUG: Processing query results for edge e01
  - 2020-07-06 14:32:08.513623 INFO: Query for edge e01 returned results (e01: 1368, n01: 29, n02: 240)
  - 2020-07-06 14:32:08.513661 DEBUG: Deduplicating nodes
  - 2020-07-06 14:32:08.514155 DEBUG: Getting preferred curies for n01 nodes returned in this step via the NodeSynonymizer
  - 2020-07-06 14:32:08.514485 DEBUG: Sending NodeSynonymizer a list of 29 curies
  - 2020-07-06 14:32:08.553031 DEBUG: Got results back from NodeSynonymizer for 29 curies
  - 2020-07-06 14:32:08.554836 DEBUG: Getting preferred curies for n02 nodes returned in this step via the NodeSynonymizer
  - 2020-07-06 14:32:08.555096 DEBUG: Sending NodeSynonymizer a list of 240 curies
  - 2020-07-06 14:32:11.531071 DEBUG: Got results back from NodeSynonymizer for 240 curies
  - 2020-07-06 14:32:11.541384 DEBUG: After deduplication, answer KG counts are: e01: 1368, n01: 28, n02: 240
  - 2020-07-06 14:32:11.541738 DEBUG: Removing any self-edges from the answer KG
  - 2020-07-06 14:32:11.544646 DEBUG: Merging answer into Message.KnowledgeGraph
  - 2020-07-06 14:32:11.545948 DEBUG: Pruning any paths that are now dead ends
  - 2020-07-06 14:32:11.554353 INFO: After Expand, Message.KnowledgeGraph has 269 nodes and 1397 edges
  - 2020-07-06 14:32:11.554502 INFO: Processing action 'overlay' with parameters {'action': 'overlay_clinical_info', 'observed_expected_ratio': 'true', 'virtual_relation_label': 'C1', 'source_qnode_id': 'n00', 'target_qnode_id': 'n01'}
  - 2020-07-06 14:32:11.561998 INFO: Converting CURIE identifiers to human readable names
  - 2020-07-06 14:32:11.562458 DEBUG: Computing observed expected ratios.
  - 2020-07-06 14:32:11.562475 INFO: Overlaying observed expected ratios utilizing Columbia Open Health Data. This calls an external knowledge provider and may take a while
  - 2020-07-06 14:32:12.220831 DEBUG: Applying Overlay to Message with parameters {'action': 'overlay_clinical_info', 'observed_expected_ratio': 'true', 'virtual_relation_label': 'C1', 'source_qnode_id': 'n00', 'target_qnode_id': 'n01'}
  - 2020-07-06 14:32:12.221589 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'C1',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'has_observed_expected_ratio_with'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-07-06 14:32:12.221605 DEBUG: Number of nodes in KG is 269
  - 2020-07-06 14:32:12.221796 DEBUG: Number of nodes in KG by type is Counter({'protein': 240, 'chemical_substance': 28, 'disease': 1})
  - 2020-07-06 14:32:12.221806 DEBUG: Number of edges in KG is 1425
  - 2020-07-06 14:32:12.222600 DEBUG: Number of edges in KG by type is Counter({'physically_interacts_with': 1368, 'contraindicated_for': 28, 'has_observed_expected_ratio_with': 28, 'indicated_for': 1})
  - 2020-07-06 14:32:12.223081 DEBUG: Number of edges in KG with attributes is 1140
  - 2020-07-06 14:32:12.224184 DEBUG: Number of edges in KG by attribute Counter({'probability': 1112, 'observed_expected_ratio': 28})
  - 2020-07-06 14:32:12.224204 INFO: Processing action 'filter_kg' with parameters {'action': 'remove_edges_by_attribute', 'edge_attribute': 'observed_expected_ratio', 'direction': 'below', 'threshold': '3', 'remove_connected_nodes': 't', 'qnode_id': 'n01'}
  - 2020-07-06 14:32:12.228393 DEBUG: Removing Edges
  - 2020-07-06 14:32:12.228416 INFO: Removing edges from the knowledge graph with the specified attribute values
  - 2020-07-06 14:32:12.230221 DEBUG: Removing Nodes
  - 2020-07-06 14:32:12.230230 INFO: Removing connected nodes and their edges from the knowledge graph
  - 2020-07-06 14:32:12.233276 INFO: Edges successfully removed
  - 2020-07-06 14:32:12.233333 DEBUG: Applying Overlay to Message with parameters {'action': 'remove_edges_by_attribute', 'edge_attribute': 'observed_expected_ratio', 'direction': 'below', 'threshold': 3.0, 'remove_connected_nodes': True, 'qnode_id': 'n01'}
  - 2020-07-06 14:32:12.234095 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'C1',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'has_observed_expected_ratio_with'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-07-06 14:32:12.234122 INFO: Processing action 'filter_kg' with parameters {'action': 'remove_orphaned_nodes', 'node_type': 'protein'}
  - 2020-07-06 14:32:12.243289 DEBUG: Removing orphaned nodes
  - 2020-07-06 14:32:12.243320 INFO: Removing orphaned nodes
  - 2020-07-06 14:32:12.244215 INFO: Nodes successfully removed
  - 2020-07-06 14:32:12.244318 DEBUG: Applying Overlay to Message with parameters {'action': 'remove_orphaned_nodes', 'node_type': 'protein'}
  - 2020-07-06 14:32:12.245458 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'C1',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'has_observed_expected_ratio_with'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-07-06 14:32:12.245496 INFO: Processing action 'overlay' with parameters {'action': 'compute_ngd', 'virtual_relation_label': 'N1', 'source_qnode_id': 'n01', 'target_qnode_id': 'n02'}
  - 2020-07-06 14:32:12.248036 DEBUG: Computing NGD
  - 2020-07-06 14:32:12.248061 INFO: Computing the normalized Google distance: weighting edges based on source/target node co-occurrence frequency in PubMed abstracts
  - 2020-07-06 14:32:12.248069 INFO: Converting CURIE identifiers to human readable names
  - 2020-07-06 14:32:12.248084 WARNING: Utilizing API calls to NCBI eUtils, so this may take a while...
  - 2020-07-06 14:32:12.248117 DEBUG: Applying Overlay to Message with parameters {'action': 'compute_ngd', 'virtual_relation_label': 'N1', 'source_qnode_id': 'n01', 'target_qnode_id': 'n02', 'default_value': inf}
  - 2020-07-06 14:32:12.249040 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'C1',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'has_observed_expected_ratio_with'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-07-06 14:32:12.249067 INFO: Processing action 'filter_kg' with parameters {'action': 'remove_edges_by_attribute', 'edge_attribute': 'normalized_google_distance', 'direction': 'above', 'threshold': '0.85', 'remove_connected_nodes': 't', 'qnode_id': 'n02'}
  - 2020-07-06 14:32:12.249120 WARNING: Supplied value normalized_google_distance is not permitted. In action {'remove_edges_by_attribute'}, allowable values to edge_attribute are: []
  - 2020-07-06 14:32:12.249138 DEBUG: Applying Overlay to Message with parameters {'action': 'remove_edges_by_attribute', 'edge_attribute': 'normalized_google_distance', 'direction': 'above', 'threshold': 0.85, 'remove_connected_nodes': 't', 'qnode_id': 'n02'}
  - 2020-07-06 14:32:12.249893 DEBUG: Query graph is {'edges': [{'id': 'e00',
            'negated': None,
            'relation': None,
            'source_id': 'n00',
            'target_id': 'n01',
            'type': None},
           {'id': 'e01',
            'negated': None,
            'relation': None,
            'source_id': 'n01',
            'target_id': 'n02',
            'type': None},
           {'id': 'C1',
            'negated': None,
            'relation': 'C1',
            'source_id': 'n00',
            'target_id': 'n01',
            'type': 'has_observed_expected_ratio_with'}],
 'nodes': [{'curie': 'DOID:9406',
            'id': 'n00',
            'is_set': None,
            'type': 'disease'},
           {'curie': None,
            'id': 'n01',
            'is_set': True,
            'type': 'chemical_substance'},
           {'curie': None, 'id': 'n02', 'is_set': None, 'type': 'protein'}]}
  - 2020-07-06 14:32:12.249915 INFO: Processing action 'resultify' with parameters {'ignore_edge_direction': 'true', 'debug': 'true'}
  - 2020-07-06 14:32:12.249943 DEBUG: Applying Resultifier to Message with parameters {'ignore_edge_direction': 'true', 'debug': 'true'}
  - 2020-07-06 14:32:12.250175 WARNING: no results returned; empty knowledge graph
  - 2020-07-06 14:32:12.250196 INFO: Running experimental reranker on results
  - 2020-07-06 14:32:12.250338 INFO: Summary of available edge metrics: {}
  - 2020-07-06 14:32:12.250357 INFO: Processing action 'return' with parameters {'message': 'true', 'store': 'false'}
  - 2020-07-06 14:32:12.250373 INFO: Processing is complete. Transmitting resulting Message back to client.
```

**Comment by dkoslicki** [comment]
@finnagin try replacing the hard-coded threshold with your std deviation filter and see if that helps. We should also check that the results are at least somewhat consistent with what we had in the demo (I.e. the important/interesting stuff) doesn’t get filtered out.

**Comment by dkoslicki** [comment]
And @dkoslicki (note to self and @finnagin) looks like there might be a problem with NGD as it apparently isn’t working (no edges were decorated with NGD, so none to filter). That is, unless the previous filter on `observed_expected_ratio` took all the edge out...

**Comment by finnagin** [comment]
So trying to run the following error: 

```
  - 2020-07-06 21:25:47.112092 ERROR: Encountered a problem using NodeSynonymizer: Traceback (most recent call last):
  File "/home/finn/Documents/rtx_clone/RTX/code/ARAX/ARAXQuery/Expand/expand_utilities.py", line 189, in get_curie_synonyms
    normalizer_results = node_synonymizer.get_normalizer_results(curies, kg_name="KG2")
  File "/home/finn/Documents/rtx_clone/RTX/code/ARAX/ARAXQuery/Expand/../../NodeSynonymizer/node_synonymizer.py", line 1208, in get_normalizer_results
    cursor.execute( f"SELECT unique_concept_curie FROM {kg_prefix}_curie{TESTSUFFIX} WHERE uc_curie = ?", (entity.upper(),) )
sqlite3.OperationalError: no such table: kg2_curie

  - 2020-07-06 21:25:47.112102 ERROR: Cannot expand an edge for which neither end has any curies. (Could not find curies to use from a prior expand step, and neither qnode has a curie specified.)
```

Do I need to do something first with my local mysql database to use the synonymizer?

**Comment by amykglen** [comment]
ah, yep - you need to build/get `node_synonymizer.sqlite` - some instructions from Eric on how to do that are [here](https://github.com/RTXteam/RTX/issues/825#issuecomment-653652955).

downloading it from the server worked well for me - only took a few minutes with:
```
scp ubuntu@arax.rtx.ai:/data/orangeboard/devED/RTX/code/ARAX/NodeSynonymizer/node_synonymizer.sqlite [your_location]
```

**Comment by finnagin** [comment]
Thank you! I'll try that.

**Comment by dkoslicki** [comment]
I think this may be an issue due to both #889 and #885 as in `test_example_3`, only 2 edges are being overlayed with clinical info (both of which have `observed_expected_ratio` well below 3)

**Comment by finnagin** [comment]
Yeah, I just ran it on my end and got the same thing @dkoslicki .

Max of attribute observed_expected_ratio: 0.9033941855174025

**Comment by dkoslicki** [comment]
This turned out to be an issue related to #885, basically needed to fix COHD conversion of new curies to OMOP concept ids. Test passes now in `node-normalizer` branch, so closing.
