### ISSUE TITLE
Error with BTE query using predict_drug_treats_disease in node-normalization branch

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#892]
when I run this DSL in the `node-normalization` branch:
```
add_qnode(curie=DOID:11830, type=disease, id=n00)
add_qnode(type=gene, curie=[UniProtKB:P39060, UniProtKB:O43829, UniProtKB:P20849], is_set=true, id=n01)
add_qnode(type=chemical_substance, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(kp=BTE)
overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_relation_label=P1)
resultify()
```

I'm seeing this error:

`
2020-07-07 12:30:16.307662 ERROR:  An uncaught error occurred: 'NoneType' object is not subscriptable: ['Traceback (most recent call last):\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 501, in executeProcessingPlan\n result = overlay.apply(message, action[\'parameters\'], response=response)\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 142, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 479, in __predict_drug_treats_disease\n response = PDTD.predict_drug_treats_disease()\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 89, in predict_drug_treats_disease\n for equiv_source_curie in self.convert_to_trained_curies(source_curie):\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 42, in convert_to_trained_curies\n equivalent_curies = [x[\'identifier\'] for x in normalizer_result[input_curie][\'equivalent_identifiers\']]\n', "TypeError: 'NoneType' object is not subscriptable\n"]
`

here's the full log:
```
2020-07-07 12:29:43.259378 INFO:  ARAXQuery launching on incoming Message
2020-07-07 12:29:43.259403 INFO:  Examine input query for needed information for dispatch
2020-07-07 12:29:43.259411 INFO:  Found input processing plan. Sending to the ProcessingPlanExecutor
2020-07-07 12:29:43.259418 DEBUG:  Entering executeProcessingPlan
2020-07-07 12:29:43.263836 DEBUG:  No starting messages were referenced. Will start with a blank template Message
2020-07-07 12:29:43.264209 DEBUG:  Found processing_actions
2020-07-07 12:29:43.264225 INFO:  Parsing input actions list
2020-07-07 12:29:43.264233 DEBUG:  Parsing action: add_qnode(curie=DOID:11830, type=disease, id=n00)
2020-07-07 12:29:43.264278 DEBUG:  Parsing action: add_qnode(type=gene, curie=[UniProtKB:P39060, UniProtKB:O43829, UniProtKB:P20849], is_set=true, id=n01)
2020-07-07 12:29:43.264323 DEBUG:  Parsing action: add_qnode(type=chemical_substance, id=n02)
2020-07-07 12:29:43.264348 DEBUG:  Parsing action: add_qedge(source_id=n00, target_id=n01, id=e00)
2020-07-07 12:29:43.264376 DEBUG:  Parsing action: add_qedge(source_id=n01, target_id=n02, id=e01)
2020-07-07 12:29:43.264402 DEBUG:  Parsing action: expand(kp=BTE)
2020-07-07 12:29:43.264422 DEBUG:  Parsing action: overlay(action=predict_drug_treats_disease, source_qnode_id=n02, target_qnode_id=n00, virtual_relation_label=P1)
2020-07-07 12:29:43.264454 DEBUG:  Parsing action: resultify()
2020-07-07 12:29:43.264523 INFO:  Processing action 'add_qnode' with parameters {'curie': 'DOID:11830', 'type': 'disease', 'id': 'n00'}
2020-07-07 12:29:43.264544 INFO:  Adding a QueryNode to Message with parameters {'id': 'n00', 'curie': 'DOID:11830', 'name': None, 'type': 'disease', 'is_set': None}
2020-07-07 12:29:43.265324 DEBUG:  Looking up CURIE DOID:11830 in KgNodeIndex
2020-07-07 12:29:43.268564 INFO:  Processing action 'add_qnode' with parameters {'type': 'gene', 'curie': ['UniProtKB:P39060', 'UniProtKB:O43829', 'UniProtKB:P20849'], 'is_set': 'true', 'id': 'n01'}
2020-07-07 12:29:43.268600 INFO:  Adding a QueryNode to Message with parameters {'id': 'n01', 'curie': ['UniProtKB:P39060', 'UniProtKB:O43829', 'UniProtKB:P20849'], 'name': None, 'type': 'gene', 'is_set': 'true'}
2020-07-07 12:29:43.268839 DEBUG:  Looking up CURIE UniProtKB:P39060 in KgNodeIndex
2020-07-07 12:29:43.270667 DEBUG:  Looking up CURIE UniProtKB:O43829 in KgNodeIndex
2020-07-07 12:29:43.271610 DEBUG:  Looking up CURIE UniProtKB:P20849 in KgNodeIndex
2020-07-07 12:29:43.272705 INFO:  Processing action 'add_qnode' with parameters {'type': 'chemical_substance', 'id': 'n02'}
2020-07-07 12:29:43.272750 INFO:  Adding a QueryNode to Message with parameters {'id': 'n02', 'curie': None, 'name': None, 'type': 'chemical_substance', 'is_set': None}
2020-07-07 12:29:43.273081 INFO:  Processing action 'add_qedge' with parameters {'source_id': 'n00', 'target_id': 'n01', 'id': 'e00'}
2020-07-07 12:29:43.273111 INFO:  Adding a QueryEdge to Message with parameters {'id': 'e00', 'source_id': 'n00', 'target_id': 'n01', 'type': None}
2020-07-07 12:29:43.273141 INFO:  Processing action 'add_qedge' with parameters {'source_id': 'n01', 'target_id': 'n02', 'id': 'e01'}
2020-07-07 12:29:43.273155 INFO:  Adding a QueryEdge to Message with parameters {'id': 'e01', 'source_id': 'n01', 'target_id': 'n02', 'type': None}
2020-07-07 12:29:43.273174 INFO:  Processing action 'expand' with parameters {'kp': 'BTE'}
2020-07-07 12:29:43.273222 DEBUG:  Applying Expand to Message with parameters {'edge_id': ['e00', 'e01'], 'node_id': [], 'kp': 'BTE', 'enforce_directionality': False, 'use_synonyms': True, 'synonym_handling': 'map_back', 'continue_if_no_results': False}
2020-07-07 12:29:43.273470 DEBUG:  Query graph for this Expand() call is: {'nodes': [{'id': 'n00', 'curie': 'DOID:11830', 'type': 'disease', 'is_set': None}, {'id': 'n01', 'curie': ['UniProtKB:P39060', 'UniProtKB:O43829', 'UniProtKB:P20849'], 'type': 'gene', 'is_set': True}, {'id': 'n02', 'curie': None, 'type': 'chemical_substance', 'is_set': None}], 'edges': [{'id': 'e00', 'type': None, 'relation': None, 'source_id': 'n00', 'target_id': 'n01', 'negated': None}, {'id': 'e01', 'type': None, 'relation': None, 'source_id': 'n01', 'target_id': 'n02', 'negated': None}]}
2020-07-07 12:29:43.273501 INFO:  Expanding edge e00 using BTE
2020-07-07 12:29:43.273569 DEBUG:  Looking for query nodes to use curie synonyms for
2020-07-07 12:29:43.273578 DEBUG:  Getting curie synonyms for qnode n00 using the NodeSynonymizer
2020-07-07 12:29:43.285686 DEBUG:  Getting curie synonyms for qnode n01 using the NodeSynonymizer
2020-07-07 12:29:43.303277 WARNING:  BTE cannot do bidirectional queries; the query for this edge will be directed, going: n00-->n01
2020-07-07 12:29:43.593999 DEBUG:  Sending query to BTE: UMLS:C0027092-->Gene
2020-07-07 12:29:45.742985 DEBUG:  Got results back from BTE for this query (502 edges)
2020-07-07 12:29:45.893072 DEBUG:  Sending query to BTE: DOID:11830-->Gene
2020-07-07 12:29:46.310834 DEBUG:  Sending query to BTE: HP:0000545-->Gene
2020-07-07 12:29:46.510188 DEBUG:  Sending query to BTE: MESH:D009216-->Gene
2020-07-07 12:29:48.283867 DEBUG:  Got results back from BTE for this query (487 edges)
2020-07-07 12:29:48.449535 DEBUG:  Sending query to BTE: MONDO:0001384-->Gene
2020-07-07 12:29:49.187337 DEBUG:  Sending query to BTE: OMIM:MTHU036427-->Gene
2020-07-07 12:29:49.193832 INFO:  Query for edge e00 returned results (e00: 10, n00: 2, n01: 3)
2020-07-07 12:29:49.193864 DEBUG:  Deduplicating nodes
2020-07-07 12:29:49.193892 DEBUG:  Getting preferred curies for n00 nodes returned in this step
2020-07-07 12:29:49.194178 DEBUG:  Sending NodeSynonymizer a list of 2 curies
2020-07-07 12:29:49.210348 DEBUG:  Got results back from NodeSynonymizer
2020-07-07 12:29:49.210999 DEBUG:  Getting preferred curies for n01 nodes returned in this step
2020-07-07 12:29:49.211261 DEBUG:  Sending NodeSynonymizer a list of 3 curies
2020-07-07 12:29:49.236810 DEBUG:  Got results back from NodeSynonymizer
2020-07-07 12:29:49.237463 DEBUG:  After deduplication, answer KG counts are: e00: 10, n00: 1, n01: 3
2020-07-07 12:29:49.237500 DEBUG:  Removing any self-edges from the answer KG
2020-07-07 12:29:49.237550 DEBUG:  Merging answer into Message.KnowledgeGraph
2020-07-07 12:29:49.237573 DEBUG:  Pruning any paths that are now dead ends
2020-07-07 12:29:49.237663 INFO:  Expanding edge e01 using BTE
2020-07-07 12:29:49.237758 DEBUG:  Looking for query nodes to use curie synonyms for
2020-07-07 12:29:49.237767 DEBUG:  Getting curie synonyms for qnode n01 using the NodeSynonymizer
2020-07-07 12:29:49.239001 WARNING:  BTE cannot do bidirectional queries; the query for this edge will be directed, going: n01-->n02
2020-07-07 12:29:49.463708 DEBUG:  Sending query to BTE: UMLS:C0251815-->ChemicalSubstance
2020-07-07 12:29:49.847305 DEBUG:  Sending query to BTE: UMLS:C3887702-->ChemicalSubstance
2020-07-07 12:29:50.401337 DEBUG:  Sending query to BTE: UMLS:C4082596-->ChemicalSubstance
2020-07-07 12:29:50.782909 DEBUG:  Sending query to BTE: ENSEMBL:ENSG00000112280-->ChemicalSubstance
2020-07-07 12:29:51.594974 DEBUG:  Got results back from BTE for this query (6 edges)
2020-07-07 12:29:51.834653 DEBUG:  Sending query to BTE: ENSEMBL:ENSG00000182871-->ChemicalSubstance
2020-07-07 12:29:52.907178 DEBUG:  Got results back from BTE for this query (156 edges)
2020-07-07 12:29:53.139192 DEBUG:  Sending query to BTE: ENSEMBL:ENSG00000198081-->ChemicalSubstance
2020-07-07 12:29:53.919247 DEBUG:  Got results back from BTE for this query (2 edges)
2020-07-07 12:29:54.147282 DEBUG:  Sending query to BTE: HGNC:12860-->ChemicalSubstance
2020-07-07 12:29:54.869094 DEBUG:  Got results back from BTE for this query (2 edges)
2020-07-07 12:29:55.084855 DEBUG:  Sending query to BTE: HGNC:2195-->ChemicalSubstance
2020-07-07 12:29:56.053513 DEBUG:  Got results back from BTE for this query (156 edges)
2020-07-07 12:29:56.283305 DEBUG:  Sending query to BTE: HGNC:2217-->ChemicalSubstance
2020-07-07 12:29:57.106850 DEBUG:  Got results back from BTE for this query (6 edges)
2020-07-07 12:29:57.358414 DEBUG:  Sending query to BTE: NCBIGene:1297-->ChemicalSubstance
2020-07-07 12:29:58.338672 DEBUG:  Got results back from BTE for this query (6 edges)
2020-07-07 12:29:58.566281 DEBUG:  Sending query to BTE: NCBIGene:7541-->ChemicalSubstance
2020-07-07 12:29:59.385758 DEBUG:  Got results back from BTE for this query (2 edges)
2020-07-07 12:29:59.605516 DEBUG:  Sending query to BTE: NCBIGene:80781-->ChemicalSubstance
2020-07-07 12:30:00.662039 DEBUG:  Got results back from BTE for this query (156 edges)
2020-07-07 12:30:00.799210 DEBUG:  Sending query to BTE: PR:000005702-->ChemicalSubstance
2020-07-07 12:30:00.914854 DEBUG:  Sending query to BTE: PR:000005722-->ChemicalSubstance
2020-07-07 12:30:01.021686 DEBUG:  Sending query to BTE: PR:000017634-->ChemicalSubstance
2020-07-07 12:30:01.145030 DEBUG:  Sending query to BTE: PR:O43829-->ChemicalSubstance
2020-07-07 12:30:01.260850 DEBUG:  Sending query to BTE: PR:P20849-->ChemicalSubstance
2020-07-07 12:30:01.385414 DEBUG:  Sending query to BTE: PR:P39060-->ChemicalSubstance
2020-07-07 12:30:01.610697 DEBUG:  Sending query to BTE: UNIPROTKB:O43829-->ChemicalSubstance
2020-07-07 12:30:02.362175 DEBUG:  Got results back from BTE for this query (2 edges)
2020-07-07 12:30:02.560804 DEBUG:  Sending query to BTE: UNIPROTKB:P20849-->ChemicalSubstance
2020-07-07 12:30:03.337446 DEBUG:  Got results back from BTE for this query (6 edges)
2020-07-07 12:30:03.711380 DEBUG:  Sending query to BTE: UNIPROTKB:P39060-->ChemicalSubstance
2020-07-07 12:30:04.733048 DEBUG:  Got results back from BTE for this query (156 edges)
2020-07-07 12:30:04.750912 INFO:  Query for edge e01 returned results (e01: 408, n01: 12, n02: 98)
2020-07-07 12:30:04.750959 DEBUG:  Deduplicating nodes
2020-07-07 12:30:04.751368 DEBUG:  Getting preferred curies for n01 nodes returned in this step
2020-07-07 12:30:04.751752 DEBUG:  Sending NodeSynonymizer a list of 12 curies
2020-07-07 12:30:04.761651 DEBUG:  Got results back from NodeSynonymizer
2020-07-07 12:30:04.762183 DEBUG:  Getting preferred curies for n02 nodes returned in this step
2020-07-07 12:30:04.762421 DEBUG:  Sending NodeSynonymizer a list of 98 curies
2020-07-07 12:30:06.277050 DEBUG:  Got results back from NodeSynonymizer
2020-07-07 12:30:06.277148 WARNING:  NodeSynonymizer did not return info for: {'CHEBI:5921', 'CUI:C0596105'}
2020-07-07 12:30:06.281796 DEBUG:  After deduplication, answer KG counts are: e01: 408, n01: 3, n02: 98
2020-07-07 12:30:06.281954 DEBUG:  Removing any self-edges from the answer KG
2020-07-07 12:30:06.282737 DEBUG:  Merging answer into Message.KnowledgeGraph
2020-07-07 12:30:06.283108 DEBUG:  Pruning any paths that are now dead ends
2020-07-07 12:30:06.285436 INFO:  After Expand, Message.KnowledgeGraph has 102 nodes and 418 edges
2020-07-07 12:30:06.285500 INFO:  Processing action 'overlay' with parameters {'action': 'predict_drug_treats_disease', 'source_qnode_id': 'n02', 'target_qnode_id': 'n00', 'virtual_relation_label': 'P1'}
2020-07-07 12:30:16.216144 DEBUG:  Computing drug disease treatment probability based on a machine learning model
2020-07-07 12:30:16.216173 INFO:  Computing drug disease treatment probability based on a machine learning model: See [this publication](https://doi.org/10.1101/765305) for more details about how this is accomplished.
2020-07-07 12:30:16.307662 ERROR:  An uncaught error occurred: 'NoneType' object is not subscriptable: ['Traceback (most recent call last):\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 501, in executeProcessingPlan\n result = overlay.apply(message, action[\'parameters\'], response=response)\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 142, in apply\n getattr(self, \'_\' + self.__class__.__name__ + \'__\' + parameters[\'action\'])() # thank you https://stackoverflow.com/questions/11649848/call-methods-by-string\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_overlay.py", line 479, in __predict_drug_treats_disease\n response = PDTD.predict_drug_treats_disease()\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 89, in predict_drug_treats_disease\n for equiv_source_curie in self.convert_to_trained_curies(source_curie):\n', ' File "/Users/aglen/translator/RTX_new/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Overlay/predict_drug_treats_disease.py", line 42, in convert_to_trained_curies\n equivalent_curies = [x[\'identifier\'] for x in normalizer_result[input_curie][\'equivalent_identifiers\']]\n', "TypeError: 'NoneType' object is not subscriptable\n"]
```

**Comment by edeutsch** [comment]
current behavior of the NodeNormalizer is that if an input_curie is not found anywhere then normalizer_result[input_curie] is None, and so I'm guessing that's why normalizer_result[input_curie]['equivalent_identifiers'] is generating an error?

**Comment by dkoslicki** [comment]
@edeutsch Does this imply that BTE is using curie prefixes that are not "standard"/"kosher" (i.e. not recognized by our node normalizer or the SRI node normalizer)?

**Comment by edeutsch** [comment]
@dkoslicki I don't understand your question. My only point was in the line that appears to be crashing, the reason was likely that NodeNormalizer did not find the curie in question. But I am guessing. A more detailed repro would help narrow that down.

**Comment by edeutsch** [comment]
would be useful to expand the node to look for a result of None for a curie and report the curie that yielded the warning in the log and otherwise handle gracefully.

**Comment by dkoslicki** [comment]
@edeutsch Just about to say the same thing about finding the culprit curie. I initially thought the ` PR:000005702` curies were causing a problem, but it appears the node normalizer handles those just find. @amykglen would be nice to know what curie is causing this issue... but I guess I should handle it since it is definitely a problem in `predict_drug_treats_disease` given the underlying error is:
```
equivalent_curies = [x['identifier'] for x in normalizer_result[input_curie]['equivalent_identifiers']]
```
So I guess a simply `try except` is appropriate here, right @edeutsch? If we can't find a synonymous curie that was in the training data for the ML model, just skip it...

**Comment by edeutsch** [comment]
Well, my suggestion was (translated to Python):

if normalizer_result[input_curie] is None:
    response.warning(f"NodeSynonymizer did not find curie {input_curie}. Skipping..")
    whatever else to handle gracefully

**Comment by amykglen** [comment]
yeah - the NodeSynonymizer can't find results for every single curie, so when that happens in `expand` I just issue a warning listing which curies it couldn't find, and then just don't do any remapping of those curies.

(there are a lot of curies in BTE that the NodeSynonymizer doesn't know about, even though they use desired prefixes - a lot of NCBIGene curies, for example - like these: `'NCBIGene:217698', 'NCBIGene:561339', 'NCBIGene:12346', 'NCBIGene:378998', 'NCBIGene:15115', 'NCBIGene:751535', 'NCBIGene:100195763', 'NCBIGene:793796'` .)

**Comment by dkoslicki** [comment]
Ah, I see. I'll update `predict_drug_treats_disease_ tomorrow with something like @edeutsch's suggestion and just throw a warning

**Comment by edeutsch** [comment]
Note that NodeNormalizer should know about every curie in KG2 and KG1 and (any equivalencies in SRI for KG2 and KG1 curies) but nothing else. Note my query for more equivalencies from the KG2 build process in #888 to expand this.

One exception to be addressed is nodes in KG2 with no name, see #825 . But they would be found but not clustered with anything else.

There's a universe of other curies out there. I don't know how/if we should get them into the NodeSynonymizer. At some level we're duplicating work of SRI at this point. But I think we're far advances of SRI at this point, and better serving KG2 reasoning for sure.

It is possible that the nodes you seek are in SRI but are not in KG2. Those also would not be present. NodeNormalizer does not fall back to SRI node normalizer for things it doesn't know about. It could. At a substantial speed cost. And probably a very low additional hit rate.

**Comment by edeutsch** [comment]
@amykglen note that NCBIGene:217698 is a mouse gene. Handling for multiple species is shaky here. If we start introducing mouse genes into the system, we'll probably want to make our system more species aware. Thus far I thought we were going to stay with human only genes. And maybe some pathogen or comensal genes. If we want to add model organism genes, we probably need to think about this carefully. Maybe we're headed down this road anyway.

**Comment by edeutsch** [comment]
NodeSynonymizer would likely cluster together human genes and mouse genes of the same name/symbol if both in KG2 and that could start to get messy without building in species awareness.

**Comment by amykglen** [comment]
hah, that's funny. yeah, I'm certainly not arguing for including mouse genes in anything. I was just pasting in some curies that come back from BTE that I've seen the synonymizer doesn't know about. (unfortunately I don't think there's a way to ask BTE only for human genes?)

**Comment by edeutsch** [comment]
In any case, if you find that the NodeSynonymizer professes not to know about a curie that you think it should, do let me know.

**Comment by dkoslicki** [comment]
Try except works, test passes, so closing.
