### ISSUE TITLE
Max batch size for NodeSynonymizer - increase it or work around it?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#932]
In the course of processing this query, `expand` tries to send `NodeSynonymizer.get_canonical_curies()` a list of 7744 curies, but `NodeSynonymizer` returns None, I'm assuming because this is over its max batch size of 5000 - thus causing an error in `expand`. 

```
add_qnode(name=DOID:14330, id=n00)
add_qnode(type=protein, is_set=true, id=n01)
add_qnode(type=biological_process, id=n02)
add_qedge(source_id=n00, target_id=n01, id=e00)
add_qedge(source_id=n01, target_id=n02, id=e01)
expand(kp=ARAX/KG2)
resultify()
```

```
2020-07-16 17:22:21.290530 DEBUG:  Query for edge e01 returned results (e01: 82499, n01: 1714, n02: 7744)
2020-07-16 17:22:21.290574 DEBUG:  Deduplicating nodes
2020-07-16 17:22:21.317280 DEBUG:  Getting preferred curies for n01 nodes returned in this step
2020-07-16 17:22:21.317561 DEBUG:  Sending NodeSynonymizer.get_canonical_curies() a list of 1714 curies
2020-07-16 17:22:21.801085 DEBUG:  Got results back from NodeSynonymizer
2020-07-16 17:22:21.807520 DEBUG:  Getting preferred curies for n02 nodes returned in this step
2020-07-16 17:22:21.807789 DEBUG:  Sending NodeSynonymizer.get_canonical_curies() a list of 7744 curies
2020-07-16 17:22:21.807820 DEBUG:  Got results back from NodeSynonymizer
2020-07-16 17:22:21.818745 ERROR:  An uncaught error occurred: 'NoneType' object is not iterable: ['Traceback (most recent call last):\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_query.py", line 491, in executeProcessingPlan\n result = expander.apply(message,action[\'parameters\'], response=response)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 121, in apply\n query_graph, use_synonyms, synonym_handling, log)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 195, in _expand_edge\n answer_kg, edge_to_nodes_map = self._deduplicate_nodes(answer_kg, edge_to_nodes_map, log)\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/ARAX_expander.py", line 290, in _deduplicate_nodes\n canonicalized_nodes = eu.get_preferred_curies(list(unmapped_node_ids), log) if unmapped_node_ids else dict()\n', ' File "/mnt/data/orangeboard/beta/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/../../../../ARAX/ARAXQuery/Expand/expand_utilities.py", line 220, in get_preferred_curies\n unrecognized_curies = {input_curie for input_curie in canonical_curies_dict if not canonical_curies_dict.get(input_curie)}\n', "TypeError: 'NoneType' object is not iterable\n"]
```

I can modify `expand` to only send `NodeSynonymizer` 5000 curies at a time (and improve error catching), but I'm wondering if there's much reasoning behind the 5000 limit? @edeutsch

**Comment by edeutsch** [comment]
The current limit is arbitrary. I build some SQL that is WHERE curie IN ( 'X', 'Y', 'Z' ) where there are up to 5000 XYZs. It looks like the default SQLite SQL maximum is 1 MB, so I could easily increase this to 40,000 and probably not hit the limit. Shall I just increase to 40,000. Is that enough? Or might that run into problems as well? Maybe your code needs to gracefully consider a maximum anyway? I will increase to 40,000. But that doesn't really completely solve the problem. If I don't limit it, a crash is possibly eventually at some batch size less than 100,000 I think.

**Comment by amykglen** [comment]
ok, cool - yeah, 40,000 sounds great. I think that's well above anything I've seen be returned from a query so far... but yes, you're right, I should have some sort of handling in case of ridiculously large numbers of nodes being returned from a KP.

hmm.. if `expand` gets back more than 40,000 nodes (or whatever limit) for a particular qnode_id, should it just kind of truncate the answers and ignore nodes beyond that limit? or should it include all and send them in batches to the `NodeSynonymizer`? at some point it might just be too large for our system to really handle anyway...

**Comment by amykglen** [comment]
or, I suppose you could also batch it within your `NodeSynonymizer` methods, @edeutsch? meaning, do a SQL query for every 40,000 curies passed in...

**Comment by edeutsch** [comment]
yeah, that makes more sense. #Unlimited!

**Comment by amykglen** [comment]
verified this is working on production. thanks!
