### ISSUE TITLE
AssertionError in merge_graphs.py loading kg2-smpdb.json

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#961]
```
(kg2-venv) ubuntu@ip-172-31-51-76:~/kg2-build$ python3 ~/kg2-code/merge_graphs.py --kgFiles /home/ubuntu/kg2-build/kg2-smpdb.json --kgFileOrphanEdges foo.json test.json
[/home/ubuntu/kg2-build/kg2-smpdb.json] reading nodes from file
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/merge_graphs.py", line 52, in <module>
    nodes[node_id] = kg2_util.merge_two_dicts(nodes[node_id], node)
  File "/home/ubuntu/RTX/code/kg2/kg2_util.py", line 472, in merge_two_dicts
    assert False
AssertionError
```

**Comment by saramsey** [comment]
am extracting nodes out of the 15 GB JSON file now...

**Comment by saramsey** [comment]
OK, oddly enough, the error is being tripped when `key` contains "description"

**Comment by saramsey** [comment]
OK, this node has an invalid `description` field (which should be a string or None):
```
        {
            "category": "https://w3id.org/biolink/vocab/ChemicalSubstance",
            "category label": "chemical_substance",
            "creation date": null,
            "deprecated": false,
            "description": {
                "@nil": "true"
            },
            "full name": "Glycerone phosphate",
            "id": "PathWhiz.Compound:42631",
            "iri": "https://pathbank.org/lims#/compounds/42631",
            "name": "Glycerone phosphate",
            "provided by": "PathWhiz:",
            "publications": [],
            "replaced by": null,
            "synonym": [],
            "update date": "2019-08-17 06:08:36"
        },
```

**Comment by saramsey** [comment]
Hi @ericawood, thanks!  Can you please push it to kg2steve2 and test smpdb_csv_to_kg_json.py there?  You can use the "--test" option. Once you've verified that the output JSON is good, then please run it without the "--test" option to rebuild `/home/ubuntu/kg2-build/kg2-smpdb.json` on that instance, and please let me know when it is done. Then I will proceed with the merge step. Thank you!

**Comment by saramsey** [comment]
This looks to be a good sign:
```
(kg2-venv) ubuntu@ip-172-31-51-76:~/kg2-build$ python -m json.tool <kg2-smpdb.json | grep '"@nil": "true"' | wc -l

0
```

**Comment by saramsey** [comment]
rerunning `merge_graphs.py` now...

**Comment by saramsey** [comment]
Problem is fixed now:

<img width="608" alt="Screen Shot 2020-07-22 at 10 43 33 PM" src="https://user-images.githubusercontent.com/5562107/88255274-cf058080-cc6c-11ea-9841-cd48a77b7335.png">
