### ISSUE TITLE
arax.rtx.ai errors

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#966]
At 11pm PDT my ARAX monitoring app started generating errors. Had been running fine until then. No code has been rolled out since I last announced it. Error message is:
```
27.0.0.1 - - [23/Jul/2020 06:01:03] "POST /api/rtx/v1/translate HTTP/1.1" 500 -
[2020-07-23 07:01:03,227] ERROR in app: Exception on /api/rtx/v1/translate [POST]
Traceback (most recent call last):
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/translate_controller.py", line 26, in translate
    query = txltr.format_response(question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 137, in format_response
    question, parameters, error_message, error_code = self.parse_question(input_question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ParseQuestion.py", line 57, in parse_question
    parameters = question.get_parameters(input_question)
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/Question.py", line 302, in get_parameters
    node_label = RU.get_node_property(node, "label")  # TODO: Arnab's UMLS lookup
  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/swagger_server/controllers/../../../../../reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 269, in get_node_property
    record = session.run(query).single()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neo4j/__init__.py", line 444, in run
    self._connect()
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neo4j/__init__.py", line 383, in _connect
    self._connection = self._acquirer(access_mode)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neobolt/direct.py", line 972, in connect
    raise last_error
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neobolt/direct.py", line 964, in connect
    connection = _handshake(s, address, der_encoded_server_certificate, **config)
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/neobolt/direct.py", line 898, in _handshake
    ready_to_read, _, _ = select((s,), (), (), 1)
ValueError: filedescriptor out of range in select()
```

Unclear to me what this means. Suddenly neo4j is having a problem? Started sometime between 10pm and 11pm tonight?

**Comment by saramsey** [comment]
Hmm checked:
- Root filesystem on the host OS is not full (only 54% used)
- inside the `RTX1 container, systemd status for neo4j is "running"
- it's been ten hours since there was an error in the neo4j debug.log file:

```
2020-07-22 05:25:38.403+0000 WARN  badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@61d7dfba{r=0,c=false,a=IDLE,uri=}
root@1d9f9e25e40a:/# date
Thu Jul 23 15:59:08 UTC 2020
```

**Comment by saramsey** [comment]
Does flask need to be restarted?

**Comment by saramsey** [comment]
As of 0918 PDT, this query is working fine:

<img width="947" alt="Screen Shot 2020-07-23 at 9 18 18 AM" src="https://user-images.githubusercontent.com/5562107/88311241-7dd5ab00-ccc5-11ea-9cce-b93365752096.png">

**Comment by edeutsch** [comment]
I restarted flask earlier this morning and that seems to have fixed the problem. strange. closing.

**Comment by saramsey** [comment]
Random idea: 

Is there a way to run the exact query that the ARAX monitoring app runs, on the command-line?

Rationale: If a similar situation happens again (i.e., we are getting a stack-backtrace) on the ARAX monitor app, it might be nice to be able to run the same query for testing purposes. Perhaps this is already possible?
