### ISSUE TITLE
SQL syntax error with NodeSynonymizer.get_canonical_curies(curies)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#967]
Running this in `master`:

```
node_ids = ['CHEMBL.MECHANISM:potassium_channel,_inwardly_rectifying,_subfamily_j,_member_11_opener', 'CHEMBL.MECHANISM:potassium_channel,_inwardly_rectifying,_subfamily_j,_member_8_opener', 'CHEMBL.MECHANISM:endothelin_receptor,_et-a/et-b_antagonist', 'CHEMBL.MECHANISM:amylin_receptor_amy1,_calcr/ramp1_agonist', 'CHEMBL.MECHANISM:sulfonylurea_receptor_2,_kir6.2_opener', 'CHEMBL.MECHANISM:sulfonylurea_receptor_1,_kir6.2_blocker', 'CHEMBL.MECHANISM:amiloride-sensitive_sodium_channel,_enac_blocker', 'CHEMBL.MECHANISM:hepatitis_c_virus_serine_protease,_ns3/ns4a_inhibitor', 'CHEMBL.MECHANISM:1,3-beta-glucan_synthase_inhibitor', "CHEMBL.MECHANISM:3',5'-cyclic_phosphodiesterase_inhibitor", 'CHEMBL.MECHANISM:dna_topoisomerase_i,_mitochondrial_inhibitor', 'CHEMBL.MECHANISM:carbamoyl-phosphate_synthase_[ammonia],_mitochondrial_positive_allosteric_modulator', 'CHEMBL.MECHANISM:parp_1,_2_and_3_inhibitor', 'CHEMBL.MECHANISM:c-jun_n-terminal_kinase,_jnk_inhibitor', 'CHEMBL.MECHANISM:voltage-gated_potassium_channel,_kqt;_kcnq2(kv7.2)/kcnq3(kv7.3)_activator', 'CHEMBL.MECHANISM:hla_class_ii_histocompatibility_antigen,_drb1-10_beta_chain_other', 'CHEMBL.MECHANISM:hla_class_ii_histocompatibility_antigen,_drb1-15_beta_chain_modulator', 'CHEMBL.MECHANISM:indoleamine_2,3-dioxygenase_inhibitor', 'CHEMBL.MECHANISM:5,6-dihydroxyindole-2-carboxylic_acid_oxidase_other', 'CHEMBL.MECHANISM:amine_oxidase,_copper_containing_inhibitor', 'CHEMBL.MECHANISM:carnitine_o-palmitoyltransferase_1,_muscle_isoform_inhibitor', 'CHEMBL.MECHANISM:troponin,_cardiac_muscle_positive_modulator', 'CHEMBL.MECHANISM:isocitrate_dehydrogenase_[nadp],_mitochondrial_inhibitor']
canonical_curie_info = synonymizer.get_canonical_curies(node_ids)
```

Currently gives me this error:

```
Traceback (most recent call last):
  File "create_canonicalized_kg_json.py", line 39, in <module>
    main()
  File "create_canonicalized_kg_json.py", line 35, in main
    create_canonicalized_kg_json()
  File "create_canonicalized_kg_json.py", line 25, in create_canonicalized_kg_json
    canonical_curie_info = synonymizer.get_canonical_curies(comma_node_ids)
  File "/Users/aglen/translator/RTX_new/RTX/code/kg2/canonicalized/../../ARAX/NodeSynonymizer/node_synonymizer.py", line 1223, in get_canonical_curies
    cursor.execute( sql )
sqlite3.OperationalError: near "'-CYCLIC_PHOSPHODIESTERASE_INHIBITOR'": syntax error
```

**Comment by edeutsch** [comment]
fix pushed to `master`

who knew we would see curies like this:
CHEMBL.MECHANISM:3',5'-cyclic_phosphodiesterase_inhibitor
CHEMBL.MECHANISM:5,6-dihydroxyindole-2-carboxylic_acid_oxidase_other

Are these really valid curies??

**Comment by edeutsch** [comment]
oh and thanks for the very nice repro.

**Comment by amykglen** [comment]
awesome! confirmed it's working for me now, thank you.

yeah, pretty strange curies... not sure if they're intended. @saramsey?
I see them in both `kg2endpoint` and `kg2endpoint2` with:
```
match (n) where n.id in ["CHEMBL.MECHANISM:3',5'-cyclic_phosphodiesterase_inhibitor", "CHEMBL.MECHANISM:5,6-dihydroxyindole-2-carboxylic_acid_oxidase_other"] return n
```

**Comment by amykglen** [comment]
confirmed this fix is working on `/test`.
