### ISSUE TITLE
Errors in normalized google distance code

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#99]
@finnagin Looks like some of the code you pushed resulted in the following errors:
```python
python3 Q2Solution.py -j
Traceback (most recent call last):
  File "Q2Solution.py", line 294, in <module>
    main()
  File "Q2Solution.py", line 291, in main
    res = answerQ2(drug, disease, k, use_json)
  File "Q2Solution.py", line 114, in answerQ2
    RU.weight_graph_with_google_distance(g, context_node_id=disease_name, context_node_descr=disease_descr, default_value=max_gd)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py", line 809, in weight_graph_with_google_distance
    gd_temp = NormGoogleDistance.get_ngd_for_all([source_id, target_id, context_node_id], [source_descr, target_descr, context_node_descr])
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/NormGoogleDistance.py", line 152, in get_ngd_for_all
    ngd = QueryNCBIeUtils.multi_normalized_google_distance(terms_combined,mesh_flags)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 394, in multi_normalized_google_distance
    counts = QueryNCBIeUtils.multi_pubmed_hits_count(search_string, n_terms=len(name_list))
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 370, in multi_pubmed_hits_count
    res_int += [int(res.json()['esearchresult']['translationstack'][a]['count'])]
TypeError: string indices must be integers
```

**Comment by finnagin** [comment]
@dkoslicki Would it be possible to get the `[source_id, target_id, context_node_id], [source_descr, target_descr, context_node_descr]` that was passed to `NormGoogleDistance.get_ngd_for_all` in `ReasoningUtilities.py` that triggered this error?
